### ISSUE TITLE
I am not able to assemble virus sectors in CLB on PROD

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/checklistbank#1000]
For attention of @thomasstjerne 

I need to assemble children taxa from ICTV dataset in newly created top unranked taxon “Viruses” https://data.catalogueoflife.org/catalogue/3/assembly?datasetKey=1014&sourceTaxonKey=xS2

I drag-&-dropped kingdoms from ICTV datasets, but there were no expected results: there was no popup menu with further steps, and children were not established. Seems, drag-&-drop function does not work:

![image](https://user-images.githubusercontent.com/28574252/152574119-8f1ce130-574b-4e46-99e9-a6400c04da60.png)

Note: a day ago, I have completed these steps in DEV successfully.

**Comment by yroskov** [comment]
2022-02-07: today assembly is working. I have completed assembly of viruses using Firefox.

However, during assembly of sets of kingdoms, families and genera, first click on "Attach' button didn't perform any further actions; second click shown TypeError message, but all expected steps triggered and completed.

![image](https://user-images.githubusercontent.com/28574252/152806745-52586ddc-ad82-43d8-900b-457e5ef2bf13.png)

**Comment by thomasstjerne** [comment]
Nice catch @yroskov 
A fix is being deployed now
