### ISSUE TITLE
CLB, Assembly tool does not work for Viruses - Replace

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/checklistbank#1002]
[Frontend version: 1fce520 February 9, 2022 8:47 AM](https://github.com/CatalogueOfLife/checklistbank/tree/1fce520)[Backend version: a33964d February 7, 2022 12:00 AM](https://github.com/CatalogueOfLife/backend/tree/a33964d) 

I am trying to assemble new ICTV data in the CoL Tree on PROD: https://data.catalogueoflife.org/catalogue/3/assembly?datasetKey=1014

My steps: 
1. Deleted all old sectors in unranked group Viruses
2. Deleted Viruses subtree
3. Established Viruses again as unranked group in the root
4. Dragged & dropped Viruses from ICTV in Viruses in CoL. Menu "Cancel-Attach-Replace-Union" appeared. But there are no actions after I clicked button "Replace": 

![image](https://user-images.githubusercontent.com/28574252/153482039-b3ee4e70-c53f-4c62-97f7-01d7283cd047.png) 

@thomasstjerne, could you pls help with this?

**Comment by thomasstjerne** [comment]
A sector need a target node and can therefore not replace a root taxon. The UI is now updated so that this option is not available for roots

**Comment by mdoering** [comment]
Can't you drag virus to virus and create a union sector? It worked for me on dev:
https://data.dev.catalogueoflife.org/catalogue/2075/assembly

**Comment by yroskov** [comment]
Will try "Union" now

**Comment by yroskov** [comment]
Virus to Virus, Union: hmm, only 5 of 6 realms "moved", and no any other taxa from  the root:

![image](https://user-images.githubusercontent.com/28574252/153602648-c03aff15-5cee-48a5-a577-57dbe05f0106.png)

**Comment by yroskov** [comment]
Syncing now. Let see, what will be happened next.

**Comment by yroskov** [comment]
Final result: CoL has a single sector "Viruses" for ICTV:
![image](https://user-images.githubusercontent.com/28574252/153605195-7c3e28a2-c557-47fd-a2e8-c5e48f7c4503.png)

It shown as a single sector in ICTV window (Assembly):
![image](https://user-images.githubusercontent.com/28574252/153605426-8ba90726-e140-42df-a876-8a40212d87b9.png)
 
Not sure that it is clear that viruses have a single sector in CoL window (Assembly):
![image](https://user-images.githubusercontent.com/28574252/153605000-2407d1d9-d4d3-4e12-a09b-96c59217e06d.png)
