### ISSUE TITLE
CLB: failure of Project - Sectors report

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/checklistbank#1007]
CLB on PROD
[Frontend version: 1bb80f5 February 11, 2022 1:19 PM](https://github.com/CatalogueOfLife/checklistbank/tree/1bb80f5)[Backend version: c94dbef February 15, 2022 12:00 AM](https://github.com/CatalogueOfLife/backend/tree/c94dbef)

@thomasstjerne, @mdoering  

I have opened  Project - Sectors and typed in "ITIS" awaiting report on ITIS sectors. I have got a white screen (9.45-10.00 am, Champaign).

![image](https://user-images.githubusercontent.com/28574252/154304957-9410e786-40ea-4d5d-81bf-835749430618.png)

White screen as a result:

![image](https://user-images.githubusercontent.com/28574252/154304678-7b4c6796-3c90-4b79-bfdc-e74695bf5887.png)

**Comment by timrobertson100** [comment]
If it is not a bad response, then I think [this line](https://github.com/CatalogueOfLife/checklistbank/blob/master/src/pages/catalogue/CatalogueSectors/SectorTable.js#L185) should read:

```
                    textToHighlight={
                      _.get(record, "subject.name")
                        ? record.subject.name.toString()
                        : ""
```

**Comment by mdoering** [comment]
Thanks Tim, looking into this. It's an unexpected response. If the subject (or target) of a sector is "broken" this means we cannot link to the source and do not have a working ID at hand. The name should have been stored when the sector was created and should not change - it is actually used to rematch broken sectors and lookup the current id. 

Sth must have gone wrong when the sector got created. Hm, it was created in 2020 and only now modified.

**Comment by mdoering** [comment]
looking at the database there is just this one ITIS sector without a subject name, odd.
I will try to manually correct it based on older releases...

**Comment by mdoering** [comment]
[Archostemata](https://data.catalogueoflife.org/dataset/2144/taxon/109217) is a suborder of Coleoptera, so looks good

**Comment by yroskov** [comment]
Unfortunately, I cannot confirm that exactly Archostemata is missing among ITIS sectors, because I still have white window on screen for ITIS sectors report: 
https://data.catalogueoflife.org/catalogue/3/sector?limit=100&offset=0&subjectDatasetKey=2144

![image](https://user-images.githubusercontent.com/28574252/154314726-a3580fe4-5cdf-4100-a839-ab12980bd557.png)

**Comment by yroskov** [comment]
Before a white window, "error 403" message flashes for a second.

**Comment by yroskov** [comment]
Re-login failed with 401 error:

![image](https://user-images.githubusercontent.com/28574252/154315737-d1db551b-fcac-45c7-9873-64915e90e504.png)

**Comment by mdoering** [comment]
Updated the database manually, works for me now

**Comment by mdoering** [comment]
That sector now also shows as broken, let me try to rematch it and monitor what happens.

**Comment by mdoering** [comment]
Fails to rematch, but the name stays and it simply remains as broken.
I guess I hand over to you to manually rematch it, delete it or do what you think should be done with that sector.
There should be 116 names in the project for that sector still.

**Comment by mdoering** [comment]
> No Sync option in this broken sector

Obviously not if its broken. You can manually edit the sector if you know where in ITIS this now belongs

**Comment by mdoering** [comment]
Let me try to fix this, I am surprised the rematch did not work cause it still exists:
https://data.catalogueoflife.org/dataset/2144/taxon/109217

**Comment by yroskov** [comment]
woops: I already kicked off deletion of Archostemata as a sector in Col

**Comment by mdoering** [comment]
Also fine, but to preserve history it is always preferrable to rematch and keep the sector

**Comment by yroskov** [comment]
Good. many thanks!
