### ISSUE TITLE
Diff tool requires root taxon

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/checklistbank#1011]
I get a 404 if I do not select a root taxon to diff 2 datasets.
It should work without any root:
https://www.dev.checklistbank.org/tools/diff-viewer?root=x4&root2=x4&dataset=2167&dataset2=2143

**Comment by thomasstjerne** [comment]
The api response is empty: https://api.dev.checklistbank.org/dataset/2167/diff/2143

**Comment by mdoering** [comment]
This is odd, it should not. Looking into this

**Comment by mdoering** [comment]
works with fixed backend now!
