### ISSUE TITLE
Avoid GBIF caching Plazi images

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/checklistbank#1020]
https://www.checklistbank.org/dataset/2406/taxon/03E387B4FFC0CD0056C40AC6FF61FF66.taxon

uses GBIF thumbor to show Plazi images like this:
https://api.gbif.org/v1/image/unsafe/x260/https://zenodo.org/record/5905165/files/figure.png

For copyright reasons we should avoid storing the images. Could we avoid any image caching at all maybe, even if slow?

**Comment by mdoering** [comment]
@gsautter would it be an option to run a [thumbor image cache](https://github.com/thumbor/thumbor) at Plazi to be publicly used for the plazi/zenodo images? You could configure it to only accept the zenodo domain if needed.

**Comment by gsautter** [comment]
@mdoering what kind of setup do you have in mind? Maybe better to _talk_ this through ... especially, as loading the figures from an external cache doesn't seem to be a problem, why not display them directly from Zenodo?

**Comment by mdoering** [comment]
Happy to talk this through, Guido. It is working without the cache, so there is no desperate need. We use thumbor to a) resize images and create thumbnails and b) cache images which have various loading times. Not sure if http2 is an issue as well.

The 6 Zenodo images from the above webpage take up to 22s on my good connection and 2 of them never return with a full image after 2 minutes. A reload gets them all within 17s.
