### ISSUE TITLE
CLB problem: Assembly tool does not work

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/checklistbank#1029]
[Frontend version: f5a3a54 March 23, 2022 11:05 AM](https://github.com/CatalogueOfLife/checklistbank/tree/f5a3a54)[Backend version: 6935275 March 21, 2022 12:00 AM](https://github.com/CatalogueOfLife/backend/tree/6935275)

https://www.checklistbank.org/catalogue/3/assembly?assemblyTaxonKey=3d5881e9-8b95-44a5-a49f-869999302604&datasetKey=2232&sourceTaxonKey=xPW

For attention of @thomasstjerne & @mdoering:
 
Assembly tool does not work (2022-03-25):  when I tried to establish WCVP sector "family Acoraceae" in the tree, the software did not respond to drug-&-drop in the family Acoraceae, nor in the parent order Acorales.  

![image](https://user-images.githubusercontent.com/28574252/160141719-ad2acc0e-7d29-4c42-b688-c847d0fcf6a4.png)

**Comment by mdoering** [comment]
@thomasstjerne please look into the problem. It is the same that I experienced last week when I called you and seems to happen more often.

**Comment by yroskov** [comment]
Drag&Drop assembly work now. Thanks!

Remaining issue:
![image](https://user-images.githubusercontent.com/28574252/160684211-73d8fb52-6845-4ce2-84a7-0875827b7954.png)

It looks like, a button "Replace" does not respond after a first click. It needs a second click to proceed.
