### ISSUE TITLE
CLB: Running Imports report is blank

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/checklistbank#1032]
For @thomasstjerne attention:

I have started sync of all ITIS sectors; opened Running Imports report - it is empty! (well, a ring in top right corner is spinning).  

![image](https://user-images.githubusercontent.com/28574252/161340525-7a425852-334b-41c4-b010-7a542fe27331.png)

**Comment by thomasstjerne** [comment]
Secor syncs are monitored at the sector sync page here https://www.checklistbank.org/catalogue/3/sector/sync?limit=25&offset=0

Syncing sector will not trigger a dataset import job

**Comment by yroskov** [comment]
Sorry. Thanks!
