### ISSUE TITLE
Create synonym pages

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/checklistbank#1034]
Synonyms have more information tight to them than we can show easily on the synonymy list of taxon pages.
It is best to have dedicated Synonym pages that ideally share some component with Taxon pages. It should be very visible that this is not a taxon page, but the following information is shared across all name usages, regardless if accepted or not:

- ID & origin (only show origin if other than source)
- status
- name, i.e. the name label and all other name properties:
   - publishedIn
   - originalSpelling
   - gender & genderAgreement
   - etymology
   - link (in addition to a usage link)
   - remarks (in addition to usage remarks)
- names index link
- external link
- remarks & nomenclaturalNote
- accordingTo with link to reference page via accordingToID
- name relations
- type material

**Comment by thomasstjerne** [comment]
Ideally, I would like to reuse the taxon page for this.
A few questions:
1. I guess the main entity endpoint would be the `/dataset/{key}/nameusage/{id}`?
2. Should we use that in the UI also for consistency? Or would we want `/dataset/{key}/synonym/{id}`?
3. Much of the taxon pages are based on the `/dataset/{key}/taxon/{id}/info` endpoint - does a similar endpoint exist for non-accepted usages?

**Comment by mdoering** [comment]
Makes sense to me to also use nameusage for the path in the UI. Taxon and Synonym identifiers are unique for both, so having a single place to resolve such usage identifiers is perfect. It is just a little less intuitive for some users. But it is always good to have the UI and API match up resource paths.

The taxon info object is very much taxon oriented and does not exist for synonyms, but we could of course also create one to at least bundle the references, name relations etc that also make sense for synonyms. Maybe the separation of Taxon and Synonym in the API resources was also not the best thing to do. Their response type does differ, but often someone with a usage id simply does not know which type it is. Changing that now is pretty impossible as it would impact any existing user of the API. 

As for the info obect(s), how about creating a new `/dataset/{key}/synonym/{id}/info` resource? Or better migrate the taxon one to `/dataset/{key}/nameusage/{id}/info` and use that for both?

**Comment by mdoering** [comment]
Issues are kept in verbatim records which can be linked from both name and usage records.
[If we want to display them](https://github.com/CatalogueOfLife/checklistbank/issues/1305) on interpreted pages we can also include them in the info objects.

**Comment by thomasstjerne** [comment]
> As for the info obect(s), how about creating a new /dataset/{key}/synonym/{id}/info resource? Or better migrate the taxon one to /dataset/{key}/nameusage/{id}/info and use that for both?

I think it would be good to use the same resource from the API (`nameusage`). But I would think that we should keep a taxon route in CLB as well as Catalogue of Life.

**Comment by thomasstjerne** [comment]
Could we have usage ids in this: https://api.checklistbank.org/dataset/2362/name/8247/relations
That would make it possible to link to usages instead of names

**Comment by mdoering** [comment]
I have deployed a version to dev that adds usageID and relatedUsageID to the name relations. Not that in some cases a name might have multiple usages which will lead to multiple relations that differ only by their usage id.
