### ISSUE TITLE
Hide gbifKey from public view

### ISSUE THREAD

**Issue by gdower** [CatalogueOfLife/checklistbank#1036]
As discussed on the stand-up, we are setting the gbifKey to prevent duplicate datasets from being synced into CLB from GBIF. To prevent potential confusion from the CLB metadata linking to often different versions of datasets in GBIF, please hide the gbifKey and probably also the gbifPublisherKey. If the gbifKeys are displayed in the portal, we definitely need to remove it there, too.

**Comment by mdoering** [comment]
Yes agree. But to be clear, the gbifKey is not there to prevend duplicates. It is the link to GBIF that allows us to stay up to date with the GBIF registry. In the vast majority of cases the datasets are the same! It is only for some of the COL sources  that there can be a different version.

**Comment by thomasstjerne** [comment]
We agreed to only show GBIF keys to admins - this is why you both see it.

**Comment by mdoering** [comment]
Maybe we should widen the input for this discussion. I feel it is odd to not have a public link to the GBIF page for datasets that were registered in GBIF and synced to CLB. @timrobertson100 @ahahn-gbif @dhobern @olafbanki do you share concerns of linking dataset pages that show different metadata in some cases? AFAIK these can happen with sources used in COL, but not really in any of the others.

**Comment by dhobern** [comment]
If I understand the issue, some kind of link seems appropriate (particularly if we are expecting to make sense in a DOI world).

**Comment by timrobertson100** [comment]
Links also seem appropriate to me. In time the CLB API will also drive the GBIF sites (gbif.org and hosted portals) but it’s the GBIF dataset key that is stored in many publisher systems (e.g. IPTs)

**Comment by mdoering** [comment]
The GBIF dataset key (UUID) is already exposed in the API. This is purely about the frontend view. Some datasets that are COL sources did have different versions in CLB than in GBIF, e.g. because we have a ColDP based ingestion while the one on GBIF still had an older DWCA one. We wanted to avoid duplication of datasets, so we manually placed the GBIF keys onto those COL sources that already existed in GBIF. @gdower can you remember an example?

**Comment by dhobern** [comment]
The link I was referring to is for front-end users to be able to navigate to the main version/copy.
