### ISSUE TITLE
How do I publish a partial checklist of Catalogue of Life?

### ISSUE THREAD

**Issue by sginzbar** [CatalogueOfLife/checklistbank#1045]
I would like to publish a partial checklist, just the tracheophyta, the vascular plants, from the Catalogue of Life. How do I do this with ChecklistBank?

Steven Ginzbarg
sginzbar@ua.edu

**Comment by mdoering** [comment]
Hi Steven, do you want to _publish_ your own dataset or _download_ a part of the Catalogue of Life?
For downloads you need to have a GBIF account, then you can filter by any group you like.

For publishing your data it needs to be in a supported format such as Darwin Core or [ColDP](https://github.com/CatalogueOfLife/coldp).

**Comment by sginzbar** [comment]
Hi Markus,

I want to download a part of Catalogue of Life. I have a GBIF account. How do I filter CoL by a group?

Steve

From: Markus Döring ***@***.***>
Sent: Saturday, April 30, 2022 11:38 AM
To: CatalogueOfLife/checklistbank ***@***.***>
Cc: Steven Ginzbarg ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [CatalogueOfLife/checklistbank] How do I publish a partial checklist of Catalogue of Life? (Issue #1045)


Hi Steven, do you want to publish your own dataset or download a part of the Catalogue of Life?
For downloads you need to have a GBIF account, then you can filter by any group you like.

For publishing your data it needs to be in a supported format such as Darwin Core or ColDP<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FCatalogueOfLife%2Fcoldp&data=05%7C01%7Csginzbar%40ua.edu%7C33fa6a38015c49a9db0708da2ac7cdf5%7C2a00728ef0d040b4a4e8ce433f3fbca7%7C0%7C0%7C637869334909692956%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=5ngm1AD63vavbr4SanjEtqNXHyD8MS%2B5A%2FJ0EnLuZuM%3D&reserved=0>.

-

**Comment by mdoering** [comment]
Hi Steve,
you go to the downloads page of the latest release (LR) of the COL Checklist:
https://www.checklistbank.org/dataset/3LR/download

When logged in you can chose a root taxon, format and some other options. It will take a few minutes to prepare and you will be notified by email once ready.

**Comment by sginzbar** [comment]
Hi Marcus,

I figured that out. I chose dwca and include bare names. The bare names were not included, maybe because there is not a dwc term for them. When I clicked the download button a message popped up with the url where the download was supposed to be but the page was not found. When I clicked on the link in the email it downloaded.

Steve

From: Markus Döring ***@***.***>
Sent: Saturday, April 30, 2022 9:03 PM
To: CatalogueOfLife/checklistbank ***@***.***>
Cc: Steven Ginzbarg ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [CatalogueOfLife/checklistbank] How do I publish a partial checklist of Catalogue of Life? (Issue #1045)


Hi Steve,
you go to the downloads page of the latest release (LR) of the COL Checklist:
https://www.checklistbank.org/dataset/3LR/download<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.checklistbank.org%2Fdataset%2F3LR%2Fdownload&data=05%7C01%7Csginzbar%40ua.edu%7C245e423a0a3340860f6c08da2b16b79d%7C2a00728ef0d040b4a4e8ce433f3fbca7%7C0%7C0%7C637869673822121982%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=cxVy3SdQhUxV882M%2FNKPHX28aQWVO9Rs4YE3oAKGcoM%3D&reserved=0>

When logged in you can chose a root taxon, format and some other options. It will take a few minutes to prepare and you will be notified by email once ready.

-

**Comment by mdoering** [comment]
Yes, the link is the same as in the mail, but only available once ready.
Bare names should not exist in the COL, there are 7 in the latest release apparently: https://www.checklistbank.org/dataset/9817/names?facet=rank&facet=issue&facet=status&facet=nomStatus&facet=nameType&facet=field&facet=authorship&facet=authorshipYear&facet=extinct&facet=environment&facet=origin&limit=50&offset=0&sortBy=taxonomic&status=bare%20name

**Comment by sginzbar** [comment]
Hi Markus,

I downloaded again DwCA. I didn't check include bare names but they were included. I never received the email from COL Downloads this time. It wasn't in my Junk Email. After waiting I was able to get the download from the link in the popup.

Steve

From: Markus Döring ***@***.***>
Sent: Saturday, April 30, 2022 10:19 PM
To: CatalogueOfLife/checklistbank ***@***.***>
Cc: Steven Ginzbarg ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [CatalogueOfLife/checklistbank] How do I publish a partial checklist of Catalogue of Life? (Issue #1045)


Yes, the link is the same as in the mail, but only available once ready.
Bare names should not exist in the COL, there are 7 in the latest release apparently: https://www.checklistbank.org/dataset/9817/names?facet=rank&facet=issue&facet=status&facet=nomStatus&facet=nameType&facet=field&facet=authorship&facet=authorshipYear&facet=extinct&facet=environment&facet=origin&limit=50&offset=0&sortBy=taxonomic&status=bare%20name<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.checklistbank.org%2Fdataset%2F9817%2Fnames%3Ffacet%3Drank%26facet%3Dissue%26facet%3Dstatus%26facet%3DnomStatus%26facet%3DnameType%26facet%3Dfield%26facet%3Dauthorship%26facet%3DauthorshipYear%26facet%3Dextinct%26facet%3Denvironment%26facet%3Dorigin%26limit%3D50%26offset%3D0%26sortBy%3Dtaxonomic%26status%3Dbare%2520name&data=05%7C01%7Csginzbar%40ua.edu%7Cb7a99a09348c4e0c23dc08da2b2155e1%7C2a00728ef0d040b4a4e8ce433f3fbca7%7C0%7C0%7C637869719431101841%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=gaJlo%2BcH3CdGpSai33z%2BrdOPx2JxOKfoE9Qd6amwKk8%3D&reserved=0>

-

**Comment by sginzbar** [comment]
Hi Markus,

I chose the phylum Tracheophyta as my root taxon but I got other phyla as well.

Tracheophyta                        | phylum        |
Leucophyta R.Br.                    | phylum        |
Bolophyta Nutt.                     | phylum        |
Picrophyta F.Muell.                 | phylum        |
Centrophyta Rchb.                   | phylum        |
Kentrophyta Nutt. ex Torr. & A.Gray | phylum        |
Basileophyta F.Muell.               | phylum        |
Conophyta Schum. ex Hook.fil.       | phylum        |
Equisetophyta D.H.Scott             | phylum

Steve

From: Steven Ginzbarg
Sent: Monday, May 9, 2022 10:57 AM
To: CatalogueOfLife/checklistbank ***@***.***>
Subject: RE: [EXTERNAL] Re: [CatalogueOfLife/checklistbank] How do I publish a partial checklist of Catalogue of Life? (Issue #1045)

Hi Markus,

I downloaded again DwCA. I didn't check include bare names but they were included. I never received the email from COL Downloads this time. It wasn't in my Junk Email. After waiting I was able to get the download from the link in the popup.

Steve

From: Markus Döring ***@***.******@***.***>>
Sent: Saturday, April 30, 2022 10:19 PM
To: CatalogueOfLife/checklistbank ***@***.******@***.***>>
Cc: Steven Ginzbarg ***@***.******@***.***>>; Author ***@***.******@***.***>>
Subject: [EXTERNAL] Re: [CatalogueOfLife/checklistbank] How do I publish a partial checklist of Catalogue of Life? (Issue #1045)


Yes, the link is the same as in the mail, but only available once ready.
Bare names should not exist in the COL, there are 7 in the latest release apparently: https://www.checklistbank.org/dataset/9817/names?facet=rank&facet=issue&facet=status&facet=nomStatus&facet=nameType&facet=field&facet=authorship&facet=authorshipYear&facet=extinct&facet=environment&facet=origin&limit=50&offset=0&sortBy=taxonomic&status=bare%20name<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.checklistbank.org%2Fdataset%2F9817%2Fnames%3Ffacet%3Drank%26facet%3Dissue%26facet%3Dstatus%26facet%3DnomStatus%26facet%3DnameType%26facet%3Dfield%26facet%3Dauthorship%26facet%3DauthorshipYear%26facet%3Dextinct%26facet%3Denvironment%26facet%3Dorigin%26limit%3D50%26offset%3D0%26sortBy%3Dtaxonomic%26status%3Dbare%2520name&data=05%7C01%7Csginzbar%40ua.edu%7Cb7a99a09348c4e0c23dc08da2b2155e1%7C2a00728ef0d040b4a4e8ce433f3fbca7%7C0%7C0%7C637869719431101841%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=gaJlo%2BcH3CdGpSai33z%2BrdOPx2JxOKfoE9Qd6amwKk8%3D&reserved=0>

-

**Comment by mdoering** [comment]
I looked into your archive and it seems all the other phyla are treated as synonyms.
Searching for [Leucophyta](https://www.catalogueoflife.org/data/search?facet=rank&facet=issue&facet=status&facet=nomStatus&facet=nameType&facet=field&facet=authorship&facet=extinct&facet=environment&limit=50&offset=0&q=Leucophyta&rank=phylum&sortBy=taxonomic) shows it is a synonym for the [genus Calocephalus](https://www.catalogueoflife.org/data/taxon/3FS8) though, so there is definitely sth wrong.

The [verbatim data from WorldPlants](https://www.checklistbank.org/dataset/1141/verbatim/1870456) does not indicate any rank. I assume the phylum ending triggered the false interpretation. @gdower @yroskov I assume there is no chance to derive a rank for WP synonyms? We only infer the rank for names when no rank is given - but it can lead to false results in some cases as you can see here. Alternatively to looking at the name ending I might restrict the rank inferal to just UNRANKED, SPECIES or INFRASPECIFIC_NAME for uni/bi/trinomials

**Comment by sginzbar** [comment]
Hi Markus,

I want to download a part of Catalogue of Life. I have a GBIF account. How do I filter CoL by a group?

Steve

From: Markus Döring ***@***.***>
Sent: Saturday, April 30, 2022 11:38 AM
To: CatalogueOfLife/checklistbank ***@***.***>
Cc: Steven Ginzbarg ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [CatalogueOfLife/checklistbank] How do I publish a partial checklist of Catalogue of Life? (Issue #1045)


Hi Steven, do you want to publish your own dataset or download a part of the Catalogue of Life?
For downloads you need to have a GBIF account, then you can filter by any group you like.

For publishing your data it needs to be in a supported format such as Darwin Core or ColDP<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FCatalogueOfLife%2Fcoldp&data=05%7C01%7Csginzbar%40ua.edu%7C33fa6a38015c49a9db0708da2ac7cdf5%7C2a00728ef0d040b4a4e8ce433f3fbca7%7C0%7C0%7C637869334909692956%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=5ngm1AD63vavbr4SanjEtqNXHyD8MS%2B5A%2FJ0EnLuZuM%3D&reserved=0>.

-

**Comment by mdoering** [comment]
Follow this link I gave above and chose a root taxon & format to download:
https://www.checklistbank.org/dataset/3LR/download
