### ISSUE TITLE
CLB, interface bug: I cannot access GSD menu INSIDE PROJECT, if GSD is open OUTSIDE the project

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/checklistbank#1050]
Aim: I need to do my work with GSD as a part of the project, for example, with Collembola.org (id 2130)  

My steps: 
1) Search **Dataset** (menu outside project), open submenu for Collembola.org. (Outside project, because I need to check original metadata in "About").
![image](https://user-images.githubusercontent.com/28574252/168117861-e2436257-e2cd-4d6c-9f9e-cca46adb25e7.png)

2) Trying to open submenu inside project: go to Source (1), click on expand, get only new menu item **Select**. Clicking on Select (2), new menu popup with pre-filled box "Collembola.org" (3).
![image](https://user-images.githubusercontent.com/28574252/168119131-7fcd9adc-ee36-4fbe-899c-658b5ed4e9fb.png)
 
What user need to do next? Click Enter = nothing happened. Click on "Collembola.org" inside search box = list of GSDs drop off, select "Collembola.org" again, nothing happened. The only available option is close the "Select source" box. Done. But I still cannot open GSD menu inside the project.

_Expected behavior_: [perhaps] we need **OK** button inside "Select source" box. If user chosen GSD from the list and clicked OK, box will be closed and GSD menu become accessible. 
![image](https://user-images.githubusercontent.com/28574252/168120574-e9d6103f-8ed5-4725-9e26-f49e168452ab.png)

I need to access this GSD menu:
![image](https://user-images.githubusercontent.com/28574252/168121267-332b8bfb-aada-4a36-af7c-c28476a0ad8e.png)

@thomasstjerne, this bug(?) creates a real problem in my work: it's not easy to access GSD menu inside the project.

**Comment by mdoering** [comment]
I also find the project source selection difficult to work with.
What if the project source and "global" dataset would always be coupled and show the same, no matter where you change it? We could then even remove the source selector and instead have an isSourceOf filter in the main dataset search.
Together with #1051 we could even remove the current releasedFrom filter and just have the isSourceOf one.

**Comment by yroskov** [comment]
>What if the project source and "global" dataset would always be coupled and show the same

It was so few months ago, than it was changed (by mistake?). 

>We could then even remove the source selector and instead have an isSourceOf filter in the main dataset search.

Perhaps, it's better.

My another problem, sometimes, I am clicking on Project selector instead of Dataset selector by mistake. Options looks very similar in the menu.

![image](https://user-images.githubusercontent.com/28574252/168123645-60f60824-861c-4e93-8af5-6cb1dda30b38.png)

**Comment by yroskov** [comment]
>What if the project source and "global" dataset would always be coupled and show the same, no matter where you change it? We could then even remove the source selector and instead have an isSourceOf filter in the main dataset search.

@thomasstjerne, 
Oh! I did find counterargument to this. Now CLB contains a lot of different datasets. It's become very difficult to search and navigate through the main dataset search. I still need a navigation INSIDE the project.

**Comment by mdoering** [comment]
You would have a filter for finding datasets only that are sources of COL. We could prepopulate that to the current project if wanted. But maybe the little lookup filter we have it is actually best if its working fine ;)

Thomas is in Helsinki today, not sure if he follows this conversation.

**Comment by thomasstjerne** [comment]
I have tried in both Chrome and Firefox, and for me it works as expected: Selecting the dataset outside the project, also selects it inside. 
I think I have to watch your screen to fully understand what is going on.
