### ISSUE TITLE
I cannot get a list of names with square bracket in CLB

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/checklistbank#1054]
For attention of @mdoering & @thomasstjerne:

Working with Systema Dipterorum update, I need to flag all accepted names with square brackets (like these:  [Aricia] coronata (Holmgren, 1883); [Cordylura] marginipennis Gimmerthal, 1847; or [Culex]; [Empis]) as _provisionally accepted_. But I cannot do it in CLB, because such names are not included in ISSUE reports, and cannot be find through Workbench search.

It would be nice to include all names with "non-basic" characters in one of ISSUE reports.

Well, it would be nice, if Workbench search can find them as well.

**Comment by yroskov** [comment]
Workbench search does not work for **[**:
![image](https://user-images.githubusercontent.com/28574252/169373174-9b4f2413-d0ed-4cc9-a353-4e67d157f96c.png)


but it works for **[Diastata]**:
![image](https://user-images.githubusercontent.com/28574252/169373003-fe865cf7-b6c4-4b10-8e11-c5f75d138c19.png)

As @gdower mentioned, search for wildcard would be very helpful (**[*]**)

**Comment by mdoering** [comment]
This is a elasticsearch problem we cannot quickly fix I am afraid.
You can search directly on the dataset with a [regular expression](https://www.regular-expressions.info/index.html) to find these names:

https://api.checklistbank.org/dataset/1101/nameusage/pattern?regex=\[[A-Z]

RegEx resources:
 - [introduction](https://www.regular-expressions.info/index.html)
 - [online tester](https://regex101.com)
 - [PostgreSQL RegEx details](https://www.postgresql.org/docs/current/functions-matching.html#FUNCTIONS-POSIX-REGEXP)

@thomasstjerne is it an option to allow users to use the postgres driven pattern search to find relevant usages and then call the search with the nameusage IDs so we get back the kind of response we need for the workbench? Maybe just a quick overlay search that allows you to search by a pattern, tick the ones you are interested in (all by default) and when you close the search the workbench updates based on the IDs? There is a `USAGE_ID` parameter for the search that we could use.

**Comment by thomasstjerne** [comment]
There is now an option to search by entering a RegEx in a text field or to select from this list of presets: https://github.com/CatalogueOfLife/checklistbank/blob/master/public/regex.json

Feel free to add expressions to that list. Each expression should be accompanied by a short description.
