### ISSUE TITLE
Link publisher key to dataset search

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/checklistbank#1058]
When a GBIF publisher key is given for a dataset we should link from the metadata to the dataset search next to the publisher key:
https://www.checklistbank.org/dataset/22895/about
-> https://www.checklistbank.org/dataset?gbifPublisherKey=750a8724-fa66-4c27-b645-bd58ac5ee010

<img width="1158" alt="image" src="https://user-images.githubusercontent.com/327505/170306785-29c9f4f8-fbbf-4219-a835-d6f61a64370e.png">

I also wonder if the verbose GBIF UUIDs can be hidden. They should be accessible for copy paste, but they are not really readable.
We could have a single GBIF row with `Dataset` and `Publisher` as links.
Or include GBIF in the identifiers map below where also Plazi keys show up:
https://www.checklistbank.org/dataset/56531/about
<img width="1127" alt="image" src="https://user-images.githubusercontent.com/327505/170307287-1cb1633b-3490-47d8-b08a-f2a85bdf9372.png">

**Comment by thomasstjerne** [comment]
Mind that GBIF keys are ONLY visible to Admins
