### ISSUE TITLE
Name matching filter no usage cannot be reverted

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/checklistbank#1065]
when you select NO Usages and then unselect it again you cannot see all matches

https://www.checklistbank.org/tools/name-match

<img width="272" alt="image" src="https://user-images.githubusercontent.com/327505/176432720-0884f744-7cf6-4f5e-9426-68efc5b4de86.png">

**Comment by thomasstjerne** [comment]
You have to click the OK button.

**Comment by mdoering** [comment]
If you click "NO usage" and then OK first. Then afterwards uncheck it and select "Usage" and click OK, you end up with no results at all!

<img width="1430" alt="image" src="https://user-images.githubusercontent.com/327505/176639168-a925f4ff-69ee-4533-9cfc-ad4b7a41542f.png">

**Comment by thomasstjerne** [comment]
Is it Safari?
I cant reproduce in Chrome or Firefox

**Comment by mdoering** [comment]
Yes, it was for me. Not sure what @chantalhuijbers was using. Trying in Chrome I can confirm this is working. So it indeed is webkit specific

**Comment by chantalhuijbers** [comment]
I am using Chrome, Version 103.0.5060.66 (Official Build) (64-bit).

When I select NO usage > I get the results.
When I then go back, deselect NO usage, the results remain the same.
If I deselect NO usage, but select Usage, I get 'No Data'.

Using the reset button does not help, it seems to just be stuck.

**Comment by thomasstjerne** [comment]
@chantalhuijbers Mac or PC?

**Comment by chantalhuijbers** [comment]
PC, and yes I use the OK button

**Comment by thomasstjerne** [comment]
Works fine with Safari Version 14.1.2 (16611.3.10.1.6)

**Comment by mdoering** [comment]
Did you change anything? It indeed works now on Safari 15.4.

Just saw that numbers don't match up. The final result has 250/ 318, while the metrics shown at the start mention 1944 names to be matched:
<img width="381" alt="image" src="https://user-images.githubusercontent.com/327505/176692701-a47a948e-b9c3-42bb-a5dc-10bff329a5c4.png">

**Comment by thomasstjerne** [comment]
Didn´t change anything - Did you match against COL? (the default)

**Comment by mdoering** [comment]
Yes, I always tried to match against COL and used the Vicia genus from WCVP-Fabacea as the source

**Comment by chantalhuijbers** [comment]
The numbers indeed don't match up. I use Acacia as example, which after selection says 'Match 3,289 names', but in the result it is 1,269/1,313

**Comment by thomasstjerne** [comment]
The numbers comes around like this:

- Match X names: `dataset/{ds.key}/nameusage/search?TAXON_ID={tx.key}&limit=0`  **1944**

- Result: `dataset/{ds.key}/export.json?taxonID={tx.key}&flat=true` **318**

@mdoering have you got a clue what could be the issue here?

**Comment by mdoering** [comment]
The search does return 1944 names:
https://www.checklistbank.org/dataset/2304/names?TAXON_ID=452522&facet=rank&facet=issue&facet=status&facet=nomStatus&facet=nameType&facet=field&facet=authorship&facet=authorshipYear&facet=extinct&facet=environment&facet=origin&limit=50&offset=0&sortBy=taxonomic

<img width="154" alt="image" src="https://user-images.githubusercontent.com/327505/176905289-cb503513-a0ee-4e9d-849f-5341f072df91.png">

It is 318 accepted names vs 1944 names in total, incl synonyms and misapplied names

**Comment by mdoering** [comment]
it needs `synonyms=true ` to export them all. Maybe even a UI toggle?

**Comment by mdoering** [comment]
https://api.checklistbank.org/dataset/2304/export.json?taxonID=452522&flat=true&synonyms=true
