### ISSUE TITLE
root tag displays "[object Object]" on dataset download page

### ISSUE THREAD

**Issue by tif-calin** [CatalogueOfLife/checklistbank#1076]
Hello really tiny visual bug.

![image](https://user-images.githubusercontent.com/76538249/179379805-51e2459f-f2cd-406a-b40f-afdfa1be8951.png)

My proposed fix:

Change line 106 of `blah`
```jsx
<div>
  {Object.keys(download.request).map((key) => (
    <Tag
      key={key}
    >{`${key}: ${download.request[key]}`}</Tag>
  ))}
</div>
```
to this:
```jsx
<div>
  {Object.keys(download.request).map((key) => {
    const value = download.request[key];
    
    return (
      <Tag
        key={key}
      >{`${key}: ${value?.id || value}`}</Tag>
    ); 
  })}
</div>
```

---

PS is this project open to external contributions? I was originally going to submit a PR with this fix but saw 
```
ERROR: Permission to CatalogueOfLife/checklistbank.git denied to tif-calin.
```

**Comment by mdoering** [comment]
Thanks @tif-calin ! This project is definitely open to pull requests. Have you tried to fork it and create a PR based on your forked changes? I would have thought that should be open to anyone.
