### ISSUE TITLE
matchType field removed?

### ISSUE THREAD

**Issue by sharifX** [CatalogueOfLife/checklistbank#1082]
For the name matching result, there used to be a "matchType" field. I have a previous test result (COL21.8) that had this field. Is removing of this field a permanent change? Is the matchType not available anymore? 

I also included a few screenshots from Jan and Feb 2022 in the ENVRI FAIR use case report (currently in draft). I probably should re-run those tests to reflect the current version.

**Comment by mdoering** [comment]
The field has been removed from the UI on purpose, as it was misleading.
The actual matching is a 2 step process: first match to the central names index, then find names in the actually requested checklist. The match type only reflected the matching of step 2 to the index. It could very well be that the input and output names were exactly identical, but the version in the names index was slightly different and therefore the match type was VARIANT. That was counter intuitive. 

We are working on a unified matching that would then include the field again, comparing the input/output only.
