### ISSUE TITLE
Cannot attach sector to target with union sector

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/checklistbank#1084]
WhenI tried to attach the subphylum Myriapoda to the phylum Arthropoda which already contains another UNION sector. Dragging asks me to replace the sector, which it should not as its a different rank?

<img width="1123" alt="image" src="https://user-images.githubusercontent.com/327505/185852544-5e8db182-6f79-4f5f-8def-34816272524e.png">

**Comment by thomasstjerne** [comment]
In the left hand assembly tree, there is already a sector rooted at the subtree Myriapoda (in the bottom of the picture). This is indicated in both the assemply and source Myriapoda with a little arrow. This should cause the UI to ask for replacement even though In this case, it looks like the target is also the same.
So a better response here would be "This sector already exists"
