### ISSUE TITLE
change representation of authorities in taxonomic names

### ISSUE THREAD

**Issue by myrmoteras** [CatalogueOfLife/checklistbank#1093]
In this case https://www.checklistbank.org/dataset/128002/taxon/03B187D1FFE1DB2ABAE8312F5404E5E3.taxon there are too many `&` in the taxonomic name that should be replaced with `,`

![image](https://user-images.githubusercontent.com/4609956/188115059-7650cce1-26bc-4f2b-bed9-2373f245b00b.png)

**Comment by mdoering** [comment]
It comes like this from your end though: https://www.checklistbank.org/dataset/128002/taxon/03B187D1FFE1DB2ABAE8312F5404E5E3.taxon

`dwc:scientificNameAuthorship = Wang & Irfan & Chen & Zhang 2022`

We apparently parse the authors fine and produce a comma delimited version, but the policy is to use the authorship as it came when it is supplied explicitly:

https://www.checklistbank.org/dataset/128002/name/03B187D1FFE1DB2ABAE8312F5404E5E3.taxon

Sometimes you want more automation and consistent parsing/rendering. Sometimes more manual control to avoid errors and special cases. It is hard to find the right balance.

**Comment by mdoering** [comment]
https://api.checklistbank.org/dataset/128002/name/03B187D1FFE1DB2ABAE8312F5404E5E3.taxon

**Comment by myrmoteras** [comment]
ok - that means it is on our side. we'll check.

**Comment by gsautter** [comment]
The idea behind generally using ampersands to separate authors is to provide an unambiguous way of parsing the list ... commas can pose an ambiguity problem there, specifically if they are used between last names and initials or first names as well as between the names. The ampersands might not look as pretty to a pair of human eyeballs, but on the other hand make the authority far easier to consume for machines, including formatting for display. In that light, which way do we want this?

**Comment by mdoering** [comment]
dwc:scientificNameAuthorship is the authorship as it should be shown to humans. So I suppose just one ampersand max. Indeed ampersands are helpful to avoid ambiguous author teams. But maybe we should better exchange structured lists of authors in that case for machines in the first place?

**Comment by gsautter** [comment]
A structured list would definitely be preferable for machine processing, even if that would also require some processing before being suitable for display in a page intended for humans ... maybe we could simply add another field to the DwCA, so one field can hold a display friendly authority string, while the other provides a representation intended for machine consumption ...

**Comment by mdoering** [comment]
I like that. In most API models of parsed names you usually find combination and basionym authorships, each of which can have a list of authors, a year and potentially also a list of ex authors. And each author of course can also be broken down to further parts (given + family name, suffix). How about having 2 new terms for the combination and the basionym authorship?

```
combinationAuthorship = 
```

Some examples:
https://api.checklistbank.org/dataset/9837/taxon/8RTZC
https://api.checklistbank.org/dataset/9837/taxon/8R6M3
https://api.checklistbank.org/dataset/9837/taxon/8M2L
https://api.checklistbank.org/dataset/9837/taxon/8H9W
https://api.checklistbank.org/dataset/9837/taxon/8HBG
https://api.checklistbank.org/dataset/9837/taxon/8QHT3

**Comment by mdoering** [comment]
Additional fields will always be ignored, that is never an issue with DwC Archives.
But yes, the visualisation would only be different if the dwc:scientificNameAuthorship contains the version with 1 ampersand max.

**Comment by gsautter** [comment]
> But yes, the visualisation would only be different if the dwc:scientificNameAuthorship contains the version with 1 ampersand max.

In principle, this is of course quite doable ... however, which field do you suggest for the more data oriented, easy to parse version with the all ampersands?

**Comment by mdoering** [comment]
You can place it into some new plazi term, e.g. plazi:scientificNameAuthorshipList / http://plazi.org/terms/scientificNameAuthorshipList

Unless it is parsed into the 6 terms above though I don't think GBIF/COL can make use of that much. We would likely stick with the regular human readable authorship just as we do with all other datasets since decades.

**Comment by mdoering** [comment]
I just see that you already provide some plazi terms in the namespace http://plazi.org/terms/1.0:

```
"dwc:scientificName":"Ficus motuoensis Zhen Zhang & Hong Qing Li 2022",
"dwc:scientificNameAuthorship":"Zhen Zhang & Hong Qing Li 2022",
"http://plazi.org/terms/1.0/combinationYear":"2022",
"http://gbif.org/dwc/terms/1.0/canonicalName":"Ficus motuoensis",
"http://plazi.org/terms/1.0/combinationAuthors":"Zhen Zhang & Hong Qing Li",
"http://plazi.org/terms/1.0/verbatimScientificName":"Ficus motuoensis Zhen Zhang & Hong Qing Li",
```

It looks like plazi:combinationYear is the same as [dwc:namePublishedInYear](https://dwc.tdwg.org/terms/#dwc:namePublishedInYear), so maybe the dwc term could be used for that?

plazi:combinationAuthors is there and could maybe hold the ampersand concatenated version?

**Comment by gsautter** [comment]
> You can place it into some new plazi term, e.g. plazi:scientificNameAuthorshipList / http://plazi.org/terms/scientificNameAuthorshipList
> 
> Unless it is parsed into the 6 terms above though I don't think GBIF/COL can make use of that much. We would likely stick with the regular human readable authorship just as we do with all other datasets since decades.

OK, got it ... there might be other consumers of the DwCAs, though ...

Again, this only ever applies to original descriptions, as in all other treatments we use the verbatim authority from the publication (potentially reconciled against CoL or GBIF) ... only in original descriptions we get the authors from the document metadata.

**Comment by gsautter** [comment]
> The only problem I see is that the basionym author definitions seems to use that field also for protonyms, so authors of new names without the parentheses. I would have expected those authors & year in the combination fields which represents the author of the exact combination, not necessarily a recombination.

And that's how we do it, those notes are (mainly) from TDWG 2013 (remember Florence, us figuring out the DwCA in the hotel lobby?) ... my understanding of the whole authority matter has deepened a good bit since, I just didn't update those notes.

**Comment by gsautter** [comment]
> It looks like you already have 4 of the 6 terms in use! As long as you don't treat ex authors the ex-terms are not relevant.

Indeed we don't separately handle "ex" authors, as the focus is on how a taxon name will most likely be cited ... "hort. ex Linnaeus" will only come up as "Linnaeus", for instance, as for what I've been told, a minimalist usage of the name will only give the latter (e.g. in a discussion section) ... and for the full clarity, there is always the verbatim taxon name in `http://plazi.org/terms/1.0/verbatimScientificName`

**Comment by gsautter** [comment]
Updated https://treatment.plazi.org/GgServer/dwca/FF88FFA9FFE3DB2DB84E33305620E41B.zip now to have a pretty-printed authority in `dwc:scientificName` and `dwc:scientificNameAuthorship`, and the more parsing friendly all-ampersand versions in `plazi:basionymAuthor` and `plazi:combinationAuthor` ... hope this displays as intended now (GBIF seems to have fetched the update already as I write this, see https://www.gbif.org/dataset/4c24df32-5d1d-468e-a85a-e8c8ae263477).

**Comment by mdoering** [comment]
> Again, this only ever applies to original descriptions, as in all other treatments we use the verbatim authority from the publication (potentially reconciled against CoL or GBIF) ... only in original descriptions we get the authors from the document metadata.

The publication author is not always the author of the name. It is in most cases, but sometimes treatments have been written by someone else, e.g. book chapters. Do you have a check in place for that? I fear we might introduce a few wrong authors that way.

**Comment by gsautter** [comment]
> The publication author is not always the author of the name. It is in most cases, but sometimes treatments have been written by someone else, e.g. book chapters. Do you have a check in place for that? I fear we might introduce a few wrong authors that way.

We sure do ... if there is an authority explicitly given next to the new taxon name (or combination), our tagger uses that ... only if there is no such luck, it substitutes the document authors. The year comes from the document metadata in both cases.

**Comment by mdoering** [comment]
Fine here too: https://www.checklistbank.org/dataset/128002/names?facet=rank&facet=issue&facet=status&facet=nomStatus&facet=nameType&facet=field&facet=authorship&facet=authorshipYear&facet=extinct&facet=environment&facet=origin&limit=50&offset=0&rank=species&status=accepted****
