### ISSUE TITLE
Download service: asynchronous?

### ISSUE THREAD

**Issue by rvosa** [CatalogueOfLife/checklistbank#1103]
Just to harass the system I asked it to export the entire CoL22 as a Newick tree. I assume this means it does a recursive traversal from root to tips across the database. It's taking a long time. Would be excellent if this could be done asynchronously, with a notification system where you can leave the page and get an email when your export is ready.

**Comment by mdoering** [comment]
That is actually the normal procedure. How did you ask for the tree synchroneously?

**Comment by rvosa** [comment]
Maybe I'm misinterpreting the behavior. I unchecked "include synonyms", switched to "newick" and clicked "download". That browser tab has now been showing a wait icon for about a half hour.
<img width="961" alt="Screenshot 2022-09-16 at 11 21 14" src="https://user-images.githubusercontent.com/106490/190604185-1939cac6-752f-4a0d-b99a-ed4c6fb2280f.png">

**Comment by rvosa** [comment]
I am using the wrong term, I realize this is asynchronous. I should have said: "close the tab and walk away"-functionality.

**Comment by rvosa** [comment]
Oh, duh, I got it: it's listed under my profile. Please go ahead and enjoy the dopamine hit of closing this issue. Thanks.

**Comment by mdoering** [comment]
Yes, starting a download takes you to the download page where you can see "progress". It is run in the background and you should get an email once completed. I am surprised the Newick tree takes so long, but I never tried it for all of COL. I would have guessed a few minutes, but not more than 10...
