### ISSUE TITLE
UNITE species hypotheses should have DOIs rather than web pages

### ISSUE THREAD

**Issue by rvosa** [CatalogueOfLife/checklistbank#1104]
A SH in UNITE ([example](https://www.checklistbank.org/dataset/30477/taxon/SH1505930.08FU)) as subsumed in CLB refers back to UNITE using `dcterms:references` with the web page as its object. It would probably be better to use the DOI. I think that would mean:

1. computing the DOI from the SH ID, which just means prefixing the ID with `10.15156/BIO/$ID`
2. using that DOI as the object of `dcterms:references`
3. visualizing it with a link through a resolver on the CLB web page

**Comment by mdoering** [comment]
that is  data question for the publisher really, not the CLB backend. It was published with that link and should therefore also be shown with that link.

**Comment by mdoering** [comment]
It is a checklist synchronised from [GBIF](https://www.gbif.org/dataset/61a5f178-b5fb-4484-b6d8-9b129739e59d). Could you leave an issue with the GBIF helpdesk please?
