### ISSUE TITLE
Full URLs as taxon ids in URL

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/checklistbank#1108]
These still cause problems:
https://www.checklistbank.org/dataset/139831/taxon/https://www.inaturalist.org/taxa/832979

Looks like the path slash is the problem. This works:
https://www.checklistbank.org/dataset/139831/taxon/https:%2F%2Fwww.inaturalist.org%2Ftaxa%2F832979

**Comment by thomasstjerne** [comment]
How did you get to the unencoded url? 
Checklistbank should only produce encoded links, as you cannot have unencoded slashes in a path parameter

**Comment by mdoering** [comment]
Think its the taxon link from verbatim pages

**Comment by mdoering** [comment]
It is not impossible to have full URLs in the path as parameters:

https://web.archive.org/web/20070713080032/http:/www.ubio.org/service/logs/reports.php?func=userDetails&userID=128

But that probably needs less frameworks and more direct servlet access. Nothing for us now...

**Comment by thomasstjerne** [comment]
The httpd (server side) routing works fine, yes. Its is just problematic in the client side routing (React router lib)
