### ISSUE TITLE
Allow dataset editors to manage users

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/checklistbank#1119]
Users can be assigned to existing datasets in the admin section just fine.
But editors of datasets also need to be able to add or remove editors for their datasets.
Maybe we can add an editors section into the Options page, listing current ones and allow to add/remove more?

**Comment by thomasstjerne** [comment]
For projects, this is possible: https://www.checklistbank.org/catalogue/3/editors

Should it be possible for external datasets as well? (Not much to edit except from options such as data access etc)

**Comment by mdoering** [comment]
Yes please. It allows them to manage who can view private datasets or trigger/upload imports
