### ISSUE TITLE
Release duplicates view broken?

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/checklistbank#1125]
When I hit the duplicates menu item for a release I get undefined values for the project:
https://www.checklistbank.org/dataset/9842/duplicates/overview

I dont think we wanted to expose the TASK board in a public release page anyways. This is rather heavy load and slow.
Can we show the search directly with no results being loaded immediately instead?

I am also not able to switch from Author Different to Author Not Different here - I get Author Ignore instead (using Safari):
https://www.checklistbank.org/dataset/9842/duplicates?acceptedDifferent=true&category=binomial&limit=100&minSize=2&mode=STRICT&status=accepted&status=synonym

**Comment by thomasstjerne** [comment]
The duplicate search and TASK board are only visible for editors of the dataset (and admins).
The task board is the only way an editor of an external dataset that is not used as a source in COL (or another project) gets access to the TASK board. While preparing data for upload to CLB, I found that the TASK board was perhaps the most important tool when cleaning/preparing a dataset for CLB.

I have now added a direct menu item to the duplicate search for external datasets and releases.
