### ISSUE TITLE
Incorrect citation Plazi checklist with multiple authors

### ISSUE THREAD

**Issue by chantalhuijbers** [CatalogueOfLife/checklistbank#1128]
Metadata in CLB for this Plazi article does not show the full author list in Citation and Source.
https://www.checklistbank.org/dataset/3723/about
When you go to the [plazi link](https://zse.pensoft.net/article/32803/), you can see there are 3 authors, but only the first is shown in our metadata in CLB.

I have tried to find other examples, but have only come across Plazi checklists with 1 author that obviously don't have this issue. So not sure if it is 1 case, or something in the pipeline that doesn't receive all authors.

**Comment by mdoering** [comment]
Plazi also just has one: http://tb.plazi.org/GgServer/summary/643B8504FF9AFFF3FF97FF9FFFF1FF82
One for @gsautter and @myrmoteras

**Comment by chantalhuijbers** [comment]
But when you follow the DOI it shows three authors: https://zse.pensoft.net/article/32803/

So is this then an issue where Plazi only has 1 author, and we get it from there?

**Comment by mdoering** [comment]
yes, the metadata is part of the data and delivered by plazi

**Comment by gsautter** [comment]
I re-imported the article in question now, so the metadata is updated to contain all three authors. The DwC-A should be re-packed in a few minutes, with a respective notification going to the GBIF API.
