### ISSUE TITLE
Decisions not showing in regex view of workbench

### ISSUE THREAD

**Issue by gdower** [CatalogueOfLife/checklistbank#1132]
In the regex tab of workbench, decisions do not display:

<img width="1920" alt="image" src="https://user-images.githubusercontent.com/8573609/201779512-997f0f71-5f30-4632-be6c-59a326550d89.png">

All of the names shown in the above screenshot [have provisionally accepted decisions](https://www.checklistbank.org/catalogue/3/decision?limit=100&offset=0&rank=genus&subjectDatasetKey=1101).

**Comment by gdower** [comment]
Here's a direct link to the search view in workbench which shows the decisions:

https://www.checklistbank.org/catalogue/3/dataset/1101/workbench?decisionMode=_NOT_NULL&facet=rank&facet=issue&facet=status&facet=nomStatus&facet=nameType&facet=field&facet=authorship&facet=authorshipYear&facet=extinct&facet=environment&facet=origin&limit=50&offset=0&rank=genus&reverse=true&sortBy=name

And the regex search results which is not displaying the decisions (although I can't direct link to the regex view):

https://www.checklistbank.org/catalogue/3/dataset/1101/workbench?USAGE_ID=xBHH&USAGE_ID=x35BQ&USAGE_ID=x35BS&USAGE_ID=xGHK&USAGE_ID=x3852&USAGE_ID=x3854&USAGE_ID=x3856&USAGE_ID=xBHK&USAGE_ID=xQCK&USAGE_ID=x6TF&USAGE_ID=xGHM&USAGE_ID=x35BV&USAGE_ID=xFDY&USAGE_ID=xVB6&USAGE_ID=xDBD&USAGE_ID=xDY3&USAGE_ID=xHH&USAGE_ID=xLVZ&USAGE_ID=xPBP&USAGE_ID=x3B2W&USAGE_ID=x6TH&USAGE_ID=x39VB&USAGE_ID=xBHM&USAGE_ID=x35BX&USAGE_ID=x4CC&USAGE_ID=xNMK&USAGE_ID=xHK&USAGE_ID=xVB8&USAGE_ID=xWC6&USAGE_ID=x66&USAGE_ID=xTK&USAGE_ID=xWC8&USAGE_ID=x4Z8&USAGE_ID=x4ZB&USAGE_ID=xTZW&USAGE_ID=x9GY&USAGE_ID=x6TK&USAGE_ID=xVBB&USAGE_ID=xZHC&USAGE_ID=x35BZ&USAGE_ID=xZHF&USAGE_ID=xZHH&USAGE_ID=xGHP&USAGE_ID=xTM&USAGE_ID=xN86&USAGE_ID=x68&USAGE_ID=xNMM&USAGE_ID=xX6B&USAGE_ID=xVBD&USAGE_ID=x6TM&facet=rank&facet=issue&facet=status&facet=nomStatus&facet=nameType&facet=field&facet=authorship&facet=authorshipYear&facet=extinct&facet=environment&facet=origin&limit=50&offset=0&unsafe=true

**Comment by thomasstjerne** [comment]
@mdoering is it possible to include decisions in this response https://api.checklistbank.org/dataset/1101/nameusage/pattern?regex=%5C%5B%5BA-Za-z%5D%2B%5C%5D&limit=50&offset=0

And allow flitering on has/has not decisions ?

**Comment by mdoering** [comment]
That is far from simple, it was never intended to return decisions. Filtering might be possible, but returning decisions will be tough. This goes straight to the database while the other searches work with Elastic.

**Comment by mdoering** [comment]
well, I think I can manage. But don't ask to add the classification :)

**Comment by mdoering** [comment]
I will add 2 query params to the regex search:

 - `projectKey`
 - `decisionMode` value or `_NOT_NULL` or `_NULL`

**Comment by mdoering** [comment]
Done. Will be on prod shortly

**Comment by mdoering** [comment]
deployed to prod: https://api.checklistbank.org/dataset/1101/nameusage/pattern?regex=Tipul&projectKey=3
