### ISSUE TITLE
UNKNOWN_REFERENCE_TYPE in references

### ISSUE THREAD

**Issue by myrmoteras** [CatalogueOfLife/checklistbank#1139]
![image](https://user-images.githubusercontent.com/4609956/203731177-563a11e1-4f3c-4c35-a414-117fac16664e.png) in this taxon, there references are of an unknown type.

https://www.checklistbank.org/dataset/27944/taxon/03A0BE3B6436FF83FF4FFCA0FDCB510D.taxon#col-refererence-r3Y

This need not to be so, because the references are in the treatment (online resource: 
http://treatment.plazi.org/id/03A0BE3B6436FF83FF4FFCA0FDCB510D)  
![image](https://user-images.githubusercontent.com/4609956/203731537-d052f350-f3fd-4576-a540-b3ed7c17c459.png)

The question might be, how to package them into the DWCA we export to GBIF?!

**Comment by mdoering** [comment]
You can always go to the verbatim record to see what is inside the dwc data that comes to ChecklistBank (follow the reference link and check the verbatim tab):
https://www.checklistbank.org/dataset/27944/verbatim/1353

The taxon data we receive from Plazi has this:

`dwc:namePublishedIn= Won (1968)UNKNOWN_REFERENCE_TYPE`

An issue for @gsautter?

**Comment by gsautter** [comment]
`UNKNOWN_REFERENCE_TYPE` is what the reference data infrastructure returns when confronted with a record that isn't of any of the defined types (book, book chapter, journal volume, journal article, conference proceedings, proceedings paper, website) ... will look at the source data.

**Comment by mdoering** [comment]
but it should not be included in the final citation string I suppose.

**Comment by gsautter** [comment]
It's an XSLT called by Java code ... might be I need to add a check there, and throw an Exception ... trying to figure out where exactly the data comes from, though ... doesn't seem to be in the DwCA this way ...

**Comment by gsautter** [comment]
Added a catch for "UNKNOWN_REFERENCE_TYPE" now and repacked the DwCA ... the GBIF API has been notified, so this should be fixed relatively soon.

**Comment by gsautter** [comment]
> similar cases existing maybe?

Quite likely ... but we have that mass update coming up anyway, so these things should be fixed by the respective re-exports as well.
