### ISSUE TITLE
Display all homotypic relationships correctly

### ISSUE THREAD

**Issue by dhobern** [CatalogueOfLife/checklistbank#1142]
See this example: 

https://www.checklistbank.org/dataset/1162/taxon/1617

The basionymID values group the names as follows:

ID,basionymID,scientificName,authorship,rank,uninomial,genus,specificEpithet,infraspecificEpithet,code,status,referenceID,link,remarks
4124,1531,Senegalia velutina,(DC.) Seigler & Ebinger,species,,Senegalia,velutina,,,established,4124,http://worldwidewattle.com/speciesgallery/species-intro.php?id=-763,
1531,1531,Acacia velutina,DC.,species,,Acacia,velutina,,,,2619,,
6792,1531,Senegalia velutina,(DC.) Bocage & L.P.Queiroz,species,,Senegalia,velutina,,,,544,,
8165,1531,Acacia velutina var. velutina,DC.,variety,,Acacia,velutina,velutina,,,544,,
8163,1531,Acacia velutina f. velutina,DC.,form,,Acacia,velutina,velutina,,,544,,4486,1531,Manganaroa velutina,(DC.) Speg.,species,,Manganaroa,velutina,,,,2619,,
4487,4487,Acacia velutina var. monadena,Hassl.,variety,,Acacia,velutina,monadena,,,2619,,
4488,4488,Manganaroa velutina var. glabrescens,Speg.,variety,,Manganaroa,velutina,glabrescens,,,2619,,
4489,4488,Acacia velutina var. glabrescens,(Speg.) Burkart,variety,,Acacia,velutina,glabrescens,,,2619,,
5261,5261,Acacia velutina f. ferox,Hassl.,form,,Acacia,velutina,ferox,,,2619,,
5260,5260,Acacia velutina f. subinermis,Hassl.,form,,Acacia,velutina,subinermis,,,2619,,

_Acacia velutina_ var. _glabrescens_ is homotypic with _Manganaroa velutina_ var. _glabrescens_. Bruce Maslin has suggested that we should show this more clearly, something like the following:

≡ Acacia velutina DC. [2]
≡ Acacia velutina f. velutina DC. [1]
≡ Acacia velutina var. velutina DC. [1]
≡ Manganaroa velutina (DC.) Speg. [2]
≡ Senegalia velutina (DC.) Bocage & L.P.Queiroz [1]
= Acacia velutina f. ferox Hassl. [2]
= Acacia velutina f. subinermis Hassl. [2]
= Acacia velutina var. monadena Hassl. [2]
= Manganaroa velutina var. glabrescens Speg. [2]
    ≡ Acacia velutina var. glabrescens (Speg.) Burkart [2]

I indented the final row here, but Github hides the whitespace. I hope the idea is clear.

**Comment by thomasstjerne** [comment]
@mdoering in order for the UI to do this, I´d suggest adding sth like `basionymNameID` to the name objects of in `Taxon.info.synonyms.heterotypic` & `Taxon.info.synonyms.homotypic`. 
https://api.checklistbank.org/dataset/1162/taxon/1617/info

**Comment by mdoering** [comment]
Yes, that would be ideal indeed. I always liked the way the EDIT CDM software does that based on conventions in botanic literature:

![CDM_Agoseris_apargioides_synonymy](https://user-images.githubusercontent.com/327505/208675873-d99e0a32-40c6-4e0c-b310-e320f58099a4.png)

**Comment by mdoering** [comment]
> @mdoering in order for the UI to do this, I´d suggest adding sth like `basionymNameID` to the name objects of in `Taxon.info.synonyms.heterotypic` & `Taxon.info.synonyms.homotypic`.
> https://api.checklistbank.org/dataset/1162/taxon/1617/info

It is not just basionyms. We should group all homotypic names incl replacement names.
We once had sublists for the heterotypic names in the synonymy to group them, but for some reasons we have removed that again. I think it was confusing people when we did not know about the homotypic relations, but showed them as if they were heterotypic. When in fact this was just unknown. I don't think we can distinguish between unknown and heterotypic in the current setup, maybe we should.

**Comment by mdoering** [comment]
we changed it from the sublists to a simple synonymy response  here: https://github.com/CatalogueOfLife/backend/commit/1504e9ccee256f82370468cfe82cc1d13d231a6e

**Comment by mdoering** [comment]
@thomasstjerne would it be fine to go back to the sublist approach and just show all names in a sublist as homotypic with the respective symbol? I think the problem we had was mostly visualising whats going on.

**Comment by mdoering** [comment]
... that rasises also the question how to sort the synonyms within a homotypic group. By year if known, otherwise alphabetically?

**Comment by mdoering** [comment]
I have added the homotypic grouping back to the heterotypic synonyms. It is available in a new property `heterotypicGroups` for now to not break the existing UI:
https://api.checklistbank.org/dataset/1162/taxon/1617/synonyms

_glabrescens_ now groups with 2 names

**Comment by dhobern** [comment]
I would think the sequence would indeed be:

- Accepted name
- Homotypic synonyms of accepted name sorted if possible by year and then alphabetically
- Heterotypic synonyms sorted if possible by year and then alphabetically, each followed by its homotypic synonyms (sorted by year and then alphabetically)
