### ISSUE TITLE
Stopping background job fails

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/checklistbank#1146]
<img width="1780" alt="image" src="https://user-images.githubusercontent.com/327505/208148978-9e58611c-b8af-4ce2-9527-cb2f19d2bc35.png">

**Comment by thomasstjerne** [comment]
Looks like the UI expects the job to have an `UUID` property that is now missing.
Looks like this now `key` instead.

**Comment by mdoering** [comment]
Yes its key, but I believe this has always been like that. Thanks for changing!
