### ISSUE TITLE
white page after creating project root taxon "Biota"

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/checklistbank#1150]
Created a new project and staeted assembly by creating the first root taxon unranked Biota. Results in whitepage

**Comment by mdoering** [comment]
https://www.dev.checklistbank.org/catalogue/26/assembly

**Comment by mdoering** [comment]
<img width="1516" alt="image" src="https://user-images.githubusercontent.com/327505/208869386-7bc565e3-3da0-49a6-8cec-85feb1d723d5.png">

Same if I create another root. Taxa are created

**Comment by thomasstjerne** [comment]
Should now work on the extended branch (i.e. DEV env)
