### ISSUE TITLE
maintainance notice not shown on DEV

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/checklistbank#1152]
<img width="1551" alt="image" src="https://user-images.githubusercontent.com/327505/208902433-8da36e19-a924-4d48-8c32-d578fcf47d56.png">

**Comment by thomasstjerne** [comment]
Still don´t see it? - must be some caching issue
![Screenshot at Dec 22 10-31-03](https://user-images.githubusercontent.com/1666484/209103710-ca1ed74c-34e8-4e98-905f-28347f13cf70.png)

**Comment by mdoering** [comment]
now I do

**Comment by mdoering** [comment]
But now the admin settings do not show the maintenance mode
<img width="1042" alt="image" src="https://user-images.githubusercontent.com/327505/209129309-7d32b14d-6ac8-41d0-8dfb-72d234b5cbce.png">

**Comment by mdoering** [comment]
if I turn it on and off again it works.
