### ISSUE TITLE
Simpler project selection

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/checklistbank#1161]
Selecting a project needs to be done in a distinct selector. The project is also shown mostly redundantly next to a dataset details menu item:
<img width="1617" alt="image" src="https://user-images.githubusercontent.com/327505/214029857-ca971b94-4efe-49a6-b8d4-0bfc2f07a747.png">

Try to simplify the process and cleanup redundancy. What if:

 - dataset (search) menu is placed above the project menu. Selecting any dataset link from there would activate the dataset or project details menu item
 - the dataset details menu item would become a project item in case it is a project AND the user has permission for it. Otherwise it just stays as a regular public dataset menu item

This would a) remove the need for a project selector and more importantly to me b) remove the redundant dataset & project menu items

**Comment by mdoering** [comment]
See also #775

**Comment by dhobern** [comment]
This would be a big help and much more intuitive.

**Comment by mdoering** [comment]
@thomasstjerne can this be done without too much pain?

**Comment by mdoering** [comment]
I wondered if the link to "your project" could take you to the project instead of trying to select sth else. Then you always have a quick access...
