### ISSUE TITLE
White page when showing informal taxon details

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/checklistbank#1165]
World Catalogue of the Tortricidae 4.0:
https://www.dev.checklistbank.org/dataset/64922/taxon/5435

**Comment by thomasstjerne** [comment]
I can´t reproduce, but I hit a backend error when trying: https://api.dev.checklistbank.org/dataset/64922/nameusage/5435

**Comment by mdoering** [comment]
oha. `Error occurred when processing a response created from an already mapped exception.`
I'll follow that up

**Comment by mdoering** [comment]
Fixed in https://github.com/CatalogueOfLife/backend/commit/6de2cd5cd54867e183a84829d38ce7834efc6710, waiting for jenkins to deploy
