### ISSUE TITLE
Search does not find word followed by dot

### ISSUE THREAD

**Issue by peterdesmet** [CatalogueOfLife/checklistbank#1178]
https://www.checklistbank.org/dataset/204830/about has the following title:

> Waarnemingen.be / observations.be - List of species observed in Belgium

The dataset search does not yield results for:

- `waarnemingen`: https://www.checklistbank.org/dataset?limit=50&offset=0&q=Waarnemingen
- `waarnemingen.`: https://www.checklistbank.org/dataset?limit=50&offset=0&q=Waarnemingen.

One has to search `waarnemingen.be`: https://www.checklistbank.org/dataset?limit=50&offset=0&q=Waarnemingen.be

Is it possible to consider dots as a word separator when searching?

**Comment by mdoering** [comment]
We use regular [postgres full text search](https://www.postgresql.org/docs/14/textsearch-parsers.html). This is how the default parser splits up tokens:

```
SELECT alias, description, token FROM ts_debug('Waarnemingen.be / observations.be - List of species öbsérved in Belgium ');
   alias   |    description    |      token      
-----------+-------------------+-----------------
 host      | Host              | Waarnemingen.be
 blank     | Space symbols     |  
 blank     | Space symbols     | / 
 host      | Host              | observations.be
 blank     | Space symbols     |  
 blank     | Space symbols     | - 
 asciiword | Word, all ASCII   | List
 blank     | Space symbols     |  
 asciiword | Word, all ASCII   | of
 blank     | Space symbols     |  
 asciiword | Word, all ASCII   | species
 blank     | Space symbols     |  
 word      | Word, all letters | öbsérved
 blank     | Space symbols     |  
 asciiword | Word, all ASCII   | in
 blank     | Space symbols     |  
 asciiword | Word, all ASCII   | Belgium
 blank     | Space symbols     |  

```

**Comment by mdoering** [comment]
I can see the value of searching for just Waarnemingen. But it might also be benefitial to keep domains together. But maybe not...

**Comment by mdoering** [comment]
Honestly I am not sure how to do that. Seems I need to customise the pg parser, but I dont know how to do that. 
I have tuned the dataset search to much higher rank hits on the alias and title and rate other things in descriptions much lower. WoRMS for example used to yield all kind of COL releases before you could actually find WoRMS.
