### ISSUE TITLE
Indicate whether dataset is used for COL or not

### ISSUE THREAD

**Issue by peterdesmet** [CatalogueOfLife/checklistbank#1179]
Other than dataset confidence I currently do not see on a dataset page whether a dataset contributes to COL or not: https://www.checklistbank.org/dataset/2144/about

I think it would be useful to indicate that info (e.g. as a badge).

**Comment by mdoering** [comment]
Its at the very bottom of the page, but I agree this could be made more prominent!

**Comment by mdoering** [comment]
<img width="1360" alt="image" src="https://user-images.githubusercontent.com/327505/223507812-e1cc1a5d-ca43-4308-abe8-9f39d967a06d.png">
