### ISSUE TITLE
Add link to owned dataset from profile

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/checklistbank#1184]
As a user I would like to easily access the datasets I have created and the ones I have editor or reviewer access to.
A link like this does it: https://www.dev.checklistbank.org/dataset?editor=728&origin=external&origin=project

Suggest to add this to the profile dropdown at the top or/and into the dataset search

**Comment by thomasstjerne** [comment]
The editor and reviewer ones is there already - I think only the ones createdBy should be added

**Comment by mdoering** [comment]
I can only find a link from the admin menu, but not when logged in for me:
<img width="1432" alt="image" src="https://user-images.githubusercontent.com/327505/225561582-10d13082-bc1c-4cc3-8065-8a4ac7ad898e.png">

 link to datasets (not releases) created by me or where I have editing rights should exist somewhere.

Related note. I notice we have a nice current project link in the account info. If you hit it it wants you to select a new project. With the new menu structure and dataset search to change projects I would much more prefer if that link simply takes me to my project. Options, metadata, assembly maybe? Then there is always a quick way to get there.

**Comment by thomasstjerne** [comment]
You should select profile to see your details, downloads , editor and reviewer datasets

**Comment by mdoering** [comment]
Oh, nice ;)
