### ISSUE TITLE
Allow to jump from assembly tree to source taxon

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/checklistbank#1196]
The assembly context menu already has "show sector in source", but that takes you to the sector subject.
Instead it would be more useful to have a "show in source" entry that goes to the exact taxon in the source. The API offers this via the source route `https://api.dev.checklistbank.org/dataset/9944/taxon/ab16971f-02b8-4cd4-877c-f3adeb7e18e4/source`

which returns the source id:

```
{
"id":"ab16971f-02b8-4cd4-877c-f3adeb7e18e4",
"datasetKey":9944,
"sourceId":"989790",
"sourceDatasetKey":2008,
}

```

**Comment by thomasstjerne** [comment]
@mdoering this is now implemented but work only when the `sourceDatasetKey` also changes along with a `sourceTaxonId`.
I.e. if you try to show another taxon within the same sector, the UI won´t update.  I tried initially to reload the tree when a new taxon is selected, but this resulted in https://github.com/CatalogueOfLife/checklistbank/issues/1394

I think this is still better than just pointing to the sector subject.
