### ISSUE TITLE
CLB: where is "decision" option in a new interface?

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/checklistbank#1197]
[Frontend version: 5eb299a March 20, 2023 6:49 AM](https://github.com/CatalogueOfLife/checklistbank/tree/5eb299a)[Backend version: 53da770 March 15, 2023 12:00 AM](https://github.com/CatalogueOfLife/backend/tree/53da770)

Former TASKS reports, now "Duplicate Overview" reports: I cannot find an option for making editorial decision (no tick boxes with names):

![image](https://user-images.githubusercontent.com/28574252/226935626-9bfe5c7e-97da-4ffd-83c7-b388812c4bd8.png)

https://www.checklistbank.org/dataset/2073/duplicates?acceptedDifferent=true&authorshipDifferent=true&category=binomial&limit=500&minSize=2&mode=STRICT&offset=0&status=accepted&status=synonym

**Comment by thomasstjerne** [comment]
You still need to select "species fungorum" under "source" in the project which takes you to https://www.checklistbank.org/catalogue/3/dataset/2073/duplicates?catalogueKey=3&limit=50&offset=0

**Comment by yroskov** [comment]
Thanks! Clear now
