### ISSUE TITLE
Wrong system date at the project sycs tab 3 years mismatch

### ISSUE THREAD

**Issue by camiplata** [CatalogueOfLife/checklistbank#1211]
The project syncs have an internal date with a 3 years mismatch, the date is correctly set on the other tabs of the project

Screenshoot taken on 2023-04-20, the same date of the sycns shown 
<img width="1216" alt="Captura de pantalla 2023-04-20 a la(s) 5 17 43 p m" src="https://user-images.githubusercontent.com/5700527/233498995-6353f024-0524-4337-967c-b209e9c9ae35.png">

**Comment by mdoering** [comment]
I only see dates from 2023 on that screenshot. Maybe the year split on 2 lines is misleading?

**Comment by camiplata** [comment]
You are right I completely oversee the second line and read 20 instead of 2023
