### ISSUE TITLE
CLB on DEV: how to find reports on duplicates in the menu, if GSD is not assigned in the project?

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/checklistbank#1234]
Working with a new version of Systema Dipterorum on DEV, I met a problem to see reports on duplicates. There is no items **Duplicate Overview** and **Duplicate Search** in the menu. Why? What I am doing wrong?

I need to share DEV reports on duplicates with authors of GSDs during our **period of pre-assembly tests**, when GSD is not a part of the project yet.  

https://www.dev.checklistbank.org/dataset/59400/classification:
![image](https://github.com/CatalogueOfLife/checklistbank/assets/28574252/38203e1d-6fb1-41a7-9080-ad2781319ff4)

Just in case, both "Duplicate Overview" and "Duplicate Search" are present in the menu on PROD (GSD :
https://www.checklistbank.org/dataset/1101/duplicates?limit=50&offset=0

![image](https://github.com/CatalogueOfLife/checklistbank/assets/28574252/0bf043a0-0c1e-4616-a9df-fae9c55d4371)

**Comment by mdoering** [comment]
if the item doesnt show up just paste the URL: https://www.dev.checklistbank.org/dataset/59400/duplicates?limit=50&offset=0

**Comment by thomasstjerne** [comment]
These menu items are only visible for editors or admins of a dataset : Options, Tasks, Duplicates.
This means that if you haven´t got the same access rights on DEV and RROD you may see a different menu. 

As I remember the reasoning was that we would shield publishers from having duplicates exposed publicly, and that the duplicates tool is targeted technical users doing data assessments.

Should I expose those menu items publicly?   
As it is now, you can still send a link and access the tool by hitting the url directly

**Comment by mdoering** [comment]
Makes sense to hide them to the public I think. If you can access the link that would be more than enough for sharing with the GSDs. We could even consider to require a reviewer/editor/admin role. But that adds a bit of burden as GSDs will have to have an account in CLB - which might be good to increase usage, but likely also stops some from using it

**Comment by yroskov** [comment]
>Should I expose those menu items publicly? As it is now, you can still send a link and access the tool by hitting the url directly

@thomasstjerne, the problem is: Geoff and I would like to point GSD authors to the CLB on DEV with all reports accessible via the menu, and let them to play with the software according their needs. If they need to register account in CLB, it's a barrier for them.
