### ISSUE TITLE
Incorrect validation of duplicates based on higher taxonomy

### ISSUE THREAD

**Issue by camiplata** [CatalogueOfLife/checklistbank#1237]
I created a dataset (#54506 in dev) on checklisbank, several genus have been reinterpreted creating duplicate alerts, the difference between the duplicates is that the original genus is matched to the family and the interpreted one is matched to the subfamily. The original genus has the subfamily documented in both the genus record and all the species records

<img width="939" alt="Captura de pantalla 2023-05-26 a la(s) 11 34 12 a m" src="https://github.com/CatalogueOfLife/checklistbank/assets/5700527/2a2c84e3-0460-4f5a-95c2-ca0281133927">

**Comment by mdoering** [comment]
Look at the origin of the records please.
There are 26 denormalised classification origins in this dataset, 21 being a genus:
<img width="1821" alt="image" src="https://github.com/CatalogueOfLife/checklistbank/assets/327505/e2f1f47a-b082-4552-b9b4-faec813ec3e4">

You can see that their classification differs.
Looking at a verbatim record from one of the source records, e.g. Shiponaptera:
https://www.dev.checklistbank.org/dataset/54506/verbatim/2451

you can see that the `parentID` points to the family record.
But that the record contains also the flat classification with `subfamily` and a badly named `phyllum` column.
These are exactly the kind of problems that we would also see if we had [acceptedNameUsage](https://github.com/CatalogueOfLife/coldp/issues/71).

**Comment by mdoering** [comment]
So to me this is perfectly correct. The interpretation cannot swallow and ignore the difference in classification so it creates 2 records. The duplicate tool spots them.
