### ISSUE TITLE
NameMatch tool shows wrong results

### ISSUE THREAD

**Issue by DianRHR** [CatalogueOfLife/checklistbank#1247]
I tried to match a list of ~5000 scientific names, uploaded a csv file with fields: scientificName, rank, code and proceed with the match. 
The result was: 0/5428 matches. 

From the same list, I copied and paste 20 names using the "simple data entry" option. And all of them had a match. 

I'm attaching the file that I tried to match. 

[enAnMx.csv](https://github.com/CatalogueOfLife/checklistbank/files/11697260/enAnMx.csv)

**Comment by mdoering** [comment]
Apparently the match service does not parsers for some enumerations like the nomenclatural code.
ICZN is expected to be ZOOLOGICAL:

>| BadRequestException: Invalid NomCode value: ICZN
 GET /nidx/match?q=Zoogoneticus%20tequila&code=ICZN&rank=species

@thomasstjerne the UI should indicate a failed match with an error response.
and @mdoering we should probably use the code parser...

**Comment by mdoering** [comment]
This works: 
[enAnMx.csv](https://github.com/CatalogueOfLife/checklistbank/files/11702326/enAnMx.csv)

**Comment by mdoering** [comment]
@thomasstjerne maybe we should also show the provided author, rank & code that was used for matching?

**Comment by DianRHR** [comment]
thanks @mdoering  I didn't check that difference with DwC . 
Now I know, won't forget and yes, it's working. A code parser could be helpful though but definitely an error response.
