### ISSUE TITLE
Deformed taxonomic names in some checklists

### ISSUE THREAD

**Issue by kbseah** [CatalogueOfLife/checklistbank#1260]
Not sure how else to describe this, but some datasets have "deformed" taxon names, which appear to be a problem with how the authorship field is parsed. 

Example: the name `Loxophyllum helus (Stokes 1884)(Stokes,1884)Penard 1922 (Stokes, 1884) (Stokes, 1884) Penard 1922` in the screenshot below, from this dataset: https://www.checklistbank.org/dataset/46512/classification 
![Screenshot 2023-08-01 164707](https://github.com/CatalogueOfLife/checklistbank/assets/9416913/a97bbb12-6567-417e-bdf4-9bb2e328cdda)

Another example with a slightly different issue, where the species name and the authorship are both not parsed properly:
https://www.checklistbank.org/dataset/23066/taxon/03AE281F9F718861359AB557FC96BFCC.taxon

Both these examples were imports from Plazi, but the original entries on the Plazi look ok.

The Ciliophora (ciliated protists) somehow are simultaneously classified under kingdoms Animalia, Chromista, and even Plantae (!) in the same dataset, but this appears to be a problem with the original records on Plazi.

**Comment by mdoering** [comment]
These are all Plazi issues as you can see in the verbatim data tab of the records

**Comment by kbseah** [comment]
thanks @mdoering for forwarding this to Plazi!
