### ISSUE TITLE
 Xenacoelomorpha being displayed as x Enacoelomorpha in Browse section of Dataset

### ISSUE THREAD

**Issue by Sherrin-ALA** [CatalogueOfLife/checklistbank#1262]
The phylum Xenacoelomorpha is being displayed as x Enacoelomorpha in Browse section of Dataset - example here
https://www.checklistbank.org/dataset/60706/taxon/https%3A%2F%2Fbiodiversity.org.au%2Fafd%2Ftaxa%2F4c2714a5-f1ee-4499-a37c-849bb4d7280e

**Comment by mdoering** [comment]
I bet this is because the name is in all upper caps

**Comment by mdoering** [comment]
fixed in name parser
