### ISSUE TITLE
Wrong "Not Sectors" label for taxa on a CLB project

### ISSUE THREAD

**Issue by camiplata** [CatalogueOfLife/checklistbank#1263]
Taxa from merges/xreleases are probably not correctly treated/shown on CLB

<img src="https://github.com/CatalogueOfLife/checklistbank/assets/5700527/b11f66fd-44f0-4bbc-81dc-1fafe0e66118" width=50% height=50%>

**Comment by mdoering** [comment]
can you leave links to the problematic data so it is easier to investigate? Screenshots are nice to capture the state, but you can not dive into details

**Comment by mdoering** [comment]
@camiplata where is the project & xrelease located?

**Comment by camiplata** [comment]
Annelidae_bold_01:  https://www.dev.checklistbank.org/catalogue/10021/metadata

**Comment by mdoering** [comment]
The regular way of doing an extended release is just releasing, not doing syncs manually.
Still doing manual syncs should not result into sth odd. It also seems the search index is not up to date, I have rebuilt it.

When I create a simple project with just BOLD and sync it it seems good:
https://www.dev.checklistbank.org/catalogue/10027/assembly?assemblyTaxonKey=e8b8de8f-e3ef-443a-b6e3-6788461b022c

**Comment by mdoering** [comment]
`camiplata` is added
