### ISSUE TITLE
COL23 "Last Import Job of this dataset failed" on dev

### ISSUE THREAD

**Issue by camiplata** [CatalogueOfLife/checklistbank#1264]
Last Import Job of this dataset failed.
NotUniqueException; PersistenceException: ### Error updating database. Cause: org.postgresql.util.PSQLException: ERROR: conflicting key value violates exclusion constraint "dataset_doi_unique" Detail: Key (doi)=(10.48580/dfsy) conflicts with existing key (doi)=(10.48580/dfsy). ### The error may exist in life/catalogue/db/mapper/DatasetMapper.xml ### The error may involve life.catalogue.db.mapper.DatasetMapper.update-Inline ### The error occurred while setting parameters ### SQL: UPDATE dataset SET ( type, doi, identifier, title, alias, description, issued, version, issn, contact, creator, editor, publisher, contributor, keyword, geographic_scope, taxonomic_scope, temporal_scope, confidence, completeness, license, url, logo, notes, created_by, modified_by , deleted, gbif_key, gbif_publisher_key, private , modified) = ( ?::datasettype, ?, ?::hstore, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?::LICENSE, ?, ?, ?, ?, ? , ?, ?, ?, ? , now()) WHERE key = ? ### Cause: org.postgresql.util.PSQLException: ERROR: conflicting key value violates exclusion constraint "dataset_doi_unique" Detail: Key (doi)=(10.48580/dfsy) conflicts with existing key (doi)=(10.48580/dfsy).; PSQLException: ERROR: conflicting key value violates exclusion constraint "dataset_doi_unique" Detail: Key (doi)=(10.48580/dfsy) conflicts with existing key (doi)=(10.48580/dfsy).

see: https://www.dev.checklistbank.org/dataset/55380/about

**Comment by mdoering** [comment]
It is running now. An external dataset with data from https://download.catalogueoflife.org/col/latest_dwca.zip that is the latest COL release. Do we need that?

A dataset DOI is forced to be unique in CLB, thats why it failed earlier.

**Comment by mdoering** [comment]
The other one is this one, created by @DianRHR: https://www.dev.checklistbank.org/catalogue/10024/metadata
But that does not seem to be the entire COL: https://www.dev.checklistbank.org/dataset/10023/imports

It is dev, so it doesnt matter much. But it might be better to give proper metadata or make tests private to not confuse others using dev.
