### ISSUE TITLE
Spoiled metadata in fixed releases

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/checklistbank#1265]
Some items(*) in GSD metadata in fixed CoL editions are changing to the latest view of metadata in CoL-Working Draft (id 3). That is wrong

(*) _at least **incorrect Alias**_

**Comment by mdoering** [comment]
@thomasstjerne logos are archived for each release. Does the UI access them via the release datasetKey like this?

`/dataset/{releaseKey}/logo/source/{sourceDatasetKey}`
