### ISSUE TITLE
Editors do not automatically get editor role for releases of their projects

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/checklistbank#1268]
Camila is the creator of a project, but does not see the private toggle switch to publish the [release](https://www.dev.checklistbank.org/dataset/10029/about).

**Comment by camiplata** [comment]
I can't see the toggle yet

<img width="1134" alt="Captura de pantalla 2023-09-05 a la(s) 3 24 06 p m" src="https://github.com/CatalogueOfLife/checklistbank/assets/5700527/498d45d4-7c17-4788-bb97-eac56497beed">

**Comment by mdoering** [comment]
what is the link please?

**Comment by mdoering** [comment]
The DEV UI wasnt updated, I just did.

**Comment by camiplata** [comment]
I cleaned the cache but it Is not visible yet. (I don't have permits to reopen an issue)

link to my test release: https://www.dev.checklistbank.org/dataset/264658/about

**Comment by mdoering** [comment]
@thomasstjerne could you please look into this?

**Comment by camiplata** [comment]
I would like to add that the problem is not only the toggle, is about all the features that needs editor rights. I can't see the issues, check duplicates, edit metadata among others. I'm the editor of the project but have no rights over the releases.

**Comment by DianRHR** [comment]
I have the same problem. 
I have a project , made a release but can't go further. 
The id of my release is 265170. https://www.dev.checklistbank.org/dataset/265170/about  
And Camila helped me making the xrelease, but still can't get the issues or duplicates either in the release or the xrelease.

**Comment by thomasstjerne** [comment]
@mdoering I think there is a backend adjustment needed here.
I would expect that any editor of a project would automatically have the editor role for any release of that project.
As far as I can see, @DianRHR does not have editor roles for any releases, not even those that she triggered herself:
https://www.dev.checklistbank.org/dataset?editor=643&limit=50&offset=0&origin=release&origin=xrelease&reverse=false

**Comment by mdoering** [comment]
That is not expected, for all releases one has to check with the project, not the release.
Otherwise we would have to change all releases each time the project rights change

**Comment by mdoering** [comment]
see https://github.com/CatalogueOfLife/backend/issues/983

**Comment by thomasstjerne** [comment]
The user endpoint `https://api.dev.checklistbank.org/user/me` has an `editor` array (see below)
Would it be possible to fill releases into that from the backend by a DB join? The frontend auth simply scans that array for the datasetkey to see if the user has access

``````
{
    "key": 100,
    "username": "username",
    "firstname": "Thomas Stjernegaard",
    "lastname": "Jeppesen",
    "email": "email@email.org",
    "orcid": "0000-0003-1691-239X",
    "country": "DK",
    "roles": [
        "editor",
        "admin"
    ],
    "editor": [
        9847,
        9802
    ],
    "lastLogin": "2020-04-20T09:47:04.111592",
    "created": "2019-11-21T13:01:20.192964"
}
``````

**Comment by mdoering** [comment]
Probably, let me see. It might become large in some cases. There is also a /user/dataset/{datasetKey} method that checks the current user if he has editor rights

**Comment by mdoering** [comment]
Also be aware that there is a `reviewer` field with dataset keys on the user object that should also have read access to these datasets. Viewing a private release and seeing its duplicate should be possible. Just not applying any changes. The backend will guard this, so if forms are there for reviewers at least they cannot cause any harm.

This is also being taken into account in the above _isAuthorized_ method.

**Comment by mdoering** [comment]
Finally there is also a `/user/dataset/{datasetKey}/write` method to check for write access.

**Comment by mdoering** [comment]
I have deployed a change to include release keys in the user objects retrieved from the `/me` resource - but from nowhere else!

If feasable I would still prefer the UI to consult the isReadable or isWritable methods which would encapsulate all the logic better.

**Comment by mdoering** [comment]
Does it work now with the new service?

**Comment by camiplata** [comment]
@mdoering Thanks for the clarifying that releases don't have the issues or duplicate options. Nevertheless the project is not showing duplicate and issues from the xrelease details on [this issue](https://github.com/CatalogueOfLife/xcol/issues/66)

**Comment by camiplata** [comment]
Maybe we can check together how the release should look like in our next meeting as I think a might have misunderstood some of your comment above.

**Comment by mdoering** [comment]
I have deployed a new implementation to DEV which does work for me using @camiplata credentials.
I can login and do see the [COL releases](https://www.dev.checklistbank.org/dataset/2328/about) and their duplicate search and metadata/private toggles.

<img width="1394" alt="image" src="https://github.com/CatalogueOfLife/checklistbank/assets/327505/2ed7269e-92dd-4bd8-a2f4-f1e3f3737836">
