### ISSUE TITLE
Login not working on the front end

### ISSUE THREAD

**Issue by camiplata** [CatalogueOfLife/checklistbank#1278]
I can't access my account

I get Invalid Username or password 401

Using curl I get to see my user:

> camisilver@MacBook-Pro-de-CamiSilver ~ % curl -s --user camisilver:PASSWORD "https://api.checklistbank.org/user/me"
> {"key":728,"username":"camisilver","firstname":"Camila","lastname":"Plata","email":"camila.platac@gmail.com","country":"CO","roles":["reviewer","editor"],"editor":[9921,54170,1018,9885],"reviewer":[2259,2292,2325,9828,2342,9811,9877,2275,9878,9812,9893,9895,2242,2324,9843,9846,2162,2079,9845,9844,9859,2241,2294,9880,9879,9858,2223,2229,2309,2226,2307,2311,265948,2225,2224,2140,2313,2280,9816,9923,2230,9808,2363,9915,2296,9832,9850,9889,9883,9848,2157,9891,9842,9840,2165,2331,2246,2163,9830,9826,9913,2282,9838,2339,9917,2343,9834,9814,9897,9901,3,9899,2347,9903,2345,9909,9911,9905,2264,2349,2351,9907,2284,9820,265729,9902,2366,2135,9919,9837,9836,9918,9853,2235,2252,9920,9852,2365,2367,2368,9804,2332,9803,9887,9886,2220,9851,2315,9871,2237,2303,2134,2233,9854,2298,2136,2137,2139,2138,265945,2222,2255,9890,2123,9857,9882,9849,2239,9914,9815,9833,9898,2320,2204,2081,2322,2295,9922,2083,9839,9841,2164,2206,2330,2328,9892,9900,2348,2261,2344,2166,9908,9809,2336,9813,2364,9916,9835,9896,9912,9825,9827,9821,9831,9817,9819,9829,266150,9910,9906,9904,2269,2350],"lastLogin":"2023-02-04T23:41:17.008979","created":"2023-02-04T23:41:17.020494"}%

**Comment by mdoering** [comment]
<img width="1792" alt="Screenshot 2023-09-11 at 16 43 05" src="https://github.com/CatalogueOfLife/checklistbank/assets/327505/eff0f600-acdf-4b94-91fc-2d5e4523f2b8">

**Comment by mdoering** [comment]
sth with the loading of release keys to address https://github.com/CatalogueOfLife/checklistbank/issues/1268 wasnt working. I have reverted the change and login works now as usual again
