### ISSUE TITLE
Indicate source of synonyms in merged taxa

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/checklistbank#1283]
When a taxon has synonyms merged in from other sources these are not shown. For example all proles names here are from WCVP not COL https://dev.checklistbank.org/dataset/266870/taxon/6Q :

<img width="1726" alt="image" src="https://github.com/CatalogueOfLife/checklistbank/assets/327505/5d0baf02-bb92-4d92-bf1f-3df877868d7d">

I think we should indicate the primary source in the synonymy already. Whether by alias, logo or a short label/number that is listed in the footer I dont know. I tend towards the alias.

But we also need to look into proper synonym pages again as we want also secondary sources and other information displayed somewhere for all synonyms. I would argue for proper synonym pages similar to taxon pages that will replace the name details pages we currently have: https://github.com/CatalogueOfLife/checklistbank/issues/1034

**Comment by thomasstjerne** [comment]
Could you add the sourceTaxonKey to synonyms in the info object? Currently there are only sector keys.

**Comment by mdoering** [comment]
hm, that isnt that trivial. Did we do that anywhere else yet?
Or would a list of all sectors in that info object be good enough?

**Comment by thomasstjerne** [comment]
A map from sector to datasetKey would work, but let me try to do a frontend only solution for now.
