### ISSUE TITLE
Add "Source" to results in Duplicate search in xreleases

### ISSUE THREAD

**Issue by DianRHR** [CatalogueOfLife/checklistbank#1284]
https://www.dev.checklistbank.org/dataset/265693/duplicates?limit=50&offset=0

![image](https://github.com/CatalogueOfLife/xcol/assets/124217901/e94b54ac-ac9e-4144-a5b1-789ae004bd4c)

**Comment by thomasstjerne** [comment]
@mdoering for projects, this information is present in the duplicate API, but not for Xreleases.
Could you add that?
How a project response looks:
<img width="1045" alt="duplicate_sources" src="https://github.com/CatalogueOfLife/checklistbank/assets/1666484/2ddd2be0-f8ee-464b-9a75-29105aa59c2f">

**Comment by mdoering** [comment]
Now on dev also for releases!
