### ISSUE TITLE
CLB: ~~TASKS (?) or~~ ISSUES & WORKBENCH reports do not reflect resolving decisions in duplicated names correctly

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/checklistbank#1293]
- [ ] ~~Seems, ISSUES (or TASKS?) reports do not reflect duplicated names & resolving decisions correctly~~ 
ISSUES & WORKBENCH reports do not reflect resolving decisions in duplicated names correctly

All tasks are in green in _TASKS_, i.e. resolved: https://www.checklistbank.org/catalogue/3/dataset/125101/tasks

![image](https://github.com/CatalogueOfLife/checklistbank/assets/28574252/ce339946-034a-4aa0-b67e-e609cc3ede65)

However, _ISSUES_ report "Duplicate Name" shows 57 cases of duplicated names. Neither of them resolved via decision: https://www.checklistbank.org/catalogue/3/dataset/125101/workbench?decisionMode=_NULL&facet=rank&facet=issue&facet=status&facet=nomStatus&facet=nameType&facet=field&facet=authorship&facet=authorshipYear&facet=extinct&facet=environment&facet=origin&issue=duplicate%20name&limit=100&offset=0

![image](https://github.com/CatalogueOfLife/testing/assets/28574252/b68b3311-2e20-4ebf-80e7-af601856d9e6)

Checked in the preview (https://preview.catalogueoflife.org/): indeed, duplicated names appear in the CoL.

![image](https://github.com/CatalogueOfLife/checklistbank/assets/28574252/63bd2918-31a4-4b90-83db-e8542c9c2b6f)

(All left as it is for @thomasstjerne & @mdoering to look on the problem).

_Originally posted by @yroskov in https://github.com/CatalogueOfLife/testing/issues/215#issuecomment-1749487106_

**Comment by yroskov** [comment]
It looks like, TASKS reports are correct, but **decisions are not reflected in the WORKBENCH tool:**

https://www.checklistbank.org/catalogue/3/dataset/125101/duplicates?acceptedDifferent=true&authorshipDifferent=false&catalogueKey=3&category=binomial&limit=500&minSize=2&mode=STRICT&offset=0&status=synonym

**Comment by mdoering** [comment]
I am not sure if I understand the problem. Issues and decisions & duplicates are entirely different things.
Issues are flagged in the source on import and stay until the next import overwrites them. They will never change because of a decision - which is just a decision for a specific project on how to sync/integrate data from that source.

Decisions on the other hand are only applied during a sync. They have no effect on the project before the sector with that name is actually synced (again). 

With that in mind, what exactly is going wrong?

**Comment by mdoering** [comment]
I guess I know now. New decisions are not visible in the workbench, while they are shown on the duplicate tool:

https://www.checklistbank.org/catalogue/3/dataset/125101/duplicates?acceptedDifferent=true&catalogueKey=3&category=binomial&limit=100&rankDifferent=false&status=synonym&q=Erythrodiplax

https://www.checklistbank.org/catalogue/3/dataset/125101/workbench?issue=duplicate%20name&q=Erythrodiplax

The duplicate tool run directly on the database and is the correct source if in doubt.
The workbench run on the search index and it seems that index is missing some decisions. I will check if they should get updated in code

**Comment by mdoering** [comment]
Reindexing resolved it
