### ISSUE TITLE
Name match tool confused by tabs

### ISSUE THREAD

**Issue by dhobern** [CatalogueOfLife/checklistbank#1294]
Cutting and pasting pairs of columns (scientificName and authorship) from Excel into the Name match tool gives unexpected results because of the tabs.

Try matching the following against the latest COL:

```
Dishkeya bifurcata	(Braun, 1915)
Dishkeya gothica	Stonis & Solis, 2020
Dishkeya gouaniae	(Stonis & Diškus, 2007)
Dishkeya ursipedella	Diškus, Mey & Stonis, 2022
```

The two rows with parentheses around the authorship are parsed correctly to the species. The other two are matched against the genus. Replacing the tabs with spaces gives the expected result.

Pasting from Excel is not an unlikely use case.

**Comment by mdoering** [comment]
https://api.checklistbank.org/nidx/match?q=Dishkeya%20bifurcata(Braun,%201915)
https://api.checklistbank.org/nidx/match?q=Dishkeya%20gothicaStonis%20&%20Solis,%202020
https://api.checklistbank.org/nidx/match?q=Dishkeya%20gouaniae(Stonis%20&%20Di%C5%A1kus,%202007)
https://api.checklistbank.org/nidx/match?q=Dishkeya%20ursipedellaDi%C5%A1kus,%20Mey%20&%20Stonis,%202022

**Comment by mdoering** [comment]
The ampersand does not seem to be URL encoded either which leads to wrong query parameters.

**Comment by dhobern** [comment]
![image](https://github.com/CatalogueOfLife/checklistbank/assets/26148454/72f1dc7b-cf4e-43d2-a0ba-3800dc0c98ee)
![image](https://github.com/CatalogueOfLife/checklistbank/assets/26148454/20068c13-5060-4e98-a858-df405c908c6d)
