### ISSUE TITLE
New admin functions for reindexing & matching

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/checklistbank#1304]
On the admin settings page there should be 2 more buttons, both POSTing to the given URL without content:

- [x] reindex scheduler `/admin/reindex/scheduler`
- [x] rematch scheduler `/admin/rematch/scheduler`

To monitor nidx matches per dataset it would be great to have a page similar to the Elastic one, called "Names Index".
On that pagable & searchable table with all datasets like the one on ES but with column `Matched` instead of `Indexed`.

Thinking about it maybe its even fine to just add one more column to the ES page and call it "Dataset monitor"?
For a dataset the number of matches can be retrieved with `GET /dataset/{key}/matches/count`

**Comment by thomasstjerne** [comment]
I get 404´s when I do `https://api.dev.checklistbank.org/dataset/2397/matches/count`

**Comment by mdoering** [comment]
Oh, I had forgotten to deploy to dev, it was on prod only. There now

**Comment by mdoering** [comment]
I have renamed the component and path to /admin/datasets - hope I didnt break anything
