### ISSUE TITLE
CLB: Request failed with status code 400

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/checklistbank#1308]
I am experiencing this problem in CLB (2023-11-08):

![image](https://github.com/CatalogueOfLife/checklistbank/assets/28574252/706d9207-a5ad-4dd1-a121-b8a497fa0f95)

![image](https://github.com/CatalogueOfLife/checklistbank/assets/28574252/02339b42-9195-48be-8a83-960dc750c1b3)

**Comment by mdoering** [comment]
weird. I dont get this on https://www.checklistbank.org/dataset/9910/sourcemetrics
<img width="1771" alt="image" src="https://github.com/CatalogueOfLife/checklistbank/assets/327505/6faac10d-17ae-479d-9047-e5c7346df49b">

Can you try to clear caches or force refresh?
Ah, the error is actually from the importer page you visited before apparently. I still cannot reproduce this. If you could leave a URL where this happens that would be appreciated

**Comment by yroskov** [comment]
Now it works:

https://www.checklistbank.org/dataset/9910/sourcemetrics
