### ISSUE TITLE
Valid urls in dcterms:references tagged as 'url invalid'

### ISSUE THREAD

**Issue by xsainnz** [CatalogueOfLife/checklistbank#1309]
Some DOI urls in dcterms:references are being tagged as 'url invalid' eg:
https://doi.org/10.3417/1055-3177(2006)16[168:ESFTNG]2.0.CO;2
https://doi.org/10.1644/1545-1542(2002)083<1127:MDOEPD>2.0.CO;2

**Comment by mdoering** [comment]
In which dataset is that please?

**Comment by mdoering** [comment]
There are reserved characters in the URI specs which are not allowed in the URL path and need to be escaped/url encoded: https://datatracker.ietf.org/doc/html/rfc3986#section-2.2

Expressing a DOI which allow more characters in their suffix as an URL is a challenge for others too: https://tex.stackexchange.com/questions/618777/special-characters-in-doi-leading-to-invalid-urls

**Comment by mdoering** [comment]
Closing as it is true - the DOI URL given is an invalid URL and neeeds escaping
