### ISSUE TITLE
CLB: application of decisions does not work

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/checklistbank#1310]
Working with Entiminae checklist, I tried to block 83 names with portion **[GENUS NOT SPECIFIED]**: https://www.checklistbank.org/catalogue/3/dataset/1166/workbench?decisionMode=_NULL&facet=rank&facet=issue&facet=status&facet=nomStatus&facet=nameType&facet=field&facet=authorship&facet=authorshipYear&facet=extinct&facet=environment&facet=origin&limit=500&offset=0&q=%5BGENUS%20NOT%20SPECIFIED%5D 

After I clicked button _Apply Selected Decision_ CLB did not indicate any progress (previously, pop-up menu in top right corner reported the completion). After reloading page in browser, the same 83 names appear without decision.

![image](https://github.com/CatalogueOfLife/checklistbank/assets/28574252/a5f6024a-32c8-42ca-b97e-4b2f779d5b68)

![image](https://github.com/CatalogueOfLife/checklistbank/assets/28574252/dc69213a-8dc8-4d3f-946b-5670bcc08461)

**Comment by yroskov** [comment]
Whereas, here https://www.checklistbank.org/catalogue/3/dataset/1166/workbench?facet=rank&facet=issue&facet=status&facet=nomStatus&facet=nameType&facet=field&facet=authorship&facet=authorshipYear&facet=extinct&facet=environment&facet=origin&issue=indetermined&limit=100&offset=0 with names like that **Episomus var. var.confinis Faust, 1897**, **Episomus var. var.obsoletus Faust, 1897** decision "block" works as expected.

**Comment by yroskov** [comment]
2023-11-15: Working with Issues in World Ferns, I tried to apply _Complex Decision_ to the name Pteridaceae subfamily Ceratopteridoideae. It does not work:

![image](https://github.com/CatalogueOfLife/checklistbank/assets/28574252/01739c62-3336-4bbf-b0c4-e330e5b132d1)

https://www.checklistbank.org/catalogue/3/dataset/1140/workbench?facet=rank&facet=issue&facet=status&facet=nomStatus&facet=nameType&facet=field&facet=authorship&facet=authorshipYear&facet=extinct&facet=environment&facet=origin&issue=blacklisted%20epithet&limit=100&offset=0

**Comment by yroskov** [comment]
2023-11-15: Working with Issues in World Ferns, I tried to flag 147 names as Provisionally Accepted. 
https://www.checklistbank.org/catalogue/3/dataset/1140/workbench?decisionMode=_NULL&facet=rank&facet=issue&facet=status&facet=nomStatus&facet=nameType&facet=field&facet=authorship&facet=authorshipYear&facet=extinct&facet=environment&facet=origin&limit=50&nomstatus=manuscript&offset=0&status=accepted

Decisions do not work. 

![image](https://github.com/CatalogueOfLife/checklistbank/assets/28574252/188447dc-5401-4677-92ae-16090109ea81)

@olafbanki, @mdoering could you please give a **top priority to this bug**. This has become a severe problem.

**Comment by mdoering** [comment]
@thomasstjerne @yroskov see also https://github.com/CatalogueOfLife/checklistbank/issues/1313

**Comment by yroskov** [comment]
@thomasstjerne, please note  
>2023-11-15: Working with Tasks in World Ferns, I tried to flag 147 names as Provisionally Accepted.

BUT, working today with Tasks in World Plants, I flagged 24 accepted "comb. ined." names as Provisionally Accepted **without problem**: https://www.checklistbank.org/catalogue/3/dataset/1141/workbench?facet=rank&facet=issue&facet=status&facet=nomStatus&facet=nameType&facet=field&facet=authorship&facet=authorshipYear&facet=extinct&facet=environment&facet=origin&limit=50&nomstatus=manuscript&offset=0&status=accepted

I'll try to re-do job with World Ferns now again. No, it does not work.

_If it may help, Firefox console says:_

This page uses the non standard property “zoom”. Consider using calc() in the relevant property values, or using “transform” along with “transform-origin: 0 0”. [workbench](https://www.checklistbank.org/catalogue/3/dataset/1140/workbench?decisionMode=_NULL&facet=rank&facet=issue&facet=status&facet=nomStatus&facet=nameType&facet=field&facet=authorship&facet=authorshipYear&facet=extinct&facet=environment&facet=origin&limit=500&nomstatus=manuscript&offset=0&status=accepted)
XHRPOST
https://api.checklistbank.org/dataset/3/decision
[HTTP/2 400  1031ms]

XHRPOST
https://api.checklistbank.org/dataset/3/decision
[HTTP/2 400  1275ms]

XHRPOST
https://api.checklistbank.org/dataset/3/decision
[HTTP/2 400  790ms]

XHRPOST
https://api.checklistbank.org/dataset/3/decision
[HTTP/2 400  1034ms]

XHRPOST
https://api.checklistbank.org/dataset/3/decision
[HTTP/2 400  906ms]

XHRPOST
https://api.checklistbank.org/dataset/3/decision
[HTTP/2 400  789ms]

XHRPOST
https://api.checklistbank.org/dataset/3/decision
[HTTP/2 400  789ms]

XHRPOST
https://api.checklistbank.org/dataset/3/decision
[HTTP/2 400  1032ms]

XHRPOST
https://api.checklistbank.org/dataset/3/decision
[HTTP/2 400  910ms]

XHRPOST
https://api.checklistbank.org/dataset/3/decision
[HTTP/2 400  1032ms]

XHRPOST
https://api.checklistbank.org/dataset/3/decision
[HTTP/2 400  909ms]

XHRPOST
https://api.checklistbank.org/dataset/3/decision
[HTTP/2 400  1153ms]

XHRPOST
https://api.checklistbank.org/dataset/3/decision
[HTTP/2 400  909ms]

XHRPOST
https://api.checklistbank.org/dataset/3/decision
[HTTP/2 400  1152ms]

XHRPOST
https://api.checklistbank.org/dataset/3/decision
[HTTP/2 400  903ms]

XHRPOST
https://api.checklistbank.org/dataset/3/decision
[HTTP/2 400  1026ms]

XHRPOST
https://api.checklistbank.org/dataset/3/decision
[HTTP/2 400  902ms]

XHRPOST
https://api.checklistbank.org/dataset/3/decision
[HTTP/2 400  943ms]

XHRPOST
https://api.checklistbank.org/dataset/3/decision
[HTTP/2 400  1065ms]

XHRPOST
https://api.checklistbank.org/dataset/3/decision
[HTTP/2 400  939ms]

XHRPOST
https://api.checklistbank.org/dataset/3/decision
[HTTP/2 400  938ms]

XHRPOST
https://api.checklistbank.org/dataset/3/decision
[HTTP/2 400  1184ms]

XHRPOST
https://api.checklistbank.org/dataset/3/decision
[HTTP/2 400  1182ms]

XHRPOST
https://api.checklistbank.org/dataset/3/decision
[HTTP/2 400  937ms]

XHRPOST
https://api.checklistbank.org/dataset/3/decision
[HTTP/2 400  940ms]

XHRPOST
https://api.checklistbank.org/dataset/3/decision
[HTTP/2 400  1062ms]

XHRPOST
https://api.checklistbank.org/dataset/3/decision
[HTTP/2 400  936ms]

XHRPOST
https://api.checklistbank.org/dataset/3/decision
[HTTP/2 400  1058ms]

XHRPOST
https://api.checklistbank.org/dataset/3/decision
[HTTP/2 400  1181ms]

XHRPOST
https://api.checklistbank.org/dataset/3/decision
[HTTP/2 400  1058ms]

XHRPOST
https://api.checklistbank.org/dataset/3/decision
[HTTP/2 400  1057ms]

XHRPOST
https://api.checklistbank.org/dataset/3/decision
[HTTP/2 400  1179ms]

XHRPOST
https://api.checklistbank.org/dataset/3/decision
[HTTP/2 400  1057ms]

XHRPOST
https://api.checklistbank.org/dataset/3/decision
[HTTP/2 400  1178ms]

XHRPOST
https://api.checklistbank.org/dataset/3/decision
[HTTP/2 400  1056ms]

XHRPOST
https://api.checklistbank.org/dataset/3/decision
[HTTP/2 400  1177ms]

XHRPOST
https://api.checklistbank.org/dataset/3/decision
[HTTP/2 400  1055ms]

XHRPOST
https://api.checklistbank.org/dataset/3/decision
[HTTP/2 400  1054ms]

XHRPOST
https://api.checklistbank.org/dataset/3/decision
[HTTP/2 400  1176ms]

XHRPOST
https://api.checklistbank.org/dataset/3/decision
[HTTP/2 400  1054ms]

XHRPOST
https://api.checklistbank.org/dataset/3/decision
[HTTP/2 400  1056ms]

XHRPOST
https://api.checklistbank.org/dataset/3/decision
[HTTP/2 400  1176ms]

XHRPOST
https://api.checklistbank.org/dataset/3/decision
[HTTP/2 400  1175ms]

XHRPOST
https://api.checklistbank.org/dataset/3/decision
[HTTP/2 400  1055ms]

XHRPOST
https://api.checklistbank.org/dataset/3/decision
[HTTP/2 400  1174ms]

XHRPOST
https://api.checklistbank.org/dataset/3/decision
[HTTP/2 400  1173ms]

XHRPOST
https://api.checklistbank.org/dataset/3/decision
[HTTP/2 400  1054ms]

Cross-Origin Request Warning: The Same Origin Policy will disallow reading the remote resource at https://download.checklistbank.org/.status.json?cachebust=0.9308571525730455 soon. (Reason: When the `Access-Control-Allow-Headers` is `*`, the `Authorization` header is not covered. To include the `Authorization` header, it must be explicitly listed in CORS header `Access-Control-Allow-Headers`).

​

**Comment by mdoering** [comment]
For the 400 bad request fern requests I can see in the logs that there is/was a decision already for the same source id. For example:

> Violated unique constraint: 
> ### Error updating database.  Cause: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "decision_dataset_key_subject_dataset_key_subject_id_key"
>   Detail: Key (dataset_key, subject_dataset_key, subject_id)=(3, 1140, Polypodiales-Pteridaceae-Vittarioideae-Haplopteris-guineensis-variety-camerooniana-(Schelpe)) already exists.

Having more than one decision per source name and project is forbidden.

The problem I have is that I don't see any option to apply a decision, see #1313

**Comment by thomasstjerne** [comment]
So these names come up in the search even though `&decisionMode=_NULL`  param is given.
Seems  for these names there are decisions in the DB that are not in Elastic?

**Comment by mdoering** [comment]
I have started a reindexing of the COL project - should be in sync in an hour or so

**Comment by mdoering** [comment]
indexing is through - does the problem remain?

**Comment by thomasstjerne** [comment]
Thats solved it.

**Comment by yroskov** [comment]
**2023-11-17:**

> ...2023-11-15: Working with Tasks in World Ferns, I tried to flag 147 accepted "comb. ined." names as Provisionally Accepted.

(1) I have checked the list here https://www.checklistbank.org/catalogue/3/dataset/1140/workbench?decisionMode=_NULL&facet=rank&facet=issue&facet=status&facet=nomStatus&facet=nameType&facet=field&facet=authorship&facet=authorshipYear&facet=extinct&facet=environment&facet=origin&limit=50&nomstatus=manuscript&offset=0&status=accepted
**all names have correctly applied decisions** 

(2) I deleted couple of decisions and re-applied them. **All work as expected.**

> ...2023-11-15: Working with Issues in World Ferns, I tried to apply Complex Decision to the name Pteridaceae subfamily Ceratopteridoideae. It does not work. After reloading the page in browser, the name appear without decision.

Correct decision for _Pteridaceae subfamily Ceratopteridoideae_ was in place. I deleted it and tried to re-apply complex decision again. Hmm, at least **interface did not show me that decision was applied** (I reloaded page in the browser):
https://www.checklistbank.org/catalogue/3/dataset/1140/workbench?facet=rank&facet=issue&facet=status&facet=nomStatus&facet=nameType&facet=field&facet=authorship&facet=authorshipYear&facet=extinct&facet=environment&facet=origin&issue=blacklisted%20epithet&limit=100&offset=0

![image](https://github.com/CatalogueOfLife/checklistbank/assets/28574252/13e8e7d7-37b6-4b03-b96e-0e63ceab7aec)

**Comment by yroskov** [comment]
**2023-11-17:**

>...Working with Entiminae checklist, I tried to block 83 names with portion [GENUS NOT SPECIFIED]

All decisions are in place here  https://www.checklistbank.org/catalogue/3/dataset/1166/workbench?decisionMode=_NULL&facet=rank&facet=issue&facet=status&facet=nomStatus&facet=nameType&facet=field&facet=authorship&facet=authorshipYear&facet=extinct&facet=environment&facet=origin&limit=500&offset=0&q=%5BGENUS%20NOT%20SPECIFIED%5D

I deleted couple of decisions and re-applied them. **All work as expected.**
