### ISSUE TITLE
CLB: cannot access Verbatim data being inside the project (status code 404)

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/checklistbank#1311]
My steps:

Working with 3i Auchenorrhyncha data INSIDE project 3, I tried to view verbatim data for the name _Aconophora imbellis Fairmaire, 1846_ from Workbench page

https://www.checklistbank.org/catalogue/3/dataset/2317/workbench?facet=rank&facet=issue&facet=status&facet=nomStatus&facet=nameType&facet=field&facet=authorship&facet=authorshipYear&facet=extinct&facet=environment&facet=origin&limit=50&offset=0&status=provisionally%20accepted

When I clicked on Verbatim bookmark, I get a message _HTTP 404 Not Found_

![image](https://github.com/CatalogueOfLife/checklistbank/assets/28574252/165cc294-f7ac-493f-8873-86c2f613f4bd)

https://www.checklistbank.org/catalogue/3/dataset/2317/taxon/52064:
![image](https://github.com/CatalogueOfLife/checklistbank/assets/28574252/2de22233-5867-4879-83a5-19ccd4236a49)

**Comment by yroskov** [comment]
However, I can access Verbatim data OUTSIDE the project: 

https://www.checklistbank.org/dataset/2317/taxon/52064:
![image](https://github.com/CatalogueOfLife/checklistbank/assets/28574252/0de9cfee-08ae-4b67-a0a2-ec0d0befe54f)

**Comment by mdoering** [comment]
That is correct. True verbatim data only exists when some text archive was read. A project doesnt do that, but instead copies data from a source. We then also leave a "verbatim source" record, but that only tracks the source dataset, identifier and potentially issues. Thats why the UI does not show a verbatim tab for project records, e.g. https://www.checklistbank.org/catalogue/3/taxon/6b48b7c0-7531-4dac-9eb9-f6073b502183

The source view you gave above should show the verbatim tab though. For some odd reason there is [no verbatim record](https://api.checklistbank.org/dataset/2317/taxon/52064/verbatim) existing for this taxon: https://api.checklistbank.org/dataset/2317/taxon/52064

@thomasstjerne the UI fails to render and the 404 brings down the page
