### ISSUE TITLE
Is not possible to navigate to the source of any given name

### ISSUE THREAD

**Issue by camiplata** [CatalogueOfLife/checklistbank#1314]
Within the xrelease, starting on the taxon page is not possible to go to the source, I get a 404 error:

![7japM34VfI](https://github.com/CatalogueOfLife/xcol/assets/5700527/757882e3-eea1-4867-a77d-f78c210d3911)

<img width="399" alt="Captura de pantalla 2023-11-02 a la(s) 8 31 43 a m" src="https://github.com/CatalogueOfLife/xcol/assets/5700527/76bef91a-3c2e-43a3-a204-f55581b63445">

**Comment by thomasstjerne** [comment]
@mdoering The api says it doesn´t exist: https://api.dev.checklistbank.org/dataset/266870/source/2041

**Comment by mdoering** [comment]
works on latest release now: https://www.dev.checklistbank.org/dataset/2011/taxon/urn:lsid:marinespecies.org:taxname:873742
https://www.dev.checklistbank.org/dataset/275521/source/2011
