### ISSUE TITLE
Sources are not listed on the xrelease

### ISSUE THREAD

**Issue by camiplata** [CatalogueOfLife/checklistbank#1317]
<img width="1307" alt="Captura de pantalla 2023-11-02 a la(s) 8 55 09 a m" src="https://github.com/CatalogueOfLife/xcol/assets/5700527/4f7c6377-3922-4951-a946-7b20154d5916">
Releated to CatalogueOfLife/checklistbank#1314

**Comment by thomasstjerne** [comment]
It looks like there are no sources for the two xreleases I see on dev:
https://api.dev.checklistbank.org/dataset/271395/source
https://api.dev.checklistbank.org/dataset/266870/source

Or the API doesn´t return them, properly

**Comment by camiplata** [comment]
This is working nicely now.

<img width="1418" alt="Captura de pantalla 2024-03-13 a la(s) 5 36 22 p m" src="https://github.com/CatalogueOfLife/checklistbank/assets/5700527/50bbddee-f464-4363-9443-a8f7bab1424e">
