### ISSUE TITLE
DwC-A download fails

### ISSUE THREAD

**Issue by camiplata** [CatalogueOfLife/checklistbank#1340]
When attempting to download a DwC-A the page goes blank and I receive an email that says "We are sorry, but an error has occurred processing your DwCA..."

This is what I get on the network inspection

<img width="1499" alt="Captura de pantalla 2023-12-07 a la(s) 4 39 18 p m" src="https://github.com/CatalogueOfLife/checklistbank/assets/5700527/5f26d7a4-e20d-4ad1-bbfd-f34a2a794b9b">

All the other formats work without problems. I tested this in a couple of datasets.

**Comment by mdoering** [comment]
yes, just fixed
