### ISSUE TITLE
ChecklistBank: how to include reference details in download 

### ISSUE THREAD

**Issue by mattbuys** [CatalogueOfLife/checklistbank#1342]
Keen to know how to include field "Reference" in species download from ChecklistBank

**Comment by mdoering** [comment]
References should be part of an "extended" cold or dwca download.
But we have a problem with the interface since a few weeks that you cannot request such downloads through the checklistbank website: https://github.com/CatalogueOfLife/checklistbank/issues/1321

We'll try to fix that asap!

**Comment by thomasstjerne** [comment]
@mattbuys you are now able to check "extended" on the download page
