### ISSUE TITLE
Opportunity to improve parsing of citation (DWC: namePublishedIN) field

### ISSUE THREAD

**Issue by mattbuys** [CatalogueOfLife/checklistbank#1343]
Current field contains:

1. year, 
2. sometimes authors (often as part of an "In: " statement), 
3. name/volume/page of publication.

There's no easy way to atomise these three elements. Any suggestions?

Maybe for DWC export use namePublishedInYear for point 1

**Comment by mdoering** [comment]
DwC does not handle parsed citations. If you want that please use the richer ColDP format!

**Comment by mdoering** [comment]
... there surely is room for better extracting of publication information from authorships.
But that is rather difficult & error prone, so we haven't made that a high priority for now. Ideally it is already supplied in a parsed way or at least with a DOI so we can lookup metadata in external services like CrossRef.
