### ISSUE TITLE
Can't access 'COL: releases' which is only sometimes on left menu

### ISSUE THREAD

**Issue by jar398** [CatalogueOfLife/checklistbank#1346]
I was able to find the 'COL: releases' list once tonight, but subsequently it never showed up again. It should be just below 'Downloads'.  I cleared cookies, no change.

Could be a browser issue, haven't checked a different browser yet.  I'm using Firefox 116.0.1 (64-bit)  on Debian.

The effect of this is that I can't figure out how to access, say, COL22.  It doesn't even work as a search term.

**Comment by jar398** [comment]
Tried two browsers on MacOS.

Safari 3.1.3 MacOS 10.15.7
  COL: releases does not show up at all.

Firefox 121.0 (64-bit) on MacOS 10.15.7:
  COL: releases  shows up the first time I visit checklistbank.org.
But after I download a subtree of COL22, it has disappeared.
If I refresh the page, I see 'COL: releases' for about half a second, and then it disappears.

**Comment by mdoering** [comment]
There are various ways to access the list of COL releases. 

 1) If you are NOT logged in you'll see a COL: releases item in the left menu. It works for me on both Safari and Chrome. When you are logged in it disappears though. @thomasstjerne maybe we should put a link to the CLB home page or keep the menu item for everyone? The menu becomes a bit cluttered though if we keep this as a first level item
 2) you can go to the [dataset search](https://www.checklistbank.org/dataset) and select "COL working draft" in the `released from` field for filtering.
 3) you can go to the [COL project](https://www.checklistbank.org/dataset/3/about) page and hit the `releases` menu item

**Comment by mdoering** [comment]
We have changed the menu and integrated the COL releases as a button in the dataset search page
