### ISSUE TITLE
Cannot upload TSV file to bulk matching

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/checklistbank#1349]
Who uploading a TSV file with the `.tsv` file suffix the API responds with a 503. I presume a wrong content type is send?
When renaming the file to `.txt` it all works.

**Comment by mdoering** [comment]
Example 
[observations_20230525_1305xx.tsv.zip](https://github.com/CatalogueOfLife/checklistbank/files/13979203/observations_20230525_1305xx.tsv.zip)

**Comment by thomasstjerne** [comment]
I think the API should actually accept `text/tab-separated-values` for `.tsv`: https://mimetype.io/text/tab-separated-values

The UI does not actively handle mime types - it just sends what the file system says.

If it is tedious for the backend, I can surely do an exception and explicitly change mime type for `.tsv`

**Comment by mdoering** [comment]
Easy to add, will do that. Do you know where exactly it is decided what mime type is send? There are so many for most types, even for json and especially for zip and compression

**Comment by mdoering** [comment]
CSV is interesting too, `text/comma-separated-values` is deprecated https://mimetype.io/text/csv
