### ISSUE TITLE
Add sector publisher project tab

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/checklistbank#1350]
For projects we need to manage sector publishers, i.e. publishers of datasets that sectors are automatically created for in xreleases and which we use to aggregated sectors & metrics as "sources".

I would propose a new "publisher" tab in Options.
As there will only be a handful publishers we should be able to use a table similar to users.
Adding a new publisher should query the GBIF registry and select a publishers UUID and title from it. The title and alias (required) can be changed by a user, only the uuid key is fixed.

The CRUD API is at `/dataset/{key}/sector/publisher` with the following Publisher class:

```
Integer datasetKey;
UUID id;
String alias;
String title;
String description;
LocalDateTime created;
Integer createdBy;
LocalDateTime modified;
Integer modifiedBy;
```

for each publishers there should be a link to a) the GBIF publisher page and b) the dataset search with that UUID as a filter. 

It would also be good to show 2 counts:
 - total count of all datasets published in CLB by this publisher (this could be the link to the dataset search)
 - number of sectors that would be created in the next xrelease for that publisher, i.e. count of datasets published which are not yet a sector. This should also be a dataset search link with a new query parameter `withoutSectorInProject={projectDatasetKey}` and allows to preview the new datasets before a release is done.

**Comment by thomasstjerne** [comment]
Should `https://api.dev.checklistbank.org/dataset/9847/sector/publisher` list publishers for a project then?

**Comment by mdoering** [comment]
Yes. For a project or release.
Management should only be possible for the project and release dataset keys give you access to the archived version as it was at release time. Im still working on that though.

**Comment by thomasstjerne** [comment]
What does the `datasetKey` refer to?

**Comment by mdoering** [comment]
datasetKey is the project or release key the sector publisher belongs to.
This is not a global publisher list, just the set of publishers that are configured in a project to create sectors automatically and act as an aggregation source. Hence this can change from project to project and release to release

**Comment by mdoering** [comment]
I have created the publishers for COL on dev as they should be at this stage

**Comment by thomasstjerne** [comment]
> datasetKey is the project or release key the sector publisher belongs to.
Sure. It is the key from the path parameter obviously
