### ISSUE TITLE
Taxon page Sources

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/checklistbank#1352]
On taxon details pages like this:
https://www.dev.checklistbank.org/dataset/279769/taxon/B74NW

the UI requests a [source](https://api.dev.checklistbank.org/dataset/279769/nameusage/B74NW/source) which is already included in the info object, so it should be redundant.

Next to the single Source entry is also a Sources block with 2 sources listed. Where do they come from and what do they actually refer to? Are these secondary sources and has the visualisation of those changed? If needed, should we maybe jut link the title and not show the alias at all?

<img width="1513" alt="Screenshot 2024-01-23 at 08 16 05" src="https://github.com/CatalogueOfLife/checklistbank/assets/327505/110dd71b-e117-4511-9dde-aff8eab70631">

**Comment by thomasstjerne** [comment]
The redundant call has been removed.
I renamed "Sources" to "Secondary sources" and added a filter so the primary source will not be included there.
That "Secondary sources" block is based on this: https://github.com/CatalogueOfLife/checklistbank/issues/1283

**Comment by mdoering** [comment]
Ah, thats yet another block then. These are the primary sources of the synonyms. Secondary sources are the ones we have in extended releases when information is partially updated, e.g. the authorship or publishedIn reference. They always come with the kind of information block that these sources refer to. 

So we really end up with 3 sources:
 - `Source`: the primary one for the main name of the taxon or synonym if its the synonym page
 - `Secondary sources`: the secondary sources for the main name of the taxon or synonym
 - `Synonym sources`: the distinct set of other sources for all synonyms (only on taxon pages)
 
 I think we should show them in that order and label them as given above. Makes sense?
 
@DianRHR also had a related question yesterday on name relations. On some taxon pages the synonymy changed due to :
  - a new synonym added by some merge source
  - new homotypic relations of existing synonyms due to homotypic grouping

How can we highlight that this information was added/changed in the extended release? New synonyms are indicated by the source, I think that is fine. But changed or new homotypic relations?

**Comment by mdoering** [comment]
See https://github.com/CatalogueOfLife/xcol/issues/88#issuecomment-1904868425 for examples
