### ISSUE TITLE
Create publisher page

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/checklistbank#1355]
We need a publisher page to link to from sources and also to display content of a publisher.
Suggest to include:

Publisher Infos
 - alias
 - title
 - description
 - GBIF link

Project sectors: count (link to sector search)
Datasets published: count (link to dataset search)

**Comment by mdoering** [comment]
count datasets: http://api.dev.checklistbank.org/dataset?limit=0&gbifPublisherKey=0674aea0-a7e1-11d8-9534-b8a03c50a862

count sectors: http://api.dev.checklistbank.org/sector?limit=0&gbifPublisherKey=0674aea0-a7e1-11d8-9534-b8a03c50a862

**Comment by mdoering** [comment]
how do I reach a publisher page?

**Comment by thomasstjerne** [comment]
So far only from the list of publishers: https://www.dev.checklistbank.org/catalogue/3/publishers

**Comment by mdoering** [comment]
maybe we should add the project title (or alias) to all project pages at the top next to the project tag?
A publisher [page](https://www.dev.checklistbank.org/catalogue/3/publisher/0674aea0-a7e1-11d8-9534-b8a03c50a862) now say for example `Publisher: SNSB [Project]`

**Comment by mdoering** [comment]
one thing - the API uses the `publisherKey` query param in all searches but the dataset one.
The publisher page now uses `gbifPublisherKey` which is not understood so the counts are wrong.

https://api.dev.checklistbank.org/dataset/3/sector?limit=0&publisherKey=0674aea0-a7e1-11d8-9534-b8a03c50a862
https://api.dev.checklistbank.org/dataset/3/sector?limit=0&gbifPublisherKey=0674aea0-a7e1-11d8-9534-b8a03c50a862

How about I also change the dataset one to use publisherKey only? I dont think it needs the gbif prefix really, or does it?

**Comment by thomasstjerne** [comment]
It only uses `gbifPublisherKey` for the facet and link to the dataset search: https://www.dev.checklistbank.org/dataset?gbifPublisherKey=943a5811-d56e-4c37-853d-bd64957d3833 - it uses `publisherKey` for sector count and link.

**Comment by mdoering** [comment]
hm, the page shows a lot of sectors though when there should only be 33

**Comment by thomasstjerne** [comment]
You are right - fixed now
