### ISSUE TITLE
unexpected issue "rank name suffix conflict" on a genus

### ISSUE THREAD

**Issue by camiplata** [CatalogueOfLife/checklistbank#1363]
I'm checking the fleas new version on dev and I get an issue on a genus that does not like rigth, I think the ending of Wagnerina should not be flagged as "rank name suffix conflict"

<img width="400" alt="Captura de pantalla 2024-02-16 a la(s) 6 46 36 p m" src="https://github.com/CatalogueOfLife/checklistbank/assets/5700527/2ba7bc7e-9e69-493c-b072-c7bea38dfa80">

link: https://www.dev.checklistbank.org/dataset/283124/taxon/G308

**Comment by mdoering** [comment]
But how would you tell that apart from real _erina_s? I dont see a solution. Obviously you get good names being flagged, that is to be expected a lot

**Comment by camiplata** [comment]
Then lest keep it as it is, the flag its doing is job
