### ISSUE TITLE
Data Import on dev is failing

### ISSUE THREAD

**Issue by camiplata** [CatalogueOfLife/checklistbank#1368]
I get the following message when[ importing a file on DEV](https://www.dev.checklistbank.org/dataset/283124/imports), I imported the same file without problem on [PROD](https://www.checklistbank.org/dataset/54170/imports)

Last Import Job of this dataset failed.
PersistenceException: ### Error updating database. Cause: org.postgresql.util.PSQLException: ERROR: update or delete on table "name_mod17" violates foreign key constraint "name_match_dataset_key_name_id_fkey18" on table "name_match" `Detail: Key (dataset_key, id)=(283124, 2754) is still referenced from table "name_match`". ### The error may exist in life/catalogue/db/mapper/DatasetPartitionMapper.xml ### The error may involve defaultParameterMap ### The error occurred while setting parameters ### SQL: DELETE FROM name WHERE dataset_key=?; ### Cause: org.postgresql.util.PSQLException: ERROR: update or delete on table "name_mod17" violates foreign key constraint "name_match_dataset_key_name_id_fkey18" on table "name_match" Detail: Key (dataset_key, id)=(283124, 2754) is still referenced from table "name_match".; PSQLException: ERROR: update or delete on table "name_mod17" violates foreign key constraint "name_match_dataset_key_name_id_fkey18" on table "name_match" Detail: Key (dataset_key, id)=(283124, 2754) is still referenced from table "name_match".

**Comment by mdoering** [comment]
it now works for me
