### ISSUE TITLE
Plazi names missing on XCOL

### ISSUE THREAD

**Issue by camiplata** [CatalogueOfLife/checklistbank#1370]
In a radmon check I found that  new names of a plazi sectors are not being merged/added to the xcol:

Both the  this stickinsect genus [Sinophasma Guenther, 1940](https://www.dev.checklistbank.org/dataset/171967/taxon/F7CE1698758B5EBA7D22975EEADB069E.taxon), and its species [Sinophasma damingshanensis Ho](https://www.dev.checklistbank.org/dataset/171967/taxon/9FC4F4E5EE0C9286330C8142D44E42DE.taxon) should have been added to the xcol.

The dataset appears as a source of the xcol
<img width="600" alt="Captura de pantalla 2024-02-29 a la(s) 10 47 25 a m" src="https://github.com/CatalogueOfLife/checklistbank/assets/5700527/8468ec1a-ed33-4e90-a5d1-299d3e61007d">

[but has no taxa added to the xcol](https://www.dev.checklistbank.org/dataset/284983/names?SECTOR_DATASET_KEY=171967&facet=rank&facet=issue&facet=status&facet=nomStatus&facet=nomCode&facet=nameType&facet=field&facet=authorship&facet=authorshipYear&facet=extinct&facet=environment&facet=origin&facet=sectorMode&limit=50&offset=0&sortBy=taxonomic)

<img width="600" alt="Captura de pantalla 2024-02-29 a la(s) 10 49 23 a m" src="https://github.com/CatalogueOfLife/checklistbank/assets/5700527/9da0e593-816d-4d2c-b32d-c2eade2b048e">

here some more examples of species missing on the xcol:

-[Cornifronus simplex](https://www.dev.checklistbank.org/dataset/284627/taxon/EB5E87D0B808FFCEFF33A3DDD6D0F868.taxon)
- [Allorhogas lavraensis](https://www.dev.checklistbank.org/dataset/284622/taxon/464A87CF7B41FFA2FF71FBB5897118ED.taxon)

Non of this name have relevant issuues

The logs also show that there were no names added:
<img width="1214" alt="Captura de pantalla 2024-02-29 a la(s) 11 13 52 a m" src="https://github.com/CatalogueOfLife/checklistbank/assets/5700527/8a773921-bda9-47df-a36c-87154b82a38a">

<img width="1211" alt="Captura de pantalla 2024-02-29 a la(s) 11 16 06 a m" src="https://github.com/CatalogueOfLife/checklistbank/assets/5700527/3027f6c6-dfa3-4dbb-a831-e99be1e66139">

**Comment by camiplata** [comment]
For [Sinophasma Guenther, 1940](https://www.dev.checklistbank.org/dataset/171967/taxon/F7CE1698758B5EBA7D22975EEADB069E.taxon) apparently it was an issue with Elastich Search rather than an issue from the backend. The data appear now on the XCOL-2024-02-16  but not on the latest release XCOL-2024-03-02, as the search is not working.

 [Cornifronus simplex](https://www.dev.checklistbank.org/dataset/284627/taxon/EB5E87D0B808FFCEFF33A3DDD6D0F868.taxon) does not appears in neither search or  browse  of any of the last xreleases but it does appears on the logs

<img width="597" alt="Captura de pantalla 2024-03-13 a la(s) 11 28 21 a m" src="https://github.com/CatalogueOfLife/checklistbank/assets/5700527/129e5d91-0c77-4e38-ad8b-126431370356">

The logs show:
40890691:2024-03-03 15:03:21,757 DEBUG NameIndexImpl             284627 Matched Cornifronus simplex Jin, Li, & Zhang, 2024 => VARIANT: Cornifronus simplex Jin, Li & Zhang, 2024 [SPECIES]
40890692:2024-03-03 15:03:21,758 DEBUG TreeBaseHandler           284627 Created ACCEPTED SPECIES usage Cornifronus simplex Jin, Li, & Zhang, 2024 from source 284627:~C298

The taxon id can be track back to the a functioning xrelease page: https://www.dev.checklistbank.org/dataset/285035/taxon/~C298

I keep the issue in reference to the ElastichSerch issue that causes this "missing" names

**Comment by camiplata** [comment]
The genus now appears but no the species Sinophasma damingshanensis

<img width="735" alt="Captura de pantalla 2024-10-17 a la(s) 4 49 03 p m" src="https://github.com/user-attachments/assets/155de863-e7dc-46b1-9de1-37d28dd5458b">

**Comment by mdoering** [comment]
It is in the base release already:
https://www.checklistbank.org/dataset/304443/taxon/4XLDJ

**Comment by mdoering** [comment]
All the other examples are also there:

<img width="1241" alt="image" src="https://github.com/user-attachments/assets/584d1c8f-45ce-40df-95f4-490484d6b0d6">

<img width="1251" alt="image" src="https://github.com/user-attachments/assets/17c2af9c-8dc2-40c2-be02-df2c318a8fef">

**Comment by camiplata** [comment]
This is now an issue for Plazi, a type on the author name has create this empty duplicated genus

**Comment by camiplata** [comment]
author typo, but now is fixed
