### ISSUE TITLE
CLB: item SECTORS disappeared in the menu SOURCE

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/checklistbank#1373]
For attaention of @thomasstjerne: 

**Item SECTORS disappeared in the menu SOURCE**:

![image](https://github.com/CatalogueOfLife/backend/assets/28574252/c6f629ea-40f9-4538-b08a-92a0fec70d83)

It was convenient option to access sectors for active GSD inside the project. Now I need to do extra steps, i.e. go to the project menu, and search for GSD again.

It would be more comfortable to have a full set of options to work with GSD inside the project. Please bring back item SECTORS in active GSD menu inside the project.

**Comment by mdoering** [comment]
See https://github.com/CatalogueOfLife/checklistbank/issues/1326 for menu changes

**Comment by mdoering** [comment]
@thomasstjerne my original proposal did not include the sector menu item, but I don't mind bringing it back as a link to the project sector page, prefilled with the source. Alternatively we could think of another place in a GSD page to offer a link to the sectors. 

@yroskov Guess the same is also true for decisions.

**Comment by yroskov** [comment]
>a link to the project sector page, prefilled with the source

Yes, this will be enough
