### ISSUE TITLE
CLB: decisions in MANUSCRIPT NAMES report do not work

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/checklistbank#1374]
For attention of @thomasstjerne: 

Working with ITIS, I tried to resolve Manuscript Names report, applying status "Provisionally Accepted" to 5 accepted species:
https://www.checklistbank.org/catalogue/3/dataset/2144/workbench?facet=rank&facet=issue&facet=status&facet=nomStatus&facet=nameType&facet=field&facet=authorship&facet=authorshipYear&facet=extinct&facet=environment&facet=origin&limit=50&nomstatus=manuscript&offset=0&status=accepted

**The interface didn't show neither progress, nor results**

Before attempt:
![image](https://github.com/CatalogueOfLife/backend/assets/28574252/df38b53d-d45c-4c56-a084-865deaf57113)

After attempt:
![image](https://github.com/CatalogueOfLife/backend/assets/28574252/41dcf991-57b8-455f-9288-3742f5d3c613)

**Comment by thomasstjerne** [comment]
It is a backend error - I think the decisions are missing in the index.
And then when you try to re-appply  them you get: `
org.apache.ibatis.exceptions.PersistenceException: ### Error updating database. Cause: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "decision_dataset_key_subject_dataset_key_subject_id_key"` 

I have updated the UI to display those backend errors

**Comment by mdoering** [comment]
I will look into the bad index which we had seen before.
And try to return a more readable message that there is a decision existing already

**Comment by yroskov** [comment]
@mdoering, this issue is not fixed yet.

Yesterday I tried to apply "provisionally accepted" status in World Ferns, and decisions were (and are) not shown neither in the report nor in the panel. 139 accepted names here supposed to have decision "provisionally accepted", but they don't:
https://www.checklistbank.org/catalogue/3/dataset/1140/workbench?decisionMode=_NULL&facet=rank&facet=issue&facet=status&facet=nomStatus&facet=nameType&facet=field&facet=authorship&facet=authorshipYear&facet=extinct&facet=environment&facet=origin&limit=500&nomstatus=manuscript&offset=0&status=accepted

![image](https://github.com/CatalogueOfLife/checklistbank/assets/28574252/f5e2cf6f-de9f-4b71-bc15-3fac38a97f6c)

I tried to reply these decisions again today, and get error message (but decisions are still not shown):
![image](https://github.com/CatalogueOfLife/checklistbank/assets/28574252/f0085c56-aa0b-4da8-a242-16b4e27e84c0)
