### ISSUE TITLE
Some decisions not displaying in the workbench

### ISSUE THREAD

**Issue by gdower** [CatalogueOfLife/checklistbank#1385]
This block decision does not display in the workbench:

http://api.checklistbank.org/dataset/3/decision/265382

![image](https://github.com/CatalogueOfLife/checklistbank/assets/8573609/48430611-ea4a-42d6-b057-64b3956ba3dd)

Here's a link to the page with decisions not displaying:

https://www.checklistbank.org/catalogue/3/dataset/1008/workbench?facet=rank&facet=issue&facet=status&facet=nomStatus&facet=nameType&facet=field&facet=authorship&facet=authorshipYear&facet=extinct&facet=environment&facet=origin&issue=inconsistent%20authorship&limit=100&offset=0

With the decisions not visible, the backend throws errors when attempting to add another duplicate decision, which is likely the same issue reported by @yroskov  in the backend: https://github.com/CatalogueOfLife/backend/issues/1290#issuecomment-1930629939

**Comment by mdoering** [comment]
The decision is indeed there: https://www.checklistbank.org/catalogue/3/decision?limit=100&name=Cochliophagus%20tornieri%20müller&offset=0&subjectDatasetKey=1008

I have reindexed ReptileDB and it works now. Closing with the hope this indexing problem will not show up again once the new index is build mid next week
