### ISSUE TITLE
CLB interface shows empty ISSUES reports after decisions applied

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/checklistbank#1388]
Resolving ISSUES in ReptileDB (id 1008) I met following bug: as soon as I applied decisions in the report, after page refresh, the report become empty in whatever option I choose (With decision / Without decision / All).

_Example:_

**Indetermined** report contained 2 names. After complex decision application it become empty: https://www.checklistbank.org/catalogue/3/dataset/1008/workbench?facet=rank&facet=issue&facet=status&facet=nomStatus&facet=nameType&facet=field&facet=authorship&facet=authorshipYear&facet=extinct&facet=environment&facet=origin&issue=indetermined&limit=100&offset=0

All:
![image](https://github.com/CatalogueOfLife/checklistbank/assets/28574252/4eedcbf2-4205-43e7-8757-c9f2ba523e95)

With decision:
![image](https://github.com/CatalogueOfLife/checklistbank/assets/28574252/1196b8c0-11d3-415b-b368-d28eff686ea0)

Without decision:
![image](https://github.com/CatalogueOfLife/checklistbank/assets/28574252/841f7c9a-1515-44f4-802c-4c1aa7ec10b0)

**Comment by yroskov** [comment]
Comment: **TASKS reports** work fine, as expected with options Yes/No/Ignore decisions.

**Comment by mdoering** [comment]
Funny thing is you can't find those `Indetermined` usages in the reptileDB search any longer either: https://www.checklistbank.org/dataset/1008/names?facet=rank&facet=issue&facet=status&facet=nomStatus&facet=nomCode&facet=nameType&facet=field&facet=authorship&facet=authorshipYear&facet=extinct&facet=environment&facet=origin&facet=sectorMode&issue=indetermined&limit=50&offset=0

Only via the verbatim view which queries the database: https://www.checklistbank.org/catalogue/3/dataset/1008/verbatim?issue=indetermined

The usage itself is there and you can search by its name: https://www.checklistbank.org/dataset/1008/names?facet=rank&facet=issue&facet=status&facet=nomStatus&facet=nomCode&facet=nameType&facet=field&facet=authorship&facet=authorshipYear&facet=extinct&facet=environment&facet=origin&facet=sectorMode&limit=50&offset=0&q=Coluber%20novae%20hispaniae

It seems when a decision is added we are losing the issues for the usage when the search index is updated to contain the new decision

**Comment by mdoering** [comment]
fix deployed and works now. There might be old records that need an index update, please let me know if you encounter some
