### ISSUE TITLE
Bug: Downloads of data in dwca or coldp format only have name usages, lack references, etc.

### ISSUE THREAD

**Issue by rdmpage** [CatalogueOfLife/checklistbank#1408]
### Description

When I go to the download page for a dataset, e.g., https://www.checklistbank.org/dataset/1051/download and chose the default (`coldp`) I expect to get a file containing the files listed on [CATALOGUE OF LIFE DATA PACKAGE (COLDP)](https://www.catalogueoflife.org/about/colusage#data-formats) (or at least those for which the datset has the relevant data). 

But regardless of which dataset I try I'm only getting `metadata.yaml` and a names file (either `NameUsage.tsv` or `Taxon.tsv`). Where are the other files?

I've just noticed that I'm not getting the additional files for `dwca` either.

### What browsers are you seeing the problem on?

Safari

**Comment by mdoering** [comment]
That is expected as its the minimal form of a ColDP archive and many people are not interested in vernacular names etc which takes up unnecessary bandwidth and computing. To access the full data please select the `extended` flag.

**Comment by mdoering** [comment]
the same is true for DwC and TextTree btw

**Comment by rdmpage** [comment]
Wow, that's not what I would have expected! I would have expected to get all the data by default.

I hadn't paid much attention to this before as I would typically download the original archive as it often has more information, especially for references (which often don't seem to be correctly parsed).

IMHO the `extended` checklist box seems cryptic at best. Maybe instead have `coldp complete` and `coldp just names` as formats?

Anyway, thanks for clarifying.

**Comment by mdoering** [comment]
whatever it is called I just like to make sure the simple format is the default and people asking for all do it on purpose
