### ISSUE TITLE
Unable to select root taxon for download

### ISSUE THREAD

**Issue by nickynicolson** [CatalogueOfLife/checklistbank#1416]
On page https://www.checklistbank.org/dataset/1048/download

I type in a scientific name in the text box labelled "Choose root taxon (optional)". 
Hit return - nothing happens
Click the search icon - nothing happens
The message below the download button in the top right of the page remains at "No root taxon selected"

I can't see any way to specify the root taxon

**Comment by mdoering** [comment]
It works just fine for me if I type "Gera" I get an autocomplete to select the genus.
What browser are you on?

**Comment by nickynicolson** [comment]
Chrome 125.0.6422.142 (Official Build) (64-bit)

**Comment by nickynicolson** [comment]
OK it looks like its not possible to: 
(i) Paste in a name and have it recognised
(ii) Select a root taxon below the level of genus

**Comment by mdoering** [comment]
@thomasstjerne that could be expected? The suggest call has minRank=GENUS. We might want to lower that, but I would avoid species as they clutter the response quickly. So maybe `infrageneric name` would be best as its the lowest to still return uninomials like series.

Pasting `Geranium` works for me.

**Comment by nickynicolson** [comment]
Pasting a species name des not work
If input of ranks below genus is not supported then the interface should explain that.

**Comment by mdoering** [comment]
@thomasstjerne the export parameter `minRank` now seems to be overloaded.
When you select `species` for the root taxon search, it also gets included in the export request even though the `Exclude ranks below` selection is blank.
