### ISSUE TITLE
Show project release history

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/checklistbank#1417]
### Description

Similar to imports there should be a place to view the list of all past release attempts.
They are accessible the same way as imports are, e.g. for COL this is:

https://api.checklistbank.org/dataset/3/import?limit=5

Showing failed and successful release with their job name, i.e. what kind of release, links to the logs and successful release datasets would be very useful for managing a project.

**Comment by mdoering** [comment]
For the project release history the links shown for each release not all make sense:
https://www.checklistbank.org/dataset/3/imports

Depending on the type of "import", for a release or xrelease we should instead show as icon links:

 - link to release dataset downloads
 - kibana logs
 - release logs links, e.g. https://download.checklistbank.org/releases/{projectKey}/{attempt}/
 - browse tree

**Comment by thomasstjerne** [comment]
When a release was successful, we should have datasetKey for the new release available in these results: https://api.checklistbank.org/dataset/3/import?limit=5 

This can be used to point to the tree browser. For imports, we browse the TextTree archived version, but for releases we want to point to the release instead

**Comment by mdoering** [comment]
That would be good, agreed. But its a weirdly overloaded class and API resource intended originally for import results only. I don't see how I can easily add that. But there is another hardly known magic dataset key that allows to refer to a dataset by the combination of its projectKey and release attempt:

http://api.checklistbank.org/dataset/(projectKey}R{attempt}.json

So you can probably just link to:
https://www.checklistbank.org/dataset/3R261/about
