### ISSUE TITLE
Left menu gets stock with last dataset info

### ISSUE THREAD

**Issue by camiplata** [CatalogueOfLife/checklistbank#1419]
Left menu gets stock with last dataset info when navigating using the  editor's dataset list an traying to openthe COL project, trying to open other dataset works fine

https://github.com/CatalogueOfLife/checklistbank/assets/5700527/327ab200-5eda-4929-8fc3-360dc664a459

**Comment by thomasstjerne** [comment]
Thanks @camiplata 
Can you check if this bug still exists? 
I have deployed a fix that will likely have fixed this.
If the bug is still there, can you please paste a link to the affected page here for me to debug.

**Comment by camiplata** [comment]
It's fixed, thanks!!
