### ISSUE TITLE
Patch edition option leads to a blank page

### ISSUE THREAD

**Issue by camiplata** [CatalogueOfLife/checklistbank#1429]
For some datasets the Patch edition option leads to a blank page, 

Example dataset where the patch does NOT work: https://www.checklistbank.org/catalogue/3/dataset/29724/metadata
Example dataset where the patch does work: 
https://github.com/CatalogueOfLife/checklistbank/assets/5700527/009e2996-ad64-4f1e-92ba-1889fe294848

The video show how de patch does not work for some sources and for others does work.
https://github.com/CatalogueOfLife/checklistbank/assets/5700527/d918b6c8-b16a-4ebe-ad89-b31193c45f4f

From the newtwork console I get

> 
> Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7Bhttps%2C%20local%7D&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
>     React 10
>     unstable_runWithPriority scheduler.production.min.js:19
>     React 20
>     <anonymous> index.js:8
>     <anonymous> registerServiceWorker.js:114
>     <anonymous> registerServiceWorker.js:114

**Comment by DianRHR** [comment]
the same is happening on my side, in some cases it turns into a white page and it's imposible to modify the alias:
https://www.checklistbank.org/catalogue/3/dataset/7888/metadata
https://www.checklistbank.org/catalogue/3/dataset/7103/metadata
https://www.checklistbank.org/catalogue/3/dataset/25995/metadata

In other cases I was able to modify the alias in the patch: 
[speciesBE](https://www.checklistbank.org/catalogue/3/dataset/53133/metadata)
