### ISSUE TITLE
Issues not shown for COL releses

### ISSUE THREAD

**Issue by camiplata** [CatalogueOfLife/checklistbank#1432]
### Description

Issues aren't shown for releases from the COL project, but are shown for xreleases:

# releases
- https://www.checklistbank.org/dataset/298894/issues
- https://www.checklistbank.org/dataset/296511/issues

# xrelase
- https://www.checklistbank.org/dataset/298210/issues
- https://www.checklistbank.org/dataset/298754/issues

Related to #1426

**Comment by mdoering** [comment]
No issues exist for regular releases yet
