### ISSUE TITLE
CLB: problem with global ITIS sectors vs merged sectors

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/checklistbank#1435]
### Description

ITIS global sectors mixed up with "merged sectors" from the Extended Catalogue:
https://www.checklistbank.org/catalogue/3/sector?limit=100&offset=0&subjectDatasetKey=2144

How I can sync only global sectors from ITIS, if I have this situation on my screen:

![image](https://github.com/CatalogueOfLife/checklistbank/assets/28574252/adf799b8-9ea5-4921-8c63-4b0475840572)

**Comment by yroskov** [comment]
Related problem: Assembly tool shows all ITIS taxa as CoL sectors. as result, I am not able to establish or manage global sectors. I am simply cannot see "true" ITIS sectors in the right window (see https://github.com/CatalogueOfLife/testing/issues/8#issuecomment-2207227175).


https://www.checklistbank.org/catalogue/3/assembly?datasetKey=2144

![image](https://github.com/CatalogueOfLife/checklistbank/assets/28574252/cb5d5d60-8b2e-4d3c-86a7-62bfa793ad6e)

**Comment by camiplata** [comment]
Hi Yury, for your first question, you could [select only attach and union sectors](https://www.checklistbank.org/catalogue/3/sector?limit=100&mode=attach&mode=union&offset=0&subjectDatasetKey=2144)

<img width="897" alt="Captura de pantalla 2024-07-03 a la(s) 10 18 06 p m" src="https://github.com/CatalogueOfLife/checklistbank/assets/5700527/6c7d27f5-a670-4e83-9268-fac23e79413e">

**Comment by mdoering** [comment]
see https://github.com/CatalogueOfLife/testing/issues/8#issuecomment-2213358280
