### ISSUE TITLE
Feature: Do not display "merged sector" labels in the source GSD

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/checklistbank#1438]
### Description

Now CLB Assembly interface has very confusing presentation of "merged sectors" in the right window (GSD window):
_(example taken from ITIS)_

![image](https://github.com/CatalogueOfLife/checklistbank/assets/28574252/9f66aacf-ed14-4879-8b85-7c85169844ae)

https://www.checklistbank.org/catalogue/3/assembly?assemblyTaxonKey=oLOtrn1yY8dB70tmSv55E&datasetKey=2144&sourceTaxonKey=1204598

As you can see on the screenshot, all ITIS taxa beneath Animalia have a label "ITIS". This is very confusing, and makes difficult to manage global ITIS sectors for the CoL. 

_Suggested solutions:_ 

_Variant A._ Keep label only with the top taxon, and remove labels with children taxa:
![image](https://github.com/CatalogueOfLife/checklistbank/assets/28574252/869c1e77-1a88-46d8-ba44-41c3d2e504a0)

_Variant B._ Create different view of Assembly interface, where editor of Global CoL will not see "merged sector" labels.

**Comment by gdower** [comment]
If Animalia had both an attach sector and merge sector, would the sector display both the merge icon and the arrow icon of an attach sector? Maybe it would still be better to have a switch that removes the merge sectors like Markus proposed in the stand-up this morning, although by default it seems like it should be set to not show the merge sectors.

**Comment by mdoering** [comment]
You cannot create multiple sectors with the same subject, so it is impossible to have both an attach and merge sector.

**Comment by mdoering** [comment]
As we don't use the assembly tree for managing merge sectors I have simply excluded all these sectors from the tree view. They will show up in the project if they got synced on purpose, but we dont do that in COL and have prevented this to happen accidentally in the project options.

**Comment by mdoering** [comment]
Deployed to prod now:

<img width="1273" alt="image" src="https://github.com/user-attachments/assets/a6e422ed-a67e-456a-a815-13ae31e2490a">
