### ISSUE TITLE
GBIF Impact tool not showing all content

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/checklistbank#1439]
### Description

The report https://download.gbif.org/catalogueoflife/report-299581-2024-07-12-13-30-09.txt contains 29726 rows, but the [UI only shows 1040](https://www.dev.checklistbank.org/tools/gbif-impact?csv=report-299581-2024-07-12-13-30-09.txt&colKey=299581). 

The last row contains `Juniperus horizontalis` which you cannot search for.

**Comment by thomasstjerne** [comment]
The tsv seem invalid. Both the parser in the UI and Visual Studios CSV plugin reports this:
`Trailing quote on quoted field is malformed on line 1038`

**Comment by mdoering** [comment]
@djtfmartin any idea how this can happen?

**Comment by mdoering** [comment]
The problem is quotes in the TSV:
> "Candidatus Pelagibacter" Rappé, Connon, Vergin & Giovannoni, 2002

If you treat the TSV values always unquoted it is all fine. We don't need to quote tabs. But the UI library apparently does that and as the value starts with a single quote we're into trouble. Could the lib just split by tabs and not do more clever things?
