### ISSUE TITLE
Problems running async name matching

### ISSUE THREAD

**Issue by rvosa** [CatalogueOfLife/checklistbank#1440]
Hi,

I'm attempting to match a CSV file against the [async service](https://www.checklistbank.org/tools/name-match-async). I'm running into a few issues:

- Apparently I need to be logged in? This is not indicated clearly except that I get an Error 401.
- Upon being logged in and uploading a file, I am forwarded to an Error 404 page.

I appreciate you are very busy and a fix might not be trivial so I am merely flagging this.

All the best,

Rutger

**Comment by mdoering** [comment]
Yes, you need to be logged in to use any of the asynchroneous services like downloads or matching

**Comment by mdoering** [comment]
can you please share the file or a part of it that you used for the matching?
What exactly did you do to run the match, can you share a screenshot?

**Comment by mdoering** [comment]
@thomasstjerne logged new issue to require a login: https://github.com/CatalogueOfLife/checklistbank/issues/1441

**Comment by mdoering** [comment]
I have improved the matching documentation on the landing page: https://www.checklistbank.org/tools/name-match-async
