### ISSUE TITLE
I cannot access the workbench to make a decision on a xrelease name

### ISSUE THREAD

**Issue by camiplata** [CatalogueOfLife/checklistbank#1450]
### Description

[xrelease name to be blocked](https://www.checklistbank.org/dataset/300043/names?facet=rank&facet=issue&facet=status&facet=nomStatus&facet=nomCode&facet=nameType&facet=field&facet=authorship&facet=authorshipYear&facet=extinct&facet=environment&facet=origin&facet=sectorMode&facet=secondarySourceGroup&facet=sectorDatasetKey&facet=group&limit=50&offset=0&q=Amphipopon&sortBy=taxonomic)

<img width="900" alt="Captura de pantalla 2024-07-26 a la(s) 12 13 31 p m" src="https://github.com/user-attachments/assets/dca4c77a-4a40-4c85-8564-347f4792c74c">

<img width="900" alt="Captura de pantalla 2024-07-26 a la(s) 12 10 40 p m" src="https://github.com/user-attachments/assets/6cf43678-f672-4eef-a158-6e067aa2a6cf">

The process works fine if it is a base release name

**Comment by mdoering** [comment]
@camiplata you can use the workbench in the source for the time being

**Comment by thomasstjerne** [comment]
Didn´t we have `releasedFrom` in the releases once? https://api.dev.checklistbank.org/dataset/287559.json

I would need to point to the workbench in the project that the xrelease came from

**Comment by mdoering** [comment]
`sourceKey` it is called
