### ISSUE TITLE
Improve CLB genus interpretation to avoing creating false genus 

### ISSUE THREAD

**Issue by camiplata** [CatalogueOfLife/checklistbank#1453]
### Description

CLB interprets the genus when a binomial is given without a parent, nevertheless when it is not a real binomial like [Amphipyrinae sp.](https://www.checklistbank.org/dataset/7103/taxon/HE6DVQRXDFE)  CLB  creates a "wrong" genus. 
This could be avoided if the names including sp. where excluded from the genus interpretation.

<img width="1045" alt="Captura de pantalla 2024-08-05 a la(s) 8 47 49 p m" src="https://github.com/user-attachments/assets/5eaadbd8-88eb-47ab-8fa2-230c18138d0d">

<img width="1129" alt="Captura de pantalla 2024-08-05 a la(s) 8 49 27 p m" src="https://github.com/user-attachments/assets/abfaec9d-c260-4745-a1f7-dcb885988cc4">

**Comment by mdoering** [comment]
This does not happen any longer in the latest XR from 2024-11-02.
There is still some confusion about genera and families though, e.g. [Arctiinae](https://www.checklistbank.org/dataset/304954/taxon/KCPQZ) is added as a genus when it existed already as a subfamily.

I think plazi is wrong here in calling it a genus:
https://www.checklistbank.org/dataset/23866/taxon/03F0BE50FFD2FF82FF4AFF5FBCD0C3FE.taxon
