### ISSUE TITLE
Inconsistent total count of plazi datasets merged

### ISSUE THREAD

**Issue by camiplata** [CatalogueOfLife/checklistbank#1454]
### Description

The total amount of [merge plazi datasets](https://www.checklistbank.org/dataset/300563/sector?limit=100&offset=0&publisherKey=7ce8aef0-9e92-11dc-8738-b8a03c50a862) according to  CLB is 21, 025, nevertheless when checking the number of names merged for each of these datasets I found that there are 3782 datasets with 0 merged names. 

[plazi_merged_xr300043_zeroCounts.csv](https://github.com/user-attachments/files/16517058/plazi_merged_xr300043_zeroCounts.csv)

**Comment by mdoering** [comment]
I am not sure I understand the issue. Not all merge sectors are required to supply new names. Its perfectly valid to just cover already existing names.

**Comment by camiplata** [comment]
Yes, I expect the same. But even if they contribute to already existing names this should be counted as merged names/information.

For example [this dataset aparently](https://www.checklistbank.org/dataset/300563/sector?limit=100&offset=0&publisherKey=7ce8aef0-9e92-11dc-8738-b8a03c50a862&subjectDatasetKey=299641) contributed something to the xrelease (was merged), but when I want to check its contribution there is [nothing there ](https://www.checklistbank.org/dataset/300563/names?SECTOR_DATASET_KEY=299641&facet=rank&facet=issue&facet=status&facet=nomStatus&facet=nomCode&facet=nameType&facet=field&facet=authorship&facet=authorshipYear&facet=extinct&facet=environment&facet=origin&facet=sectorMode&facet=secondarySourceGroup&facet=sectorDatasetKey&facet=group&limit=50&offset=0&sortBy=taxonomic). So is this (and the other datasets) actually contributing to the xrelease? or is there information that is beeing merge that we canont find with the current search parameters?

**Comment by mdoering** [comment]
the sync history shows no (primary) records synced: https://www.checklistbank.org/catalogue/3/sector/sync?sectorKey=53940
We do not track secondary counts.

So to me this all looks correct. No sync counts, no search hits. What do you think is wrong?

**Comment by camiplata** [comment]
more detailed problem in  #1457
