### ISSUE TITLE
Is not posible to seearch merged datasets on the extended release

### ISSUE THREAD

**Issue by camiplata** [CatalogueOfLife/checklistbank#1458]
### Description

This feature worked two weeks ago, I have clear the cache and tested in firefox and chrome an the error persist:

<img width="1095" alt="Captura de pantalla 2024-09-03 a la(s) 9 55 56 a m" src="https://github.com/user-attachments/assets/ead7ac17-2600-4141-b302-185ca438a120">

I have to force the url to get the details of the names merged of any given dataset

example or "[forced"](https://www.checklistbank.org/dataset/301904/names?SECTOR_DATASET_KEY=52002&facet=rank&facet=issue&facet=status&facet=nomStatus&facet=nomCode&facet=nameType&facet=field&facet=authorship&facet=authorshipYear&facet=extinct&facet=environment&facet=origin&facet=sectorMode&facet=secondarySourceGroup&facet=sectorDatasetKey&facet=group&limit=50&offset=0&sortBy=taxonomic) url

**Comment by mdoering** [comment]
@thomasstjerne the UI uses `merge=false` in the dataset suggest:
https://api.checklistbank.org/dataset/301904/source/suggest?merge=false&q=BID-AF2015

If it would be using true it finds sources:
> https://api.checklistbank.org/dataset/301904/source/suggest?q=BID-AF2015&merge=true

In most places we should be including merge sources by default. But there might be places where Yuri needs to limit results to non merge sources. Might be best to just work with all sources for now until we better know

**Comment by mdoering** [comment]
works now
