### ISSUE TITLE
name match tool not matching (some times)

### ISSUE THREAD

**Issue by camiplata** [CatalogueOfLife/checklistbank#1459]
### Description

I was testing if some of the names reported on [this issue](https://github.com/CatalogueOfLife/xcol/issues/115) where present on the xrelease but found that some of those are reported as no-matching although they are indeed present:

For example Rhizamoeba polyura: 
Has no aparent match
<img width="700" alt="Captura de pantalla 2024-09-04 a la(s) 4 26 27 p m" src="https://github.com/user-attachments/assets/2bf7d622-2aaa-4127-a75e-b62b944a089a">

But is present on the [reference xrelease dataset](https://www.checklistbank.org/dataset/301904/taxon/D85ZV)

<img width="1224" alt="Captura de pantalla 2024-09-04 a la(s) 4 26 48 p m" src="https://github.com/user-attachments/assets/de6e71fc-f19e-4a44-8cc7-2adeb64e0b13">

Another example is Xeranobium badium

Match
<img width="700" alt="Captura de pantalla 2024-09-04 a la(s) 4 57 01 p m" src="https://github.com/user-attachments/assets/20601ff0-74cc-48d4-bc3e-b8458498307e">

name in xrlease: https://www.checklistbank.org/dataset/301904/taxon/DCYMT

### What browsers are you seeing the problem on?

Firefox

### ChecklistBank URL

https://www.checklistbank.org/tools/name-match

**Comment by mdoering** [comment]
maybe you did not match against the XRelease? Works for me:

<img width="1107" alt="image" src="https://github.com/user-attachments/assets/8ee2a135-5c76-4b8d-b3a3-4249e089de20">

**Comment by camiplata** [comment]
yep, my bad :/
