### ISSUE TITLE
CLB: search box for Sector does not work for CoL project

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/checklistbank#1463]
### Description

Search box for Sector at https://www.checklistbank.org/catalogue/3/sector?limit=100&offset=0 does not allow me to see/choose WoRMS sectors. It is packed with BD & PLZ sources, there is no any single entry for WoRMS: 
![image](https://github.com/user-attachments/assets/40d30b4f-2584-444c-8515-f34fd5b8dba2)

### ChecklistBank URL

https://www.checklistbank.org/catalogue/3/sector?limit=100&offset=0

**Comment by mdoering** [comment]
@thomasstjerne we need to populate the merge parameter. Either add a checkbox next to the search form like we do elsewhere or use the sector mode selection. If no merge is selected do `merge=false`, otherwise when merge is selected do `merge=true`.  The default is now to include merge sources.
