### ISSUE TITLE
while using search boxes across  CLB I'm getting blank pages

### ISSUE THREAD

**Issue by camiplata** [CatalogueOfLife/checklistbank#1465]
example when adding a sector

https://github.com/user-attachments/assets/ced143a1-1f57-4086-8693-75d8729033a6

**Comment by thomasstjerne** [comment]
Does this still apply?
I can´t reproduce the error

**Comment by thomasstjerne** [comment]
Hi again
I tried in Firefox, and it works perfectly.
Would you be able to open "developer tools" and see what the console says?

**Comment by camiplata** [comment]
<img width="1137" alt="Captura de pantalla 2024-09-13 a la(s) 8 50 48 a m" src="https://github.com/user-attachments/assets/3553903f-3970-428a-b260-5a347994da87">

Warnings in English:

- The layout was forced before the page was fully loaded. If stylesheets are not yet loaded, this may cause a flash of unstyled content.

- This page uses the non-standard “zoom” property. Consider using calc() on the relevant property values, or using “transform” together with “transform-origin: 0 0”.

- Cross-Origin Request Warning: The same-origin policy will soon disallow reading of the remote resource at https://download.checklistbank.org/.status.json?cachebust=0.8125587652563329. (Reason: When `Access-Control-Allow-Headers` is `*`, the `Authorization` header is not included. To include the `Authorization` header, it must be explicitly listed in the `Access-Control-Allow-Headers` CORS header.)

- Cross-Origin Request Warning: The same-origin policy will soon disallow reading of the remote resource at https://download.checklistbank.org/.status.json?cachebust=0.3966315211420395. (Reason: When `Access-Control-Allow-Headers` is `*`, the `Authorization` header is not included. To include the `Authorization` header, it must be explicitly listed in the `Access-Control-Allow-Headers` CORS header.)


<img width="1509" alt="Captura de pantalla 2024-09-13 a la(s) 8 43 53 a m" src="https://github.com/user-attachments/assets/fed1a079-6b7f-49c6-944b-749ed4b9a820">

TypeError: this.state.datasets.map is not a function
    render DatasetAutocomplete.js:119
    React 7
    unstable_runWithPriority scheduler.production.min.js:19
    React 6
    getDatasets DatasetAutocomplete.js:82
    promise callback*rx/this.getDatasets DatasetAutocomplete.js:81
    Lodash 8
    onSearch Select.js:426
    Ie BaseSelect.js:200
    C index.js:81
    onInputChange index.js:106
    onChange SingleSelector.js:82
    onChange Input.js:77
    onChange Search.js:53
    onChange Input.js:162
    u commonUtils.js:56
    G Input.js:87
    React 12
    unstable_runWithPriority scheduler.production.min.js:19
    React 13
    unstable_runWithPriority scheduler.production.min.js:19
    React 5

**Comment by thomasstjerne** [comment]
Thanks - this will be useful for further debugging

**Comment by thomasstjerne** [comment]
@camiplata Can you check if the problem still exists?
