### ISSUE TITLE
Bug: Parent mismatch issue shows names without that error

### ISSUE THREAD

**Issue by DianRHR** [CatalogueOfLife/checklistbank#1466]
### Description

In the private dataset [Coleoptera type genera and family-group names](https://www.checklistbank.org/dataset/290628/about) I am generating, I got 282 names with the issue `Parent Name Mismatch`. I checked randomly 10 cases and any of them has any problem  (check Verbatim). However, I can't understand why is this issue showing in those specific names. 

### What browsers are you seeing the problem on?

Chrome

### ChecklistBank URL

https://www.checklistbank.org/dataset/290628/names?facet=rank&facet=issue&facet=status&facet=nomStatus&facet=nomCode&facet=nameType&facet=field&facet=authorship&facet=authorshipYear&facet=extinct&facet=environment&facet=origin&facet=sectorMode&facet=secondarySourceGroup&facet=sectorDatasetKey&facet=group&issue=parent%20name%20mismatch&limit=50&offset=0

**Comment by mdoering** [comment]
In the interpreted view the species are placed in the wrong genus, e.g.
[Acanthocerus aeneus](https://www.checklistbank.org/dataset/290628/taxon/6011) in [Ceratocanthus](https://www.checklistbank.org/dataset/290628/taxon/838)

The [verbatim](https://www.checklistbank.org/dataset/290628/verbatim/14222) shows both `parentID=17` and flat classification fields like `genus=Acanthocerus`.
In such cases the importer always prefers the parentID as this is more reliable and ignores all flat fields (which should probably be removed from the dataset for simplicity).

[Usage 17](https://www.checklistbank.org/dataset/290628/verbatim/4721) is Acanthocerus, but it is considered a synonym which can never be a parent in a classification. Hence it has the issue `synonym parent` and in turn links to [usage 838](https://www.checklistbank.org/dataset/290628/verbatim/8238) as the accepted taxon - which is the accepted genus Ceratocanthus which is finally used.

I'd recommend to:
 - remove flat classification fields
 - only link to accepted taxa via parentID, never to any synonym

The dataset has an issue with accepting species in a genus which is considered a synonym though. Not sure if you wanted that.

**Comment by mdoering** [comment]
Please use the backend repo for all importing issues in the future, checklistbank is just the frontend.
