### ISSUE TITLE
Question: was behaviour of decision application changed recently?

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/checklistbank#1468]
### Description

_Following our discussion during stand up..._ (@thomasstjerne @mdoering @olafbanki) 

While working on the TITAN report last week, I suspect that the CLB behavior when applying a decision has changed. during last week, I suspects that CLB behaviour on decision application was changed. (https://www.checklistbank.org/catalogue/3/dataset/1032/duplicates?acceptedDifferent=true&authorshipDifferent=true&catalogueKey=3&category=binomial&limit=100&minSize=2&mode=STRICT&offset=0&status=accepted&status=synonym)

My impression of "old style": if I need to change a decision with a name, I should first kill previous decision by clicking on cancellation cross, 
![image](https://github.com/user-attachments/assets/d1ce75ee-5662-47a1-82e4-27a780833501)
then, I should apply a new decision.

My impression of "new style": if I need to change decision with a name, I can check the box and apply the new decision without cancelling previous decision
![image](https://github.com/user-attachments/assets/6f139dc5-7095-4f1b-8fe1-6185e74a1d09)
then, the new decision will overwrite the previous one.

**Is this correct?**

**Comment by mdoering** [comment]
I am not aware of a change for a long time in this area. @thomasstjerne ?
