### ISSUE TITLE
Patched aliases aren't showing

### ISSUE THREAD

**Issue by camiplata** [CatalogueOfLife/checklistbank#1476]
### Description

Patched aliases aren't showing, the full dataset name is used on the priority list,  and the sector id on the tree:

Examples:

Patched Alias
![Image](https://github.com/user-attachments/assets/f271fc2f-1a2d-4e62-ae43-031728ce7e04)

Sector id shown instead of the patched alias
![Image](https://github.com/user-attachments/assets/fa0ab9ba-e1b7-424b-ace9-de352fa0ba29)

Full name shown instead of the patched alias
![Image](https://github.com/user-attachments/assets/345d0c96-ffd8-41dc-a04c-cde762cce48d)

**Comment by mdoering** [comment]
@thomasstjerne can you please take a look? At least in the release the alias is present in the source dataset:

https://www.checklistbank.org/dataset/304443/source/5552
https://api.checklistbank.org/dataset/304443/source/5552

It seems the tree loads the dataset metadata from the main dataset, not the release/project source!
https://www.checklistbank.org/dataset/304443/classification?taxonKey=D3Y7W
-> https://api.checklistbank.org/dataset/5552
