### ISSUE TITLE
Bug: white screen appears when browsing tree in latest xrelease

### ISSUE THREAD

**Issue by DianRHR** [CatalogueOfLife/checklistbank#1477]
### Description

It only happens on the dataset of the latest [xrelease ](https://www.checklistbank.org/dataset/304591/classification) while using the "Browse" option, however it only occurs in some names. 
Example: browsing Animalia | Arthropoda | Hexapoda | Insecta | Coleoptera | Elateroidea | Elateridae ... and there appears a white screen like this: 
![image](https://github.com/user-attachments/assets/98eeb211-509b-432e-891f-2caa81b8041b)

But it browse properly in Animalia | Arthropoda | Hexapoda | Insecta | Coleoptera | Elateroidea | Iberobaeniidae ... down to the species level. 

### What browsers are you seeing the problem on?

Chrome, Microsoft Edge

### ChecklistBank URL

https://www.checklistbank.org/dataset/304591/classification?taxonKey=C9LMN

**Comment by thomasstjerne** [comment]
I will do better error handling for this in the UI. But I think it occurs due to inconsistent data, i.e. the source is missing:
https://api.checklistbank.org/dataset/304591/source/292056

The UI expects that the source can always be derived from the sector.
Might be sth to look into @mdoering

**Comment by mdoering** [comment]
Strange. Cant get the VPN to work, but I will look into this tomorrow. It clearly should not be like that

> Investigation on possible transmission of monkeys' Plasmodium to human in a populations living in the equatorial rainforest of the Democratic republic of Congo

**Comment by DianRHR** [comment]
It's strange, the source [292056 ](https://www.checklistbank.org/dataset/292056/about)has nothing to do with the beetle family of Elateridae ... 

And the white page appears when browsing in different groups. 

This is another example , when trying to browse into [Chlorophyta](https://www.checklistbank.org/dataset/304591/classification?taxonKey=CGV7L): 
![image](https://github.com/user-attachments/assets/87de1b1b-c48f-4483-b615-ce30b4d9619f)

**Comment by thomasstjerne** [comment]
Some more examples of missing sources for debugging.

When accessing the exple from @DianRHR https://www.checklistbank.org/dataset/304591/classification?taxonKey=CGV7L 
The following calls to sources gives 404s:

https://api.checklistbank.org/dataset/304591/source/4331
https://api.checklistbank.org/dataset/304591/source/52075
https://api.checklistbank.org/dataset/304591/source/7707

**Comment by mdoering** [comment]
Finally I know whats going. All these sources come from a configured publisher for which we only provide aggregated metadata!

@thomasstjerne It seems we need to offer both aggregated sources for the metrics and source lists, but also individual source metadata to link to from data & the tree?

**Comment by thomasstjerne** [comment]
Yes. The tree needs to be able to get at least the title and alias through calls like: https://api.checklistbank.org/dataset/304591/source/7707

This issue came up when I swapped urls according to https://github.com/CatalogueOfLife/checklistbank/issues/1476#issuecomment-2421563182

**Comment by mdoering** [comment]
Plazi sources exist now in the latest XR: https://www.checklistbank.org/dataset/304954/classification?taxonKey=K9YBC
