### ISSUE TITLE
updated license list when creating a new dataset on CLB

### ISSUE THREAD

**Issue by camiplata** [CatalogueOfLife/checklistbank#1492]
Keep only the licenses that CLB we will support

CC0, CCBY and  CC BY NC? (@mdoering could you confirm? if this last one, is IT going to be allowed to?)

<img width="516" alt="Captura de pantalla 2024-11-12 a la(s) 2 18 49 p m" src="https://github.com/user-attachments/assets/cb9861f4-5a73-4649-b062-8393dfd234db">

**Comment by mdoering** [comment]
I don't clearly remember we said CLB only wants to support those 3 licenses. Did we? In that case I would consider to remove them from the API entirely and only leave unspecified and other? Or not even that and enforce the use of the 3? We will only sync datasets from GBIF with one of the 3 licenses. We can enforce that license exists when creating a new dataset via the API, e.g. for plazi and also the UI. Maybe we then even do not need `other` or `unspecified`?

 - 0 ccbynd [datasets](https://www.checklistbank.org/dataset?license=ccbynd&limit=50&offset=0&origin=external&origin=project)
 - 1 ccbysa [dataset](https://www.checklistbank.org/dataset?license=ccbync&limit=50&offset=0&origin=external&origin=project): Fauna Europaea. I dont think that is correct any longer
 - 9 unspecified [datasets](https://www.checklistbank.org/dataset?license=ccbync&limit=50&offset=0&origin=external&origin=project), mostly all private dev ones
 - 0 ccbyncsa [datasets](https://www.checklistbank.org/dataset?license= ccbyncsa&limit=50&offset=0&origin=external&origin=project)
 - 3 ccbyncnd [datasets](https://www.checklistbank.org/dataset?license=ccbyncnd&limit=50&offset=0&origin=external&origin=project): Mycobank

**Comment by mdoering** [comment]
As a first step I will remove all the ND and SA ones from the API, but keep unspecified and other for now.
@thomasstjerne can we change the UI please to only allow the 3 good licenses to be used when creating a new dataset?
