### ISSUE TITLE
Bug: Sectors tool does not work in CLB

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/checklistbank#1502]
### Description

Trying to re-sync WoRMS Ostracoda (or any other GSD) on 2024-11-21, I have got the message **Request failed with status code 500**:

![image](https://github.com/user-attachments/assets/d69db8cb-47b9-4894-8ac2-cc4ea5477a91)

### What browsers are you seeing the problem on?

Firefox

### ChecklistBank URL

https://www.checklistbank.org/catalogue/3/sector?limit=100&offset=0&subjectDatasetKey=1175

**Comment by mdoering** [comment]
fixed

**Comment by mdoering** [comment]
sync running now

**Comment by yroskov** [comment]
Thanks! Working now. 

Credits to GSD are also back now in the portal.
