### ISSUE TITLE
Show user info

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/checklistbank#276]
For logged in users we should provide a way to show the user information like name, email, roles etc. Or at least link to the GBIF portal user info.

see https://github.com/Sp2000/colplus-backend/issues/416#issuecomment-517214653

**Comment by mdoering** [comment]
There should also be a list of all linked datasets a user has editorial or review rights to.

**Comment by thomasstjerne** [comment]
It should be possible to use a `reviewer` param like the `editor` one:
https://api.dev.catalogueoflife.org/dataset?reviewer=117

In all normal cases I could just use the users array of datasetKeys (editor/reviewer) but the GBIF Sync user have so many that paging is needed.

**Comment by mdoering** [comment]
I'll remove the GBIF Sync users array - its a bot where it doesnt make much sense. Same for importer and a few others

**Comment by mdoering** [comment]
@thomasstjerne can we add the link to the dataset search for editor and reviewer roles in the admin table? 
And for a logged in user show a link to his datasets from the user info/login?

**Comment by thomasstjerne** [comment]
I was considering show users datasets when a user row is expanded in the dataset section?
