### ISSUE TITLE
URN as taxonID breaks

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/checklistbank#395]
PoWo `urn:lsid:ipni.org:names:30000422-2` returns a 404 if used with url encoding:
https://www.col.plus/dataset/2001/taxon/urn%3Alsid%3Aipni.org%3Anames%3A30000008-2

**Comment by thomasstjerne** [comment]
Still breaks: https://data.catalogue.life/dataset/2001/taxon/urn%3Alsid%3Aipni.org%3Anames%3A30001654-2

See https://github.com/CatalogueOfLife/deploy/issues/10
