### ISSUE TITLE
show taxon/name link URL

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/checklistbank#41]
A plain name, taxon or synonym can have a `link` property that takes a URL to its "homepage" in the original source. Show that link on a taxon/synonym/bare names page

**Comment by thomasstjerne** [comment]
For the `name` entity, is this a replacement for `sourceUrl` or are both valid?

**Comment by mdoering** [comment]
sourceUrl does not exist in the API now, but probably link was sourceUrl before at some stage.
