### ISSUE TITLE
Add user management interfaces

### ISSUE THREAD

**Issue by gdower** [CatalogueOfLife/checklistbank#439]
In the admin panel, it would be helpful to be able to see if a user is registered, their name, their user ID, and their access level permissions for each catalogue dataset. This isn't urgently needed because I can figure it out from the API.

A user management interface is also needed in the dataset section for catalogues (or "managed datasets") as well, because a user might be an editor of one catalogue but not all of the other catalogues in the clearinghouse. There might also need to be another role that allows a user to add or remove users of their catalogue, or possibly the dataset creators would only be allowed to manage users?

**Comment by mdoering** [comment]
The [backend implements now dataset scoped editor permissions](https://github.com/CatalogueOfLife/backend/issues/580#issuecomment-611399405) which we need to manage in the UI. This becomes an important feature now.

In general we still rely on the GBIF registry to manage users and users can change their personal information there. What is missing though is dataset permissions and user settings. User settings are not used currently by the UI AFAIK.

To manage dataset permissions the UI should:

 - [ ] new Editors menu under project & dataset that list all users with editor role and permission to modify the dataset
   - allow to add new editors by searching for an existing username
   - allow to remove a listed editor 
 - [ ] new User menu under Admin that 
   - lists all users and offers a filter by role, username & dataset
   - allows to modify a users role set and dataset permissions (add/remove)
 - [ ] Show user info incl role & dataset permissions, see #276

**Comment by mdoering** [comment]
API methods available to manage users and dataset rights:

 - `GET /user?q=query` search
 - `GET /user/{userKey}` get obfuscated user by key
 - `GET /user/me` get full currently logged in user
 - `GET /user/dataset` list datasets user has editor rights for
 - `PUT /user/{userKey}/role` `['ADMIN', 'EDITOR']` update users role with provided list
 - `GET /dataset/{datasetKey}/editor` list editors for dataset
 - `POST /dataset/{datasetKey}/editor` `{userKey}` add user to list of editors
 - `DELETE /dataset/{datasetKey}/editor/{userKey}` remove userKey from editors of dataset

**Comment by mdoering** [comment]
for the admin part of the UI it would be good to also see:
 - the user key as its the one that is used in the API everywhere
 - all roles (ADMIN, EDITOR, REVIEWER) - either as 3 columns that can be filtered on?
 - for editor and reviewer also the links to all the datasets they have access to. Maybe this could be done as a row that can be opened (+) and which is rendered only on demand as this list could be really large?

**Comment by mdoering** [comment]
When a user is added to a dataset as editor or reviewer it automatically gains this role if it doesnt have it yet. There is no need to first add the role then the dataset key.

**Comment by mdoering** [comment]
When a role is revoked, e.g. EDITOR, all the datasets the editor is linked to are also removed. So this needs to be used with care.

**Comment by mdoering** [comment]
There should also be a flag that can be toggled to deactivate a user - a way to block spammers quickly.
I will add a new field blocked which contains the timestamp when the user was blocked and a new method to block/unblock a user:
`PUT /user/{userKey}/block` `true/false`

**Comment by mdoering** [comment]
See also #276, maybe a shared component would work to show user infos?

**Comment by thomasstjerne** [comment]
> There should also be a flag that can be toggled to deactivate a user - a way to block spammers quickly. I will add a new field blocked which contains the timestamp when the user was blocked and new methods to block/unblock a user: `POST /user/{userKey}/block` blocks a user `DELETE /user/{userKey}/block` unblocks a user

Does users have a flag `blocked: true` or similar?

**Comment by mdoering** [comment]
the blocked property is actually a datetime like created
