### ISSUE TITLE
Add ES admin page with dataset stats

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/checklistbank#452]
Add a new `elasticsearch` admin menu item that holds all ES related admin buttons/actions and a simple table that lists all datasets and compares their last successful import metrics with actual counts in ES:

`dataset title | last success attempt | last success import date | import total | import bare names | import taxa | import synonyms | ES total | ES bare names | ES taxa | ES synonyms
`
and colors datasets with a mismatch between the two red.

**Comment by mdoering** [comment]
plus a button to reindex a specific dataset

**Comment by mdoering** [comment]
values for ES total | ES bare names | ES taxa | ES synonyms would probably be best taken from a search facet on the taxonomic status of a dataset

**Comment by ayco-at-naturalis** [comment]
Ah thanks!
