### ISSUE TITLE
Show type material on taxon & names page

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/checklistbank#466]
[Type Material](https://github.com/Sp2000/colplus-backend/blob/master/colplus-api/src/main/java/life/catalogue/api/model/TypeMaterial.java#L11) now exists as an entity on its own. Please show it on the taxon and name details pages:

**Taxon**
The [TaxonInfo](https://github.com/Sp2000/colplus-backend/blob/master/colplus-api/src/main/java/life/catalogue/api/model/TaxonInfo.java#L20) object now has a map `typeMaterial ` of type `nameID --> List<TypeMaterial>`. It is keyed on the nameID so the UI can quickly lookup the types for a given name (taxon.name or any of the synonyms).

Show a types material icon next to each name if any data exists, similar to references.

Discuss how to best present the types. As homotypic names are based on the same types and we recommend only to link types to original names, types should ideally only be shown for original names.

**Name**
The API has a new method `/name/{KEY}/types` to list all types for a given name.

The [ColDP examples dataset](https://github.com/Sp2000/coldp/blob/master/data/type-material.tsv) contains 3 types to test with.

**Comment by mdoering** [comment]
Not all type information seems to be shown. This IPNI type 
https://api.dev.checklistbank.org/dataset/144889/name/77126065-1/types

Only shows as [Holotype](https://www.dev.checklistbank.org/dataset/144889/taxon/77126065-1) but lacks information on date, collector, locality & remarks

**Comment by mdoering** [comment]
It would be nice to follow the [EJT material_citations_formatting_guide](https://github.com/CatalogueOfLife/checklistbank/files/8679088/EJT.material_citations_formatting_guide.pdf) recommendation on how to present material citations. 

> The preferred order of data fields is as follows:
COUNTRY • specimen(s) [e.g. “1 ♂”]; geographic/locality data [from largest to smallest]; geographic coordinates; altitude/elevation/depth [using alt. / elev. / m a.s.l. etc.]; date [format: 16 Jan. 1998]; collector [followed by “leg.”]; other collecting data [e.g. micro habitat / host / method of collecting / “DNA voucher specimen”/ “vial with detached elements”, etc.]; barcodes/identifiers [e.g. “GenBank: MG779236”]; institution code and specimen code [e.g. “CBF 06023”].


Example:
<img width="788" alt="image" src="https://user-images.githubusercontent.com/327505/168077278-d6aeef88-6e62-45da-8f91-3f2eababa252.png">

We don't have all fields yet in our model, but we will extend it in the near future:
https://github.com/CatalogueOfLife/coldp/issues/64

**Comment by thomasstjerne** [comment]
The UI shows only the `type` and the `citation` string - I kind of assumed that it would be generated by the backend.

**Comment by mdoering** [comment]
I guess I could built it - preferrably not with any html. Makes sense, it's similar to references and taxon labels I suppose.

**Comment by mdoering** [comment]
I have tried to parse the coordinates into decimal values - would it make sense to render to tiny map thumbnail or the globe like we do on [gbif events](https://www.gbif.org/dataset/740df67d-5663-41a2-9d12-33ec33876c47/event/0f3a2fce-3425-4db9-a720-430307aeb8e7)?

**Comment by thomasstjerne** [comment]
That would be great

**Comment by mdoering** [comment]
deployed to prod, seems to work fine
