### ISSUE TITLE
In assembly show only sources with data

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/checklistbank#560]
The sources menu should restrict datasets to the ones which have data.
At least for manual selection. If you enter the page with a link from a sector for example we should warn users that this sector does not have any data yet.

I will add a new dataset search parameter `minSize` to restrict results to datasets with at least the given size.

**Comment by mdoering** [comment]
[minSize parameter existing](https://github.com/CatalogueOfLife/clearinghouse-ui/issues/566)

**Comment by thomasstjerne** [comment]
Do you mean that menu?
<img width="409" alt="Screenshot at Aug 12 16-34-07" src="https://user-images.githubusercontent.com/1666484/129215710-92f74928-7369-4ac4-9157-bb0d530a869f.png">

**Comment by mdoering** [comment]
No, the right pane on the assembly tree: https://data.catalogueoflife.org/catalogue/3/assembly
