### ISSUE TITLE
Source dataset metadata patch forms

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/checklistbank#573]
As discussed in https://github.com/CatalogueOfLife/backend/issues/689 there is the need for a project to override dataset metadata for its sources. These *patches* should work similar to decisions that they stay around and get applied to the latest source metadata when a release is created. Dataset metadata patches only partially patch a dataset on a field to field basis, allowing them also to set a field to NULL if needed.

Displaying the patch with the current metadata in the UI needs some thinking. It would be good if its close to the regular dataset metadata UI and we simply adapt the dataset metadata page under the project view. I could imagine an interface that displays the current source dataset metadata similar to the regular page, highlighting where the patch was applied and maybe even warns if the original data differs. Modifying the patch data would then show +/- the regular metadata form but only with the patch data, keeping any other fields empty. We should try to only show real metadata and no settings, keys etc. 

Alternatively we could show the current dataset and the patch dataset next to each other in a table?

@thomasstjerne What API methods would be needed to do this effectively? I was thinking of having a project scoped CRUD service at `/dataset/{projectKey}/patch/{sourceDatasetKey}` that mostly returns a map. But we could also return a dataset instance for the patch only. Using the dataset would introduce a few constraint checks we might not want to see, e.g. a non null title. But I might be able to work around these

**Comment by thomasstjerne** [comment]
a project scoped CRUD service at `/dataset/{projectKey}/patch/{sourceDatasetKey}` will do.
And the schema for the patch should be identical to that of the plain dataset meta.

Basically a full decision on dataset meta.

**Comment by mdoering** [comment]
But then there is no way to declare that a property should be NULL. Or is there?
And there is no sense in deciding on settings, private flag, gbif key and many more.
Can we mark and use only those properties which are considered human metadata?

Otherwise thats very fine with me.

**Comment by mdoering** [comment]
I would suggest to slightly clean up the metadata UI as in the screenshot below.
This would group the true metadata logically in one section that can be edited for the patch.

<img width="1772" alt="Screenshot 2020-04-27 at 15 28 36" src="https://user-images.githubusercontent.com/327505/80378459-fe3e6880-889c-11ea-8b1e-f3d89997e73f.png">

**Comment by thomasstjerne** [comment]
Sure, it can be a reduced field set. 
An attribute in the patch could be set to NULL / Empty string when creating / updating. But then they should also be in the response when GETting it back from the server.

**Comment by mdoering** [comment]
sth like that:
![dataset proposal](https://user-images.githubusercontent.com/327505/80381498-4d869800-88a1-11ea-82fb-1b9f96ef586f.jpg)

**Comment by mdoering** [comment]
The ideal solution would show the latest dataset metadata together with the patch.
A side by side view should work, original metadata on the left, patch on the right. Colored if the patch differs?

Or maybe a single merged view highlighting the fields which are modified by the patch?

**Comment by mdoering** [comment]
I could add a raw=true param to the source endpoint to get the unpatched version. Might be good to show that in the form view. In the regular view its best to see the patched version already!
