### ISSUE TITLE
Show project releases and/or metrics

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/checklistbank#647]
> This dataset has never been released.
https://data.catalogue.life/dataset/3/imports

There are releases, but it seems the page is the import page that is trying to list imports?
Releases should be a separate page

**Comment by mdoering** [comment]
alternative option to show releases here: https://github.com/CatalogueOfLife/clearinghouse-ui/issues/640

I would suggest to follow #640 and just show a link, date and count in metadata.

**Comment by thomasstjerne** [comment]
But at some point there was metrics for the release here: https://api.catalogue.life/dataset/3/import?limit=20
Did the endpoint for that change?

**Comment by mdoering** [comment]
I am not sure what the page tries to show. The URL is called imports, so I guess its supposed to show the import metrics. The project itself does not have import metrics unless you have imported archives, e.g. via uploads.

Every release does have a single metric. But that belongs to the released dataset key, not the mother project.

If I understand the intentions correctly I would suggest to:
 - stick with the regular import metrics page also for projects so you can follow uploads
 - add the 2 links mentioned in #640 to the metadata page

**Comment by thomasstjerne** [comment]
Ok. I must have misunderstood this one: https://github.com/CatalogueOfLife/clearinghouse-ui/issues/513

**Comment by mdoering** [comment]
Ah yes. Just the generated metrics are for the release, not the master project.
For a single release we do show the metrics correctly: https://data.catalogue.life/dataset/2140/imports

I never know whether "Imports" or "Metrics" is a better title for the page

**Comment by thomasstjerne** [comment]
But if we should be able to track history/changes I would suggest that this call: https://api.catalogue.life/dataset/3/import?limit=20 
returned the metrics for all releases of dataset 3
Endpoint could maybe /release instead for more intuitiveness

Then you would have a nice release history here: https://data.catalogue.life/dataset/3/imports

Of course I can change the url to /dataset/3/releases so it align with the menu text.

Otherwise I could show a list of released datasets from where you could click to their respective release metrics - but that wouldn´t be the best workflow

**Comment by mdoering** [comment]
That makes sense. But what about plain imports like uploads? Should we ignore those for managed datasets? Or we indeed create new release endpoints both on API and UI which seems to make also more sense semantically

**Comment by mdoering** [comment]
As releases are different datasets the regular diff API does not work as it expects the same datasetKey or sectorKey. But with a new releases endpoint we could also create such a diff tool to show changes between releases - which sounds actually more interesting then between imports.
