### ISSUE TITLE
Posting to reference endpoint creates an empty reference

### ISSUE THREAD

**Issue by gdower** [CatalogueOfLife/checklistbank#754]
This might be a frontend bug, because I'm sending the same request that the frontend sends and maybe the request is wrong, but when posting the following, the reference is created but is empty:

POST /dataset/3/reference
```JSON
{
   "type":"personal_communication",
   "title":"Species estimates based on World Ferns data (personal comment).",
   "author":[
      {
         "family":"M.",
         "given":"Hassler"
      }
   ],
   "issued":{
      "date-parts":[
         "2019",
         "04",
         "21"
      ]
   },
   "accessed":{
      "date-parts":[
         "2019",
         "04",
         "21"
      ]
   }
}
```
9d511e85-343a-4096-bcd4-b8c6a37f3b79

GET https://api.catalogue.life/dataset/3/reference/9d511e85-343a-4096-bcd4-b8c6a37f3b79
```JSON
{
  "created": "2020-10-26T15:13:22.705672",
  "createdBy": 103,
  "modified": "2020-10-26T15:13:22.705672",
  "modifiedBy": 103,
  "datasetKey": 3,
  "id": "9d511e85-343a-4096-bcd4-b8c6a37f3b79",
  "parsed": false
}
```

**Comment by mdoering** [comment]
I just see that there is a 2nd POST create method using a different content-type `application/vnd.coldp+json` that accepts a _ColDP_ reference:

```
citation
author
title
year
source
details
doi
link
remarks
```

This might be what the frontend is calling.
It behaves just as the importer would do for a ColDP reference record.

**Comment by mdoering** [comment]
The issues, author and accessed fields you mentioned in your issue look like CSL-JSON though

**Comment by mdoering** [comment]
and there is a 3rd option that allows to POST CslData directly when using the content-type `application/vnd.citationstyles.csl+json`. That should do what you intended.

**Comment by mdoering** [comment]
I will modify the API to throw a 400 bad request if the reference is empty

**Comment by gdower** [comment]
Yeah the 2nd post method above will work for my purposes of fixing the estimates. But add new reference in the frontend fails because it uses the 1st example above:

https://data.catalogue.life/catalogue/3/references?limit=50&offset=0

**Comment by thomasstjerne** [comment]
Ok I see, the csl object should be nested.
But I actually thought that `citation` would be then gererated by the backend based on the Csl. Similar to the name/label attrs of organisations and persons.
Since it is retrievable from the Csl, and you can have different preferred formats of the `citation` string, but these different formats should be achievable from the Csl parts.

Of course the frontend could try to produce the desired `citation` format from Csl - but isn´t that better done in the backend?

**Comment by mdoering** [comment]
`citation` will be generated if you just supply the CSL or coldp properties

**Comment by thomasstjerne** [comment]
Super, then its an easy fix

**Comment by thomasstjerne** [comment]
Indeed, the content-type configuration was commented out for some reason
