### ISSUE TITLE
Interface for managing metadata inside the project (suggestion)

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/checklistbank#755]
This is a mockup for metadata patch management template:
(only few fields present as an example) 

![image](https://user-images.githubusercontent.com/28574252/97368358-bcf13a80-1878-11eb-866f-bf3bc56d66b4.png)

Please try to keep fields in Authors/Editors and Organisation groups expanded (i.e. do not collapse them in aggregated, non-editable view).

**Comment by yroskov** [comment]
For @thomasstjerne 

Being inside the project,
1) editor need to see metadata in their fields side by side: imported metadata vs CoL metadata
2) editor need to be able to copy&paste metadata from "raw side" to fields in a project view
3) editor need to edit data in a patch
4) editor need to be able to lock fields with patch view
5) editor need to be able to save data in a patch. Patched data in locked fields should not be replaced with raw metadata during sync. 
6) Patch for metadata should stay unchanged through all imports and be applied as it is with each sync until next editorial work.

**Comment by mdoering** [comment]
Can you explain the lock idea in detail? In your example it is used with values and without.

**Comment by mdoering** [comment]
Note also that a patch cannot work on parts of an organisation or author list. Either you patch the entire list or you dont. You cannot change a single organisation only. So the lock can only be at the organisations field level

**Comment by mdoering** [comment]
Metadata is also untouched in a sync. That happens at release time

**Comment by mdoering** [comment]
A patch basically acts as a lock. Without a patch all fields are taken from the source. With a patch any field can have an override value that the project patch defines. If its present it will replace whatever was there. Note for lists and complex data line persons and organisations a patch defines the entire list, not just a part of it.

**Comment by mdoering** [comment]
See #573 for original issue

**Comment by yroskov** [comment]
"Lock" means "data in the field will be taken from the patch".  Unlocked lock = data will be taken from raw source.

**Comment by yroskov** [comment]
>Note also that a patch cannot work on parts of an organisation or author list. Either you patch the entire list or you dont. You cannot change a single organisation only. So the lock can only be at the organisations field level

That's fine. However, patch should allow to edit organisation and authors/eds data in fields  easily. (Now I have the only option to delete and re-enter these data from the scratch).
