### ISSUE TITLE
Display sync progress on Sectors page

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/checklistbank#756]
Case: I have kicked off option "Sync all sectors from dataset 2144", and have no ideas whether process is started or not:

![image](https://user-images.githubusercontent.com/28574252/97446812-db991500-18fc-11eb-8657-f086b0ee5f88.png)

It would be helpful to display Syncstate report on sync progress at Project-Sectors page as it is already done at Project-Assembly page (just repeat the same report at Project-Sectors page):

![image](https://user-images.githubusercontent.com/28574252/97446991-1438ee80-18fd-11eb-8fc7-b50f9a95e476.png)

**Comment by mdoering** [comment]
I agree this is not nice. You have to go to assembly to see the progress and state.
Before we add this to more pages I would first like to consider the broader vision.

Geoff had an idea to have a pop up window available in all/many pages that would inform you about the current state:
https://github.com/CatalogueOfLife/checklistbank/issues/337

I feel we should indeed head to sth like that, maybe not popup, but some reusable component that allows to be opened on any page when you are logged in. And maybe some tiny state shown on every page so you know at least that sth is running.

My vision is also to harmonize all background tasks and show them in the same interface.
That includes imports, syncs, deletions, rematching, releases and even rare admin jobs like rebuilding the search index.

**Comment by mdoering** [comment]
@thomasstjerne if it is trivial to also add the sync state to the sectors page though I would agree Yuris suggestion is a useful intermins improvement!

**Comment by yroskov** [comment]
Any of discussed solutions will satisfy my needs.
