### ISSUE TITLE
improve startup time

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/checklistbank#759]
We should be able to improve startup time of the app in the client if you first visit a page.
Today it took me nearly 30s before the page came up:

<img width="1348" alt="Screenshot 2020-11-02 at 19 32 22" src="https://user-images.githubusercontent.com/327505/97905425-3ccc4880-1d42-11eb-9cbb-11197791ca4b.png">

@thomasstjerne @MortenHofft Can we reduce the js library size?
@MattBlissett Can we better host it or do anything else?

**Comment by MortenHofft** [comment]
Ideas:

* Add caching header - I do not see any
* Make it appear less low with skeletons.
* Split the bundle, we do that for translations on the registry. At least we did to begin with - it is all ready to do in CRA.
* Less code on the frontend and more on the backend? E.g. if there is a need to do citation formating, then move that parsing to the server? 
* An API proxy might allow for more dense queries and transferring less data?
* Remove the image

**Comment by MattBlissett** [comment]
I've added Apache configuration to serve pre-compressed `*.gz` content with the appropriate `Content-Encoding: gzip` header.  This makes a big difference to the 4MB Javascript file.

You'll need to adjust the build to gzip the Javascript, CSS and map files, retaining the originals.

(An option is to ask Apache to compress the content every time it serves it using mod_deflate, but these are so big it would add 100ms to the response.)

```
static/
├── [ 120]  css
│   ├── [593k]  main.46966069.css
│   ├── [ 70k]  main.46966069.css.gz
│   ├── [985k]  main.46966069.css.map
│   └── [105k]  main.46966069.css.map.gz
└── [ 116]  js
    ├── [3.6M]  main.e91f7f4d.js
    ├── [926k]  main.e91f7f4d.js.gz
    ├── [ 23M]  main.e91f7f4d.js.map
    └── [4.8M]  main.e91f7f4d.js.map.gz
```

**Comment by mdoering** [comment]
Great, that makes a huge difference! Down from 27s to just 600ms here!
Now I'll also shrink the images to their actually used size et voila.

@thomasstjerne can you adjust the build to create the gzip files?

**Comment by MortenHofft** [comment]
I did this on the registry @thomasstjerne :
`npm i gzipper`
add `; gzipper compress ./build` to `package.json` `scripts/build`

**Comment by thomasstjerne** [comment]
And we can keep enums as JSON files in the build, rather than calling the API.
For development purposes, it has so far been convenient to have "live" enums but as we are approaching a less volatile state of the API it makes sense to reduce the number of requests on start up

**Comment by thomasstjerne** [comment]
@MattBlissett now the build produces `*.gz` files. But I dont think they are being served though.

**Comment by MattBlissett** [comment]
I applied the configuration to dev as well as prod.

I've also added support for Brotli compression, which is even better than Gzip, especially for the Javascript:

```
static/
├── [ 188]  css
│   ├── [593k]  main.46966069.css
│   ├── [ 51k]  main.46966069.css.brotli
│   ├── [ 71k]  main.46966069.css.gz
│   ├── [985k]  main.46966069.css.map
│   ├── [ 73k]  main.46966069.css.map.brotli
│   └── [104k]  main.46966069.css.map.gz
└── [ 182]  js
    ├── [3.6M]  main.d3216419.js
    ├── [629k]  main.d3216419.js.brotli
    ├── [926k]  main.d3216419.js.gz
    ├── [ 23M]  main.d3216419.js.map
    ├── [2.2M]  main.d3216419.js.map.brotli
    └── [4.8M]  main.d3216419.js.map.gz
```

Maybe there's a similar Node library to generate the `*.brotli` files.

Finally, I've added a `Cache-Control: max-age=31536000` header to the contents of `static/`.

**Comment by mdoering** [comment]
Nice!

**Comment by mdoering** [comment]
[gzipper](https://www.npmjs.com/package/gzipper) claims to be able to produce both gzip and brotli.
