### ISSUE TITLE
Show taxon relations on taxon details page

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/checklistbank#762]
CLB now supports the ColDP [species interaction](https://github.com/CatalogueOfLife/coldp/blob/master/README.md#speciesinteraction) and [taxon concept relations](https://github.com/CatalogueOfLife/coldp/blob/master/README.md#taxonconceptrelation).
It also has name relations.

All of these should be shown on a taxon details page and is bundled with the TaxonInfo object for convenience:

https://api.dev.catalogue.life/dataset/1700/taxon/hybrid/info

the relations can be either direction from the main taxon and only refer to name or taxon ids.
For convenience all name and taxon ids can be resolved inside the taxon info objects refs, names and taxa maps!

**Comment by mdoering** [comment]
The new Gracillariidae  dataset contains 10.000 host/parasite species interactions that would be nice to visualize!
https://data.dev.catalogueoflife.org/dataset/2183/verbatim?type=col%3ASpeciesInteraction

**Comment by mdoering** [comment]
nice! Here is a page with many interactions:
https://data.dev.catalogueoflife.org/dataset/2183/taxon/120080890

Should we remove the taxon name from such lists?

`Sorbus intermedia (Ehrh.) Pers., 1806 (host of Phyllonorycter corylifoliella), Crataegus oxyacantha L., 1753 (host of Phyllonorycter corylifoliella`

Or even consider to group relations by their type and use the relation type as the label on the left as we do for name relations? That might be most readable

**Comment by mdoering** [comment]
Here is another one from @dhobern:
https://data.dev.catalogueoflife.org/dataset/2050/taxon/481

It seems the direction of the relation is wrongly shown.

> Barleria prionitis (eats Alucita priona)

should be

> Alucita priona --eats--> Barleria prionitis
the taxonID of the relation is the subject, the relatedTaxonScientificName is the object.

**Comment by mdoering** [comment]
And references are not shown

**Comment by thomasstjerne** [comment]
> Here is another one from @dhobern: https://data.dev.catalogueoflife.org/dataset/2050/taxon/481
> 
> It seems the direction of the relation is wrongly shown.
> 
> Barleria prionitis (eats Alucita priona)
> 
> should be
> 
> Alucita priona --eats--> Barleria prionitis
> the taxonID of the relation is the subject, the relatedTaxonScientificName is the object.

But in the Gracillariidae dataset I think the direction is opposite:
https://data.dev.catalogueoflife.org/dataset/2183/taxon/110071900

The tree must be the host of the moth, and also the wasp is the parasite (?)

**Comment by mdoering** [comment]
indeed they used the wrong interaction type, it should be inverse

**Comment by mdoering** [comment]
@thomasstjerne could we move the interaction type to the outer left like I proposed already for name relations?
https://github.com/CatalogueOfLife/checklistbank/issues/951

That aligns and reads better I think
