### ISSUE TITLE
ChecklistBank: Metadata page is empty for all GSDs

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/checklistbank#763]
Fixing metadata, I have checked 5 GSDs, metadata page was empty in all cases:

![image](https://user-images.githubusercontent.com/28574252/98259262-846ff180-1f47-11eb-8089-df29b29300ba.png)
![image](https://user-images.githubusercontent.com/28574252/98259312-95206780-1f47-11eb-8bc0-a6a25bbfdaae.png)
![image](https://user-images.githubusercontent.com/28574252/98259331-9a7db200-1f47-11eb-8454-a4c25906cde7.png)
![image](https://user-images.githubusercontent.com/28574252/98259060-3ce96580-1f47-11eb-83eb-39c9281a95ae.png)
![image](https://user-images.githubusercontent.com/28574252/98259864-3dcec700-1f48-11eb-9e9a-a6f6ac33a36d.png)

**Comment by mdoering** [comment]
they are working again. @thomasstjerne it is worrying though to see some pages break and magically work again.
Could that be client caching related? The API responds with a `Cache-Control` header for 24h for all API URLs that start with a release. 

@yroskov if this happens again, can you clear your browser cache and see if that makes a difference?
