### ISSUE TITLE
Project/Release metrics not shown in public

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/checklistbank#764]
The public menu for a project or release does not show any metrics like the imports sections did.
Propose new "Metrics" page

**Comment by thomasstjerne** [comment]
Should the metrics be taken from this endpoint: https://api.catalogue.life/dataset/2206/import?state=finished
?
Looks like there are only zeros so far

**Comment by mdoering** [comment]
yes, resource is right. Zeroes not, see https://github.com/CatalogueOfLife/backend/issues/907
