### ISSUE TITLE
browser requesting authentication while logged in

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/checklistbank#767]
There is a strange authentication problem with the browser requesting me to login even though I am already logged in and the JWT token is send in headers to the API:

<img width="1470" alt="Screenshot 2020-11-19 at 17 35 08" src="https://user-images.githubusercontent.com/327505/99695359-c6438080-2a8d-11eb-97c5-a97e448b8742.png">

**Comment by thomasstjerne** [comment]
Looks like the logo API wants some credentials
https://api.dev.catalogueoflife.org/dataset/2063/logo?size=MEDIUM

**Comment by mdoering** [comment]
Ah yes. It does cause its nested under a private dataset.
But we use this in a simple html image src I supposed. Is there a more reactive way to do this with auth?
