### ISSUE TITLE
Improve project menu

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/checklistbank#775]
I always found the [menu with 3 levels unintuitive and impractical](https://github.com/CatalogueOfLife/checklistbank/issues/593). It requires too many opening & closing of menus and you easily get lost. Worse it also is inconsistent how other datasets behave.

What if we kept the project menu on 1 level and only kept menu items which are only available for projects but not for releases or other public datasets? You can access any project just like any other dataset with a name search, classification tree, downloads, etc:
https://data.catalogueoflife.org/dataset/3/download

Releases are treated just as public datasets, not as projects as they have immutable data.

I'd therefore suggest to change the menu for projects as follows:

 - Assembly
 - Sectors
 - Sector Syncs
 - Decisions
 - Estimates (TBD)
 - Duplicates
 - Source datasets
 - Source metrics
 - Options
 - "select source"

This removes the need for the project menu items _Names_, _References_, _Releases_ and _Metadata_.

**Comment by yroskov** [comment]
Current state of the menu (with public subset in it) is very much confusing. We should address menu design, but pls do this AFTER the annual checklist release.

Project submenu is strongly needed.

**Comment by mdoering** [comment]
It really is not much of a big effort and as we need to test the UI for broken links thoroughly when we put the updated metadata live I would suggest to just get this done at the same time. @thomasstjerne do you agree?

**Comment by thomasstjerne** [comment]
> Project submenu is strongly needed. It is the main tool for editorial work.

If I understand this right @yroskov disagrees that the project menu should be flattened.

> Current state of the menu (with public subset in it) is very much confusing.

But something else is confusing "public subset" is this the project source section (with workbench / duplicates ) or the public dataset search and display?

**Comment by mdoering** [comment]
Yes, he apparently sees the submenus as the public part which it isn't. It does contain "classic" public items such as the names & reference search currently. Thats why argue he hardly uses it and if these public pages are not kept in the project but outside as any other public view we dont really have a problem with a flat project menu. I would very much like this to happen.

**Comment by mdoering** [comment]
I found today that MS Teams uses a 2 level sidebar menu, but for deeper nested pages it simply uses breadcrumbs:

<img width="489" alt="Screenshot 2021-06-08 at 07 12 51" src="https://user-images.githubusercontent.com/327505/121129405-2c76d180-c82d-11eb-8a69-639df476a05b.png">

**Comment by thomasstjerne** [comment]
Maybe horisontal tabs would be good for third level items. But it will take up a little space on top of the page when e.g. using workbench and duplicates. We have already the header / logo etc, so it might be too space consuming all in all.

**Comment by mdoering** [comment]
replaced by https://github.com/CatalogueOfLife/checklistbank/issues/1326
