### ISSUE TITLE
Dataset menu missing for private datasets

### ISSUE THREAD

**Issue by gdower** [CatalogueOfLife/checklistbank#776]
On prod, the dataset sidebar menu is missing for private datasets:

![image](https://user-images.githubusercontent.com/8573609/101694702-21d3af00-3a39-11eb-8d39-629c6f91097a.png)

I logged in and out, so I don't think it's a session issue. It's also missing for @yroskov.

Frontend version: 2c59729 December 8, 2020 4:31 AM
Backend version: 0d30d28 December 9, 2020 5:02 AM

**Comment by gdower** [comment]
I realized that the dataset menu does not show for private datasets.

**Comment by mdoering** [comment]
related to https://github.com/CatalogueOfLife/checklistbank/issues/772
