### ISSUE TITLE
The system refused to apply decisions (no error reports available)

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/checklistbank#778]
Leave FeedbackFrontend version: 2c59729 December 8, 2020 4:31 AMBackend version: 74a5865 December 10, 2020 3:59 AM
@gdower & @mdoering 

Working with Tasks for World Plants in the clearinghouse, I set up filters in Manuscript Names report in a way to get a list of Accepted names Without Decision.  

https://data.catalogueoflife.org/catalogue/3/dataset/1141/workbench?decisionMode=_NULL&facet=rank&facet=issue&facet=status&facet=nomStatus&facet=nameType&facet=field&limit=50&nomstatus=manuscript&offset=0&status=accepted

Then, I selected all names, chose Provisionally Accepted decision and applied it.
... and nothing happened. System does not issue error message. 

![image](https://user-images.githubusercontent.com/28574252/101957548-4362a100-3bc7-11eb-9373-263df9983b58.png)

I repeated exercise 3 times without success.

**Comment by gdower** [comment]
It looks like the [provisional decisions were applied](https://data.catalogueoflife.org/catalogue/3/dataset/1141/workbench?decisionMode=_NOT_NULL&facet=rank&facet=issue&facet=status&facet=nomStatus&facet=nameType&facet=field&limit=50&nomstatus=manuscript&offset=0&status=accepted), so maybe the notification that the decisions were applied was not displaying.
