### ISSUE TITLE
Maintenance warning needed

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/checklistbank#784]
We need to allow an admin to raise a maintenance warning globally and push that to every user currently working with the application. The warning should be a banner at the top with sth like "Maintenance work in progress - please expect errors". The users, especially editors doing content work, are warned and know the site might not be working and not log issues.

**Comment by mdoering** [comment]
The API now adds a new boolean `maintenance` property to the server settings object formerly exposed under `/admin/background`. This route has changed to `/admin/settings` instead.

You can then just PUT {"maintenance": true} /admin/settings and read it back again via GET to drive a warning banner in both CLB and the portal, see https://github.com/CatalogueOfLife/portal/issues/103

**Comment by thomasstjerne** [comment]
The admin interface now has a switch for this - deployed to dev.

**Comment by mdoering** [comment]
I wonder if it makes sense to even display the settings in the warning. It is basically a service on/off map:
 - dataset importer
   - name matching (part of importer, likely to be exposed on its own soon)
 - import scheduler
 - gbif sync

Well, probably not so interesting for the portal users.
But for ChecklistBank and API users it's very useful to know if these services are currently working.
Having these settings exposed somewhere public in CLB would be good.

**Comment by mdoering** [comment]
> The admin interface now has a switch for this - deployed to dev.

Is this deployed? I cant see it

**Comment by thomasstjerne** [comment]
Displaying the which background services are running moved to https://github.com/CatalogueOfLife/checklistbank/issues/788
