### ISSUE TITLE
Cannot manually add unparsable names in assembly

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/checklistbank#793]
When adding "Viruses" as a kingdom to Biota in the modify tree assembly mode, the 2nd step shows no scientific name at all.
Maybe this is because the name is unparsable?

http://api.dev.catalogueoflife.org/parser/name?name=Viruses

Unparsable names should still be placed into scientificName and other information like the nameType be set (in this case virus)

**Comment by mdoering** [comment]
Same happens for edit/updates

**Comment by mdoering** [comment]
If I manually edit a name, should I not just see the currently parsed values instead of parsing the name again?
I would expect to just to step 2 immediately in case of edits

**Comment by mdoering** [comment]
Please also make `Name type` a required field and populate it with the preexisting one (edit) or name parser supplied one (create). In case the name parser fails (I can't think of any reason though why this should happen) please use _scientific_ as the default.

**Comment by thomasstjerne** [comment]
Adding a child doesn´t even hit the nameparser (maybe it should?) - I can easily add Viruses or any arbitrary name.
For Edits: I think the response format of the nameparser changed, as the UI expected an array of objects, each with a name property. But this is now adapted to the current format
