### ISSUE TITLE
Remove names index issues from dataset issues page?

### ISSUE THREAD

**Issue by gdower** [CatalogueOfLife/checklistbank#799]
On the dataset issues page, could we please move all the names index issues into a separate issue group and hide that names index issues group by default? It seems like most of the time, those `Name Match *` issues are not something data providers can fix because it's an issue between the dataset and the ChecklistBank names index. People end up wasting a lot of time trying to figure out what those `Name Match *` issues even mean, and it clutters the issues page with inactionable information, making it less likely that people will go through and fix actual data issues that they can control.

If the names index is going to be managed by someone, then it might make sense to move these names index issues into a names index dashboard under the admin section, kind of like the [Source Datasets](https://data.catalogueoflife.org/catalogue/3/sources) matrix except showing only the `Name Match *` issues for the whole ChecklistBank.

**Comment by mdoering** [comment]
The question is who wants to use these flags?
We have 4 issues currently being flagged:

```
  NAME_MATCH_INSERTED(NAME, Level.INFO, "The name was never seen before and inserted into the Names Index for the first time"),

  NAME_MATCH_VARIANT(NAME, Level.INFO, "The name matches an orthographic variant of the name, authorship and/or rank " +
      "already found in the names index and which is considered to be still the same name."),
  
  NAME_MATCH_AMBIGUOUS(NAME, Level.WARNING, "Multiple matching names found in the Names Index."),
  
  NAME_MATCH_NONE(NAME, Level.WARNING, "Name not found in the Names Index."),
```

If they are useless we can just remove them from issues in CLB, not just the frontend. Not sure if removing the issues from the issue page alone makes sense. They are also present in metrics, details pages and probably elsewhere. If these other places show different information than the issue page it might be even more confusing. Hiding them with the option to show them is an easy quick change though.

We do already store the name match type with the match in the database, so we do not lose that information.
Exposing it with issues allows us just to include a filter in the search. So far I have not really made use of them, I doubt anyone else ever did.

For GBIF occurrences this was a useful filter sometimes to spot missing names in the backbone.
The names index though grows automatically with new datasets, so we should never have no matches.

**Comment by gdower** [comment]
I favor doing whatever is easiest. The main thing is just hiding it on the dataset issues page, because it is a common source of confusion for most people. I think it's much less of a problem that those `Name Match *` issues show in other places like the Source Dataset matrix and in the names search, because it will probably be overlooked by most people.

Does Ayco use those `Name Match *` issues? In the long-term maybe it will be useful for GBIF and managing the names index. However, if no one uses those issues, then we probably should eliminate them.

**Comment by yroskov** [comment]
We need a view in Issues (say, Provider's View) which help us to communicate with GSDs. At the moment, our GSD partners confused by Name Match reports in the main list. Every time we need to explain to them that they do not need to "fix" those issues. This is a barrier.

**Comment by mdoering** [comment]
any issue with INFO level should not be "fixed". The level is of issue is the most important thing.
ERRORS must be fixed, WARNINGs should at least be verified. INFO nothing to do

**Comment by thomasstjerne** [comment]
@mdoering If `Name match *` issues were moved to their own issue group in the ENUM, it would be very easy to not show them in the default view.
E.g.:
````
{
    "level": "info",
    "name": "name match inserted",
    "description": "The name was never seen before and inserted into the Names Index for the first time",
    "group": "name index" // change from "name"
  }
````

**Comment by mdoering** [comment]
It is both easy to remove them or to change their group.
I am inlined to remove them entirely, as we keep track of the match type in the database anyways if we need to figure out what has happened when managing the names index. It probably also removes the need to update our search index in some cases when we just rematch names without reimporting them.

**Comment by mdoering** [comment]
I will remove all names index issues in the next deploy
