### ISSUE TITLE
Drag and drop sector registration broken

### ISSUE THREAD

**Issue by gdower** [CatalogueOfLife/checklistbank#804]
Try to drag and drop Polychaeta onto Annelida:

https://data.dev.catalogueoflife.org/catalogue/3/assembly?assemblyTaxonKey=83daf648-b588-4c8f-96ff-8f2fd112fc9d&datasetKey=1090&sourceTaxonKey=x6

No request is sent by the frontend. Sector registration still works directly with the backend.

**Comment by gdower** [comment]
It affects prod, too.

**Comment by yroskov** [comment]
My attempt to assembly new Opiliones also failed for the same reason. 
(Note: order Opiliones is deleted from the Tree as a preparation for assembly).

**Comment by yroskov** [comment]
@thomasstjerne @mdoering 
Unfortunately, drag&drop option still does not work in production at https://data.catalogueoflife.org/catalogue/3/assembly?assemblyTaxonKey=5bb49bfb-d05a-4995-96ca-27c9bdced00f&datasetKey=2256&sourceTaxonKey=551110

Frontend version: 8ce789f February 9, 2021 3:57 AMBackend version: b323754 February 2, 2021 5:49 AM

**Comment by yroskov** [comment]
Now it works! The same version: Frontend version: 8ce789f February 9, 2021 3:57 AMBackend version: b323754 February 2, 2021 5:49 AM
