### ISSUE TITLE
Make the project section viewable without a login

### ISSUE THREAD

**Issue by gdower** [CatalogueOfLife/checklistbank#810]
It would be useful if unauthenticated users could view the managed project section but without editing rights. I think we had previously discussed implementing it by just removing the editing interfaces.

The only exception would be private datasets, where it would probably be best to not allow access to endpoints in case it exposes data that they did not want to include in the project:

https://data.catalogueoflife.org/catalogue/3/dataset/1234/*

**Comment by mdoering** [comment]
This might become a large burden for the frontend code to present either pages with editing options or without.
But maybe there is a simple generic way to do this instead by using css to just hide editorial options?

It might be good to understand the reasons for offering the project view to the public. 
Personally I miss quite a few things from the project menu in the public menu. Things like sectors, decisions, releases, source datasets all need to be publicly accessible. As a public user I would be rather puzzled though why there are 2 different menu items and not just everything under the dataset menu item. In that regard I don't think simply showing the project to the public is a good thing. I'd rather have the public item extended to cover what we need.

**Comment by mdoering** [comment]
@gdower what parts of a project would you think should be exposed in the public view?
Let's create separate issues for each of them, we have already source metrics:
https://github.com/CatalogueOfLife/checklistbank/issues/824

and a new public downloads page:
https://github.com/CatalogueOfLife/checklistbank/issues/826

Closing this one here as we don't want to expose the entire project menu. It will become hard to maintain.

**Comment by mdoering** [comment]
other open issues related to public project pages:

https://github.com/CatalogueOfLife/checklistbank/issues/737
https://github.com/CatalogueOfLife/checklistbank/issues/679
https://github.com/CatalogueOfLife/checklistbank/issues/647
