### ISSUE TITLE
Issues & References missing in public dataset view

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/checklistbank#815]
They only show if you are logged in, is that on purpose?

<img width="1487" alt="Screenshot 2021-02-24 at 10 09 39" src="https://user-images.githubusercontent.com/327505/108977040-71189b80-7688-11eb-82a1-9b9844ba23bc.png">

<img width="1548" alt="Screenshot 2021-02-24 at 10 08 48" src="https://user-images.githubusercontent.com/327505/108976945-5a724480-7688-11eb-9197-716552df37bb.png">

**Comment by thomasstjerne** [comment]
> They only show if you are logged in, is that on purpose?

I think we decided at some point that issues should only be shown to logged in users?
