### ISSUE TITLE
Allow upload of manual metadata file

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/checklistbank#834]
Offer a manual metadata upload similar to the logo on the metadata page.
This should accept a YAML or EML XML file and then do a PUT to the API with the respective content type (text/yaml or text/xml):

`PUT /dataset/{key}`

**Comment by thomasstjerne** [comment]
Would that apply to all dataset origins?

**Comment by mdoering** [comment]
Hm, I guess so. All the ones where you can modify the metadata with the forms.
And you will need to reload the dataset as it changes the dataset.

**Comment by thomasstjerne** [comment]
@mdoering see https://github.com/CatalogueOfLife/backend/issues/985
