### ISSUE TITLE
Copy&Paste titles of Tasks

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/checklistbank#837]
@thomasstjerne, could you please modify interface script to allow me do copy&paste of task titles (words) from TASK banners?

In current development, I can easy copy&paste titles from ISSUES banners (https://data.catalogueoflife.org/catalogue/3/dataset/1141/issues), but unfortunately, but cannot do it from TASKS banners (https://data.catalogueoflife.org/catalogue/3/dataset/1141/tasks).

For example, I need to use title "SYN-SYN species (different parent, different authors)" in my reports and communications with authors, and I need to type in this phrase manually again and again. It take a lot of time. (Similar work with ISSUES is much easier:)

**Comment by thomasstjerne** [comment]
@yroskov 
The task banners are links, therefore they behave a bit different.
Does it work if you right click them and then choose "copy" ?

**Comment by yroskov** [comment]
Right click is copying a link. I need a label (i.e. "SYN-SYN species (different parent, different authors)")

**Comment by thomasstjerne** [comment]
I get this:
`ACC-SYN species (same accepted, same authors) 51 of > 50  `

If I do this:
<img width="804" alt="Screenshot at Mar 22 15-43-12" src="https://user-images.githubusercontent.com/1666484/112008040-6f29e700-8b25-11eb-8138-c3ad83d200bb.png">

If you right click, do you not have a `Copy` option?

**Comment by yroskov** [comment]
Unfortunately, I have only Copy link:

![image](https://user-images.githubusercontent.com/28574252/112008607-a2538280-8af3-11eb-9127-7bfbdf0a8bca.png)

**Comment by yroskov** [comment]
I use Firefox 86.0.1

**Comment by yroskov** [comment]
If it's not possible to make copy'able label texts from TASK page, could you make able to do a copy of label text from the page of each task? I.e. from here:

![image](https://user-images.githubusercontent.com/28574252/112012670-63bfc700-8af7-11eb-809c-c2fe8a237ca4.png)
