### ISSUE TITLE
Missing daggers with extinct higher taxa in the classification

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/checklistbank#844]
@thomasstjerne @mdoering 

It looks like, there are no daggers in the classification with fully extinct taxa above species rank.

![image](https://user-images.githubusercontent.com/28574252/112537099-48b1b900-8d7c-11eb-82d3-8083930519c1.png)

Expected presentation/behavior: if all children species have extinct status inside a parent genus, the genus gets status "extinct" and should be marked with dagger. If all children genera have extinct status inside a parent family, the family gets status "extinct" and should be marked with dagger, etc.

Illustration from AC19:

![image](https://user-images.githubusercontent.com/28574252/112537755-0dfc5080-8d7d-11eb-938c-4193e63caf8f.png)

**Comment by mdoering** [comment]
Yes, that is expected as this needs to be calculated in the backend where there is an open ticket for this for some time:
https://github.com/CatalogueOfLife/backend/issues/289

I agree we should reprioritize it, maybe still for the annual release?
