### ISSUE TITLE
Strange behaviour of Assembly interface

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/checklistbank#846]
@thomasstjerne @mdoering 

I have tried to establish sector for WoRMS Mollusca.

After I drag&dropped phylum Mollusca in the Tree (subtree Mollusca was deleted before), I clicked on Attach button. Pop-up menu remained open after click, but no any further progress was happened. Later, 503 error message appeared. Mollusca did not appear in the tree.

![image](https://user-images.githubusercontent.com/28574252/112894040-000e3e80-90a1-11eb-938c-1418a641f79f.png)

![image](https://user-images.githubusercontent.com/28574252/112894135-1ae0b300-90a1-11eb-9f10-31548a6da587.png)

**Comment by thomasstjerne** [comment]
This is when the the backend is unavailable, e.g. during a deployment or other outage.
