### ISSUE TITLE
Notifying editors about a running release

### ISSUE THREAD

**Issue by gdower** [CatalogueOfLife/checklistbank#851]
Performing assembly tasks while a release is running might break the release, so the frontend should warn editors not to edit the catalogue while a release is running, or better yet not even allow editing while the release is running.

[Related notifications issue](https://github.com/CatalogueOfLife/checklistbank/issues/337) and [backend issue](https://github.com/CatalogueOfLife/backend/issues/997)

**Comment by mdoering** [comment]
I think this should happen in the backend. The UI would simply see an API error with a message about the running release
