### ISSUE TITLE
For Releases, link to source views from Tree

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/checklistbank#870]
For public projects and releases we need to provide a source dataset details page similar to the project itself.
This will be the landing page for a source DOI. Propose a resource akin to the [API](http://api.catalogueoflife.org/dataset/2296/source/1010): `https://data.catalogueoflife.org/dataset/{datasetKey}/source/{sourceKey}`

It would therefore be best to copy the [portals dataset page](https://www.catalogueoflife.org/data/dataset/1189) as much as possible and show a mix of metadata, basic metrics and the taxonomic coverage based on sectors. We should use the same for the public metadata/about page and call it "Overview" - see https://github.com/CatalogueOfLife/checklistbank/issues/868

**Comment by mdoering** [comment]
The source pages should be linked from the [source metrics ](https://data.catalogueoflife.org/dataset/3/sourcemetrics).

**Comment by mdoering** [comment]
In addition to the portal view a CLB source page should also tell where it originated from and link back to the master dataset of the source, e.g. https://data.catalogueoflife.org/dataset/2144/overview for ITIS

**Comment by mdoering** [comment]
We basically need to reproduce a mini portal inside the public dataset menu in ChecklistBank.

**Comment by thomasstjerne** [comment]
It is already there: https://data.catalogueoflife.org/dataset/2303/source/1009

**Comment by thomasstjerne** [comment]
Superceded by #876
