### ISSUE TITLE
Prepare CLB release view for annual release

### ISSUE THREAD

**Issue by thomasstjerne** [CatalogueOfLife/checklistbank#876]
- [x] Links from tree to GSD should go to source view
- [x] Links from Taxon pages should go to source view
- [x] Links in Taxonomic Coverage (expand row in source table) should link to public classification view

**Comment by thomasstjerne** [comment]
The source view is here https://data.catalogueoflife.org/dataset/2303/source/1009
It is linked from https://data.catalogueoflife.org/dataset/2303/sourcemetrics

**Comment by mdoering** [comment]
There are a few differences in terminology between the [portal component]( https://data.catalogueoflife.org/dataset/2303/source/1009) based views and [classic clb views](https://data.catalogueoflife.org/dataset/2303/taxon/33J2D) that would be good to resolve:

 - _Full name_ vs _Title_: we use title everywhere else. But I would actually drop this entirely as the title is already shown above in both CLB and the [portal](https://www.catalogueoflife.org/data/dataset/1010).
 - _Abstract_ vs _Description_: we use description everywhere else
 - _Common name_ vs _Vernacular name_: API & ColDP use Vernacular name. I would propose to use that everywhere
 -  _Short name_ vs _alias_: alias is used in API & ColDP, but short name is used often in metadata standards like CSL-JSON. Open for both as long as we are consistent
 - _English name of the Group_ or _Taxonomic Group_. The ColDP metadata format calls this [taxonomicScope](https://github.com/CatalogueOfLife/coldp/blob/master/metadata.yaml) which clashes slightly with the auto generated taxonomic coverage based on sectors. But I reckon it's fine to have both scope and coverage.
