### ISSUE TITLE
Pilot UI for showcasing difference in GBIF Occurrences

### ISSUE THREAD

**Issue by timrobertson100** [CatalogueOfLife/checklistbank#877]
When GBIF prepares to deploy a new taxonomic backbone, a process is run allowing data managers to explore the impact of the changes before it is released. This involves extracting the verbatim classifications from records, aligning them to the proposed backbone, and then presenting them for exploration, such as [this example](http://labs.gbif.org/taxonomy-review-v3/?csv=20210212/report-1000.tsv). This allows search and browse, and indicates the number of records that are affected.

A similar approach can be taken to explore how the COL and GBIF taxonomies differ with respect to occurrence organization. We could present the table showing the 3 classifications (verbatim, GBIF, COL) and allow data managers to explore how they differ, prioritized by the occurrence count.

[This file](https://github.com/CatalogueOfLife/checklistbank/files/6498979/fungi-100.csv)  provides an example showing how GBIF and COL (May 2021) differ for all Fungi records in GBIF where there are >100 records having the classification, and shown [here](http://labs.gbif.org/taxonomy-review-v3/?csv=col-test/fungi-100.csv) in the current UI.

I suggest the new UI should show 3 lines of text (verbatim, gbif, col), not 2 as the current GBIF one, but continue to collapse the cell into a single line when the content is the same, and show colouring pills when the COL version agrees with the verbatim.

**Comment by timrobertson100** [comment]
For @dhobern interest, [here](http://labs.gbif.org/taxonomy-review-v3/?csv=col-test/lep-100.csv) is GBIF/COL comparison for Lepidotera and the [source CSV](https://github.com/CatalogueOfLife/checklistbank/files/6499054/lep-100.csv) attached.

**Comment by timrobertson100** [comment]
Fabaceae [CSV](https://github.com/CatalogueOfLife/checklistbank/files/6499116/fab-100.csv) having >100 records, demo'ed [here](http://labs.gbif.org/taxonomy-review-v3/?csv=col-test/fab-100.csv)

**Comment by mdoering** [comment]
That looks very useful to me and I like the idea of 3 rows in a cell. 

It would be good if the UI would give some context and show a title for the rows and labels for the colors somewhere, so the page can be understood without knowing how it was created.

**Comment by timrobertson100** [comment]
> It would be good if the UI would give some context and show a title for the rows and labels for the colors somewhere, so the page can be understood without knowing how it was created.

Thanks, @mdoering  - we're capturing changes [here](https://github.com/gbif/taxonomy-release-review-tool/issues) as they apply to the GBIF pre-release tool too, and your ideas are covered.

You'll find ideas, including [this](https://github.com/gbif/taxonomy-release-review-tool/issues/6):

<img width="429" alt="Screenshot 2021-05-18 at 10 23 02" src="https://user-images.githubusercontent.com/6759267/118618128-97e7f900-b7c3-11eb-8853-1c6d0c73b27c.png">
