### ISSUE TITLE
Decision "block" does not work - URGENT - it is a stopper of whole assemly

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/checklistbank#881]
Frontend version: 48ec191 May 20, 2021 8:42 AMBackend version: e6a2cb9 May 16, 2021 11:19 PM
@mdoering @thomasstjerne @gdower @olafbanki 

Working on June release, I have spot that when I applies decision "block" in the Workbench via ISSUES, the label says "up..." (update). 

Preview release shown that "blocked" names go to the final product. I would expect, a lot of unwanted names go this way in CoL.

Example:
https://data.catalogueoflife.org/catalogue/3/dataset/1005/workbench?facet=rank&facet=issue&facet=status&facet=nomStatus&facet=nameType&facet=field&facet=authorship&facet=authorshipYear&facet=extinct&facet=environment&facet=origin&limit=50&offset=0&q=species

![image](https://user-images.githubusercontent.com/28574252/119000153-75cfb180-b950-11eb-9d14-d84cd69b7c5f.png)

and in the product:
https://preview.catalogueoflife.org/data/taxon/8G92W

![image](https://user-images.githubusercontent.com/28574252/119000476-c21af180-b950-11eb-8a67-a2157bf70e44.png)

If I am right, decision "block" still works in TASKS.

**Comment by mdoering** [comment]
maybe related with addition of the Ignore decision?
