### ISSUE TITLE
Source metadata without actions

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/checklistbank#903]
Project source metadata should be just metadata without any actions to upload data, logos, trigger imports or delete the dataset.
Just plain metadata, header should entirely be removed.

https://data.dev.catalogueoflife.org/catalogue/2091/dataset/2138/metadata

<img width="1213" alt="Screenshot 2021-06-15 at 15 15 55" src="https://user-images.githubusercontent.com/327505/122059130-9b839580-cdec-11eb-8abb-fd3593032d9f.png">

**Comment by thomasstjerne** [comment]
Where should the actions move to? options?

**Comment by mdoering** [comment]
just removed. You cannot delete or import sources

**Comment by mdoering** [comment]
you also cannot upload data or metadata. This only makes sense for the public, latest datasets but not the source within a project
