### ISSUE TITLE
Change dev sidebar color

### ISSUE THREAD

**Issue by gdower** [CatalogueOfLife/checklistbank#919]
The `test environment` banner on dev is too small, so it is easy to get dev and prod environments confused. If the menu is fully expanded, you cannot even see the `test environment` banner. Could you please change the color of the sidebar on dev to make the distinction between dev and prod more obvious?

![sidebar2](https://user-images.githubusercontent.com/8573609/126843786-4d7688c3-5226-4bdb-a3b8-e82a5881ab69.png)

![sidebar](https://user-images.githubusercontent.com/8573609/126843582-44ce1d40-edd9-4059-8a6d-5aa8cfc34a64.png)

**Comment by thomasstjerne** [comment]
Took another approach with a permanent header text too improve this
