### ISSUE TITLE
Missing metrics for releases

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/checklistbank#931]
releases should also have a metrics page similar to the import one:
https://data.catalogueoflife.org/dataset/2328/imports

The page works, but:

 - it is not linked from the menu
 - it contains "import" terminology when it should be called "release"
 - the new tabs for diff and timeline make sense for changes of all releases for a project, but not for a single release. We could remove them or link to the [project metrics](https://data.catalogueoflife.org/dataset/3/imports)

**Comment by mdoering** [comment]
The public COL releases still don't have any metrics:
https://data.catalogueoflife.org/dataset/2328/about

**Comment by thomasstjerne** [comment]
wasn´t deployed
https://data.catalogueoflife.org/dataset/2328/release-metrics
