### ISSUE TITLE
White screen for the report on broken sectors

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/checklistbank#935]
https://data.catalogueoflife.org/
Frontend version: 990876d August 24, 2021 3:58 AMBackend version: 7a04101 August 23, 2021 11:03 PM

I need to see a report on broken sectors in the project. 
(1) I go to Sectors page: https://data.catalogueoflife.org/catalogue/3/sector?limit=100&offset=0
(2) Choose switch "Only broken" and get a white screen which remain empty after browser reload:

![image](https://user-images.githubusercontent.com/28574252/130648369-75428ba4-a650-4aa7-93d5-7ff03503ca4c.png)

**Comment by mdoering** [comment]
@yroskov can you please try again?

**Comment by yroskov** [comment]
Now all fine because @gdower deleted a record with broke the system.

**Comment by mdoering** [comment]
which/what was that about?
