### ISSUE TITLE
Explanation of name matching result

### ISSUE THREAD

**Issue by sharifX** [CatalogueOfLife/checklistbank#941]
I am testing the name-match tool with data borrowed from ICOS. Please see the attached input file. It includes a few wrong names and wrong data on purpose. 
[ICOS_Test_CoL.txt](https://github.com/CatalogueOfLife/checklistbank/files/7122205/ICOS_Test_CoL.txt)

I was wondering if there are documentations to help us interpret the matching result (for non taxonomist/biologist). For example, _Vicia faba L_. was marked as variant even though it seems it is an accepted name. And _Vicia faba_ was marked as "exact". For both of these, the result pointed to the same taxonID: '[7G2QH'](https://data.catalogueoflife.org/dataset/2296/taxon/7G2QH). 

An explanation of the test result and how the matching works would be helpful to know.  Is the suffix parsed out always before matching? For instance, an incorrect author string was added to the test dataset and the match type was flagged as 'canonical'.

**Comment by thomasstjerne** [comment]
The Matchtype is purely technical and does not make much sense to users. It has now been removed from the results presented by the tool.
