### ISSUE TITLE
Need an export of Task & Issues reports in CSV format

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/checklistbank#943]
(for attention of @mdoering & @thomasstjerne)
 
Communicating subgeneric problems in Diptera with Systema Dipterorum authors, we have discovered that they have no access, for example, to Identical Subgenus online report 
(https://data.catalogueoflife.org/catalogue/3/dataset/1101/duplicates?category=uninomial&limit=500&minSize=2&mode=STRICT&offset=0&rank=subgenus&withDecision=false).

@gdower has exported data in CSV file. This resolved the problem.

Would it be possible to add functionality and a button in the interface "CSV Export" with each report in TASKS and ISSUES? It will make easier CoL communications and workflow between project editors and GSD authors.

**Comment by mdoering** [comment]
We could also change access control.
We always wanted to have an additional reviewer role, that only allows to read but not to submit any forms or apply changes.

The simplest would be to manage the list of such user manually per project.
But we could also consider to automatically give read access to owners of a source which are used by a project. That would remove the burden of managing access rights, but it would also make COL a lot more visible. Which might be a good thing. If someone uses data from other sources it is only fair to allow them to see how it's getting used.

Does that make sense? A CSV download might be good in any case.
