### ISSUE TITLE
Show taxon references directly

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/checklistbank#952]
Taxon references are currently hidden behind the small doc icon next to the name.
publishedIn is the only exception which renders in the main content and is immediately visible.

We should render other taxonomic references the same way, but further down in the block (very end?).
https://data.dev.catalogueoflife.org/dataset/1189/taxon/44300

<img width="1500" alt="image" src="https://user-images.githubusercontent.com/327505/135456879-4ca21880-cb52-465f-873f-f51ce18ac311.png">

<img width="1500" alt="image" src="https://user-images.githubusercontent.com/327505/135456910-79439ab6-3482-4bbb-ab5e-d9020f2db516.png">

**Comment by thomasstjerne** [comment]
We used to have that, but changed for some reason. I have revived it
