### ISSUE TITLE
Empty sceen in TASK reports

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/checklistbank#959]
Dear @thomasstjerne, 

Working with TASK reports in Scarabs GSD... 
https://data.catalogueoflife.org/catalogue/3/dataset/1027/tasks
![image](https://user-images.githubusercontent.com/28574252/140187491-f9dce35c-12f0-40b8-bde6-f9bdd71c4333.png)

... I tried to open unresolved reports (orange bars), but **get an empty white screen**, like that:
![image](https://user-images.githubusercontent.com/28574252/140188255-a54a31d3-b312-4859-b55f-cd81f5a586d5.png)
(https://data.catalogueoflife.org/catalogue/3/dataset/1027/duplicates?acceptedDifferent=true&authorshipDifferent=true&category=binomial&limit=500&minSize=2&mode=STRICT&offset=0&status=synonym&withDecision=false)

**Firefox Console report:**

Cookie “__utmt” will be soon treated as cross-site cookie against “https://data.catalogueoflife.org/terms.json” because the scheme does not match. terms.json
Cookie “__utmb” will be soon treated as cross-site cookie against “https://data.catalogueoflife.org/terms.json” because the scheme does not match. terms.json
false index.js:107:22
Cookie “__utmc” will be soon treated as cross-site cookie against “https://data.catalogueoflife.org/gitVersion.json” because the scheme does not match. gitVersion.json
Cookie “__utmt” will be soon treated as cross-site cookie against “https://data.catalogueoflife.org/gitVersion.json” because the scheme does not match. gitVersion.json
Cookie “__utmb” will be soon treated as cross-site cookie against “https://data.catalogueoflife.org/gitVersion.json” because the scheme does not match. gitVersion.json
Cookie “__utmc” will be soon treated as cross-site cookie against “https://data.catalogueoflife.org/favicon.ico” because the scheme does not match. favicon.ico
Cookie “__utmt” will be soon treated as cross-site cookie against “https://data.catalogueoflife.org/favicon.ico” because the scheme does not match. favicon.ico
Cookie “__utmb” will be soon treated as cross-site cookie against “https://data.catalogueoflife.org/favicon.ico” because the scheme does not match. favicon.ico
TypeError: Gi is undefined
    render columnDefaults.js:381
    R index.js:64
    React 7
    unstable_runWithPriority scheduler.production.min.js:19
    React 6
    getData index.js:186
react-dom.production.min.js:209:194
TypeError: Gi is undefined
    render columnDefaults.js:381
    R index.js:64
    React 7
    unstable_runWithPriority scheduler.production.min.js:19
    React 6
    getData index.js:186
react-dom.production.min.js:209:194

_Screenshot:_
![image](https://user-images.githubusercontent.com/28574252/140189132-e2d46822-d2bb-4dfd-97c9-b38238c6d950.png)

**Comment by thomasstjerne** [comment]
Thanks @yroskov 
This was because of the various software updates that I deployed recently. I have now rolled back to master, and will fix this issue on the dev branch

**Comment by yroskov** [comment]
Working perfect today. Thanks!
