### ISSUE TITLE
Rename Assembly menu to Browse?

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/checklistbank#960]
The assembly menu in a project is really the tree browsing with editorial options.
We should rename it to "Browse" like we have it for other trees. Then it is also less confusing to editor users which are only managing the tree.

**Comment by mdoering** [comment]
@thomasstjerne @yroskov ?

**Comment by mdoering** [comment]
Yes, I am talking about the "Assembly" menu item. 
It has a dual functionality, mapping sectors and managing the tree.
If there are projects that only manage the tree and do not work with sectors at all the name "Assembly" is not very well chosen. Also it is the only place to view the tree so it corresponds to the "Browse" functionality in the public datasets.

"Browse" or "Tree" I believe is more intuitive.

**Comment by yroskov** [comment]
**Strongly against renaming.**

For projects, other than CoL: if there are no sectors in the tree, means, there are no other contributing checklists. So, browsing available for a single checklist under "Browse" item in the menu. 

>Also it is the only place to view the tree 
Incorrect. If "global" checklist selected via search Dataset, "Browse" item in the menu can be used for browsing entire checklist:
![image](https://user-images.githubusercontent.com/28574252/140386347-32023636-2c8b-4a9f-9f5e-4e671a3539b2.png)

**Comment by mdoering** [comment]
This is not the project menu, it is the public one. We have 2 views for projects, a public one and a restricted project view   that you need have rights for.

**Comment by yroskov** [comment]
Both views are present in the menu, if user is registered as a project editor. So, both view are available for project insiders.

Being a project editor, I insist on the menu title "Assembly" as most appropriate name for the tool.  Term "Browse" does not reflect functionality of the assembly tool.

Why we are wasting our time?

**Comment by mdoering** [comment]
Imagine you are a taxonomist working on the Fabaceae checklist and want to modify taxa.
Would you think "Assembly" is an appropriate name for the page that allows to edit the tree?

We are facing additional requirements with pure taxonomic editing and need to find a good balance.
For projects that do not need sectors and only modify data within the project we should hide all sector and decision related parts in a project. That should work fine to hide unneeded complexity. But I then find the name of the menu item not intuitive at all. 

@thomasstjerne @dhobern any suggestions?

**Comment by yroskov** [comment]
Tool for taxonomic editing is a completely another development. Checklistbank is far away from such tool. Lot of new functionalities needed. 

If taxonomists need a tool for taxonomic editing - zoologists should go to TaxonWorks, ITIS, Aphia, botanists - to [Berlin Model], or whatever its new name is.  

@gdower, have look on this Markus idea

**Comment by dhobern** [comment]
For what it's worth, "assembly" doesn't sound clear to me.

**Comment by yroskov** [comment]
**Assembly tool** helps me (1) to identify GSD sectors and _assemble_ them in the CoL classification and (2) modify CoL tree.

**Comment by dhobern** [comment]
Sorry @yroskov - I fully understand the name. I just meant it seems an unclear name to share externally for users who are thinking more about editing/curation tasks.

**Comment by yroskov** [comment]
Task for building and editing checklists requires a separate tool in the Checklistbank. Assembly of CoL and maintaining of taxonomic checklists are different project types.
