### ISSUE TITLE
Show all agent information, especially notes

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/checklistbank#972]
The agent notes in metadata are important as they show on the COL portal.
Right now one has to look into each and every agent manually to see them.

They should be rendered with all other agent information in the metadata pages.
See also #971

**Comment by thomasstjerne** [comment]
In the dataset search? Or on dataset pages (the latter I guess?)

**Comment by mdoering** [comment]
on metadata pages and the forms
