### ISSUE TITLE
How I can share TASK reports with GSD authors?

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/checklistbank#973]
For attention of @thomasstjerne (@mdoering) 

I need to share four TASK reports with Michael Hassler for his assessment and possible corrections in the source data (for example, report _ACC-SYN species (different accepted, same authors)_:
https://data.catalogueoflife.org/catalogue/3/dataset/1141/duplicates?acceptedDifferent=true&authorshipDifferent=false&category=binomial&limit=500&minSize=2&mode=STRICT&offset=0&status=accepted&status=synonym )

- He is not able to open the link, because he has no permission in the checklistbank
- I cannot do export of the reports
- I tried to do copy&paste into Excel spreadsheet (only Firefox browser might be suitable for this), but columns in the spreadsheet were shifted in each row with decision label. Results are messy: 
![image](https://user-images.githubusercontent.com/28574252/144500757-ed501704-0622-4d04-86f2-80c4562726b7.png)

How I can share TASK reports with GSD authors?

**Comment by mdoering** [comment]
@thomasstjerne we need to have user management in the UI so you can give Michael permissions to view the project.
We also need a new REVIEWER role in the API that you can then assign to him and anyone else interested in viewing a project without the ability to change a project (and delete/corrupt things accidently).

This will take some time I am afraid. I might be able to get the API done by the end of next week, but cannot promise this. The only thing we can do now are a) screenshots and b) make Michael a true editor for a limited period of time and tell him clearly not to touch anything but view the task reports.

**Comment by mdoering** [comment]
actually the best right now is to print the page as a pdf like this one here:
[plants-duplicates.pdf](https://github.com/CatalogueOfLife/checklistbank/files/7645067/plants-duplicates.pdf)

@thomasstjerne can you add a printing css that hides the entire menu on the left?

**Comment by yroskov** [comment]
Oh! Print to pdf is a solution. Thanks!

**Comment by mdoering** [comment]
Are most of these ACC-SYN duplicates real? I would have expected species splits to happen mostly in the same genus, but here are species even placed in different families. That seems odd.

For example [Ampelocera hondurensis](https://www.jstor.org/stable/2399693?seq=1#metadata_info_tab_contents):

> It was approximately 50 years before the next species of Ampelocera, A. crenulata Urban and A. hondurensis J. D. Smith, were described. Those species, however, were not members of Ampelocera, nor even the Ulmaceae, and are presently placed into synonymy in genera in the Flacourtiaceae and Achatocarpaceae, respectively

Does not sound like an accepted name at all. WFO treats it only as a synonym:
http://worldfloraonline.org/search?query=Ampelocera+hondurensis
http://worldfloraonline.org/taxon/wfo-0000531436

**Comment by yroskov** [comment]
Let see, what Michael say

**Comment by thomasstjerne** [comment]
> actually the best right now is to print the page as a pdf like this one here: [plants-duplicates.pdf](https://github.com/CatalogueOfLife/checklistbank/files/7645067/plants-duplicates.pdf)
> 
> @thomasstjerne can you add a printing css that hides the entire menu on the left?

For now I suggest to just collapse the menu while printing 
![Screenshot at Dec 06 11-08-18](https://user-images.githubusercontent.com/1666484/144827730-485ccb60-3cf9-46fe-8eb3-50908426d572.png)

**Comment by yroskov** [comment]
2021-12-16 

@thomasstjerne & @mdoering. I am adding request to the existing ticket. 

As we discussed with Michael (as a user) and at our today's standup, it would be helpful to **add an option with each TASKS and ISSUES reports for exporting data into CSV file**. 

If it's doable, option "Export to CSV" will be helpful also with each report generated via **Workbench**. 

This simple solution will allow every user to take CSV file, open it in the MS Excel, sort and filter data as he want.

**Comment by mdoering** [comment]
@thomasstjerne there now is an export to CSV or TSV method in the duplicates API.
It is the same resource, but with a different Accept header of `text/csv` or `text/tsv`

**Comment by thomasstjerne** [comment]
Will it generate all rows, or does pagination still Apply?

**Comment by mdoering** [comment]
It will be all rows without pagination. I could add an optional page though. It is quite tricky how the results are generated, it is not a single query and I have to keep all data in memory before I can respond.

**Comment by thomasstjerne** [comment]
Would it be possible as for tsv using a query param?
The reason is that I cant add http headers on a regular html link. Therefore to get the data by http header, I actually have to fetch data and then create the file in the browser using HTML5 File Api and then trigger a download from there. This puts a potential limit on the file size based on the browsers capacity.

**Comment by mdoering** [comment]
you can enforce the Accept header by adding a suffix to the URL in any COL API resource.
The understood suffices are here:

https://github.com/CatalogueOfLife/backend/blob/master/webservice/src/main/java/life/catalogue/dw/jersey/filter/SuffixAcceptRequestFilter.java#L26


so `/dataset/3/duplicate.tsv` would request the TSV, `/dataset/3/duplicate.csv` the CSV!

**Comment by mdoering** [comment]
for example:

http://api.catalogueoflife.org/dataset/3LR.json
http://api.catalogueoflife.org/dataset/3LR.yaml
http://api.catalogueoflife.org/dataset/3LR.xml

**Comment by thomasstjerne** [comment]
Solves the problem!
