### ISSUE TITLE
Improving dataset search performance

### ISSUE THREAD

**Issue by gdower** [CatalogueOfLife/checklistbank#974]
The default view of the [dataset search](https://data.catalogueoflife.org/dataset?limit=50&offset=0) takes too long to load because by default it is populating the datasets table with 50 unrequested search results. While the data is loading, the search interface hangs so it's not possible to search for the desired dataset until the unrequested empty search results load. It would be preferable to not load any search results by default until the user enters a search term, or perhaps add a browse datasets button that will load the full datasets list.

Lowering the search limit to 5 helps a lot and could at least temporarily improve performance.

**Comment by mdoering** [comment]
How long does the loading of the default view take? It is 1-2s here from Berlin which isn't instant, but also not unbearable.
Limiting to 10 as a default would be reasonable in any case as only 9 fit onto my screen.

**Comment by gdower** [comment]
15 seconds

**Comment by mdoering** [comment]
Wow, thats unexpected. There must be many other slow pages then I suppose?
Was this always the case or could it be your specific connection? Same on the mobile network?

**Comment by mdoering** [comment]
https://tools.pingdom.com/#5f5f473fd8000000 claims 869ms for all 64 requests.
Also the 50 datasets are loaded with 1 quick call to the API. It is mostly logos that are loaded. Does removing them from your list make it much faster?

**Comment by mdoering** [comment]
@thomasstjerne I see that every page now does a call to list up to 1000 projects:
https://api.catalogueoflife.org/dataset?origin=managed&limit=1000

What is this for and why on every page? And are we sure we want 1000 once we reach that limit?

**Comment by gdower** [comment]
It's going a bit faster now, although the datasets page usually loads slow for me:

![image](https://user-images.githubusercontent.com/8573609/144511012-56f2b369-29fc-409c-8082-90185086f10b.png)

Some users probably will want the browse dataset feature, but having fast dataset search is important. We could meet both use cases if there was a landing page that just loads the search interface with a browse button, or maybe if the sidebar had dataset search built in?

**Comment by mdoering** [comment]
Have you tried without the logos?

**Comment by gdower** [comment]
It took longer to load without logos:

![image](https://user-images.githubusercontent.com/8573609/144514060-0c7ac11a-939d-4553-9fca-7d95aa280494.png)

I think it is a react rendering performance issue. The backend API call is pretty quick for 50 datasets.
