### ISSUE TITLE
Preserve upload file names

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/checklistbank#977]
When uploading data, the filename is sometimes important and should be preserved.
In archives this does not matter, but if a single CSV file is uploaded the name is used to define the rowType:

`Use encoding UTF-8 for file upload-6619605852204988001.csv`

The original name was NameUsage.csv, not upload-6619605852204988001.csv

**Comment by thomasstjerne** [comment]
I might be wrong, but I think that the filename is generated [here](https://github.com/CatalogueOfLife/backend/blob/f25e7ea69a4e17d47bd15081db71eb6828aba238/webservice/src/main/java/life/catalogue/importer/ImportManager.java#L387)

We are posting files using content type headers based on the file type. When uploading from a form using `Content-Type: multipart/form-data` the server would usually be able to get the filename through a `Content-Disposition: form-data; name="my_form_field"; filename="example.txt"` header. 
I don´t know if we should maybe use a `Content-Disposition` header? (I tried but this gave a cors error)

**Comment by mdoering** [comment]
you are right;) We could be using any header to include the filename. What does the UI currently do, is it included anywhere already?

**Comment by mdoering** [comment]
well, we could as well include a `filename` query parameter - that's actually the most simple

**Comment by thomasstjerne** [comment]
> well, we could as well include a `filename` query parameter - that's actually the most simple

That would be just fine as well

**Comment by mdoering** [comment]
I will implement an optional `filename` query parameter. Please add this to the UI already even if the API is not yet deployed
