### ISSUE TITLE
Show all related verbatim records for a taxon

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/checklistbank#978]
The verbatim section on a taxon page shows the single verbatim taxon.csv record.
A lot of the displayed information is coming from other verbatim records though. It would be great to show them all on that page.

 - the single name record
 - the related records which have taxonID={ID value}, just like [the browser does](https://data.catalogueoflife.org/dataset/2362/verbatim?type=col%3ATaxon&type=col%3ASynonym&type=col%3ATreatment&type=col%3ASpeciesInteraction&type=col%3ATaxonConceptRelation&type=col%3ASpeciesEstimate&type=col%3AMedia&type=col%3ADistribution&type=col%3AVernacularName&col:parentID=10869&col:taxonID=10869&col:taxonID=10869&col:taxonID=10869&col:relatedTaxonID=10869&col:taxonID=10869&col:relatedTaxonID=10869&col:taxonID=10869&col:taxonID=10869&col:taxonID=10869&col:taxonID=10869&termOp=OR)
 - the name related records which refer to the nameID (name relations, type material, references)

**Comment by thomasstjerne** [comment]
I would need to know the possible options of which verbatim types that could be the main record behind an interpreted Taxon record. And for each of those, which term will be the primary key. I guess this will currently be:

`col:Taxon` PK: `col:ID`
`acef:AcceptedSpecies` PK: `acef:AcceptedTaxonID`
`dwc:Taxon` PK: `dwca:ID`

Others?

This is because I need to find the PrimaryKey in an object like this: https://api.checklistbank.org/dataset/1010/verbatim/268911

**Comment by mdoering** [comment]
Don't we have that already configured as JSON somewhere for the verbatim browser?

**Comment by thomasstjerne** [comment]
Yes [here](https://github.com/CatalogueOfLife/checklistbank/blob/master/public/terms.json) - but dont think I can infer what the primary key would be from that one?

**Comment by thomasstjerne** [comment]
Looks like `col:NameUsage` PK: `col:ID` would also be a possible source of an interpreted Taxon page

**Comment by mdoering** [comment]
Isnt this a list of foreign keys with their PK in a sublist? The sublist is mostly there because we can have various uses of the standards, e.g. DwC-A can use either dwc:taxonID or dwca:id.

**Comment by mdoering** [comment]
Ye, unfortunately all standards provide different options. ColDP allows users to either use the NameUsage entity or Taxon/Synonym/Name entities. This is making things hard for consumers :(

**Comment by thomasstjerne** [comment]
I will indeed use the existing term map. It is just that in this case, I need to figure out where to start the graph (so to speak).
In the existing browser it is really down to each term (where do this link to)

**Comment by thomasstjerne** [comment]
I think I will just start with those four types, then we will see if something is missing down the road
