### ISSUE TITLE
Checklist Bank options not working

### ISSUE THREAD

**Issue by redewalt** [CatalogueOfLife/checklistbank#987]
I visited this page from Checklist Bank, https://data.catalogueoflife.org/dataset/2366/sourcemetrics. It is very difficult to view. There is no horizontal scroll bar until you are at the bottom of the page. Trying to download sources could not be accomplished from the top "Biota", there is no result as found in the public version of COL. I then tried Animalia, which was found. I signed in to a GBIF login! for download and a result was supposed to be sent to link. Clicking on the link produced no data set.

**Comment by redewalt** [comment]
I could download if no root was specified. It would have been half a gb, so I stopped it. What I wanted was the tallies for sources, not all data. How do I get that?

**Comment by mdoering** [comment]
Hi Ed, I fail to understand what you were trying to achieve. The linked page are simply source metrics for the COL december 2021 release. You cannot download anything from there, just from the downloads page I suppose you then visited?

**Comment by redewalt** [comment]
Markus,

I hoped to be able to grab the "more advanced Checklist Bank metrics". It is obviously not meant for use, I'll avoid it.

Ed
________________________________

**Comment by mdoering** [comment]
@redewalt it is meant for use and we do use it internally. Please leave a constructive feedback what makes you think this is not the case so things can be improved.

**Comment by redewalt** [comment]
I have already stated what was difficult to work with on the table. You decided to ignore it, for whatever reason. A horizontal scroll bar is only available at the very bottom of the table. I cannot see the entire table. I want the horizontal scroll bar fixed in the view so that I can use it at any part of the table. Also, the metric names were not defined. I don't know what most of them mean, though I can guess, but why make me or anyone else do that? Still, it would be excellent to be able to download the table of metrics if they are actually to be used. Have a nice day.
