### ISSUE TITLE
I have no access to the checklistbank

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/checklistbank#988]
@thomasstjerne, @mdoering, @gdower,   I have no access to the checklistbank, and cannot finalise Janury release. 

First, I have got 403 error - no access. Then, I tried to do re-login, I have got this message:

![image](https://user-images.githubusercontent.com/28574252/149544047-d31dba12-3c4b-47f9-90c2-0ca83411a5e3.png)

**Browser: Firefox 96.0.1**

**Comment by mdoering** [comment]
@yroskov, I will make you an admin for the next days. Seems I have broken editorial access when I tried to provide the reviewer role. with admin its working for me, I will make sure to fix the editorial access over the next hours.

It would be good to get these kind of serious bugs reported in Slack so we can quickly discuss things.

**Comment by yroskov** [comment]
Thanks!

>Slack
Our University insists to use Microsoft Teams for communications for Uni buisiness

**Comment by mdoering** [comment]
I have Teams if you prefer that I am happy to use it. You are an admin now, please log out and back in again!

**Comment by mdoering** [comment]
Finally works again and also includes support for reviewers.
